package yarnwrap.server.command;
public class FunctionCommand { public net.minecraft.server.command.FunctionCommand wrapperContained; public FunctionCommand(net.minecraft.server.command.FunctionCommand wrapperContained) { this.wrapperContained = wrapperContained; }

// public com.mojang.brigadier.suggestion.SuggestionProvider SUGGESTION_PROVIDER() { return wrapperContained.SUGGESTION_PROVIDER; }
// public void SUGGESTION_PROVIDER(com.mojang.brigadier.suggestion.SuggestionProvider value) { wrapperContained.SUGGESTION_PROVIDER = value; }
public static com.mojang.brigadier.suggestion.SuggestionProvider SUGGESTION_PROVIDER() { return net.minecraft.server.command.FunctionCommand.SUGGESTION_PROVIDER; }
// public static void SUGGESTION_PROVIDER(com.mojang.brigadier.suggestion.SuggestionProvider value, ) { net.minecraft.server.command.FunctionCommand.SUGGESTION_PROVIDER = value; }

// public com.mojang.brigadier.exceptions.DynamicCommandExceptionType ARGUMENT_NOT_COMPOUND_EXCEPTION() { return wrapperContained.ARGUMENT_NOT_COMPOUND_EXCEPTION; }
// public void ARGUMENT_NOT_COMPOUND_EXCEPTION(com.mojang.brigadier.exceptions.DynamicCommandExceptionType value) { wrapperContained.ARGUMENT_NOT_COMPOUND_EXCEPTION = value; }
// public static com.mojang.brigadier.exceptions.DynamicCommandExceptionType ARGUMENT_NOT_COMPOUND_EXCEPTION() { return net.minecraft.server.command.FunctionCommand.ARGUMENT_NOT_COMPOUND_EXCEPTION; }
// public static void ARGUMENT_NOT_COMPOUND_EXCEPTION(com.mojang.brigadier.exceptions.DynamicCommandExceptionType value, ) { net.minecraft.server.command.FunctionCommand.ARGUMENT_NOT_COMPOUND_EXCEPTION = value; }

// public com.mojang.brigadier.exceptions.DynamicCommandExceptionType NO_FUNCTIONS_EXCEPTION() { return wrapperContained.NO_FUNCTIONS_EXCEPTION; }
// public void NO_FUNCTIONS_EXCEPTION(com.mojang.brigadier.exceptions.DynamicCommandExceptionType value) { wrapperContained.NO_FUNCTIONS_EXCEPTION = value; }
// public static com.mojang.brigadier.exceptions.DynamicCommandExceptionType NO_FUNCTIONS_EXCEPTION() { return net.minecraft.server.command.FunctionCommand.NO_FUNCTIONS_EXCEPTION; }
// public static void NO_FUNCTIONS_EXCEPTION(com.mojang.brigadier.exceptions.DynamicCommandExceptionType value, ) { net.minecraft.server.command.FunctionCommand.NO_FUNCTIONS_EXCEPTION = value; }

// public com.mojang.brigadier.exceptions.Dynamic2CommandExceptionType INSTANTIATION_FAILURE_EXCEPTION() { return wrapperContained.INSTANTIATION_FAILURE_EXCEPTION; }
// public void INSTANTIATION_FAILURE_EXCEPTION(com.mojang.brigadier.exceptions.Dynamic2CommandExceptionType value) { wrapperContained.INSTANTIATION_FAILURE_EXCEPTION = value; }
public static com.mojang.brigadier.exceptions.Dynamic2CommandExceptionType INSTANTIATION_FAILURE_EXCEPTION() { return net.minecraft.server.command.FunctionCommand.INSTANTIATION_FAILURE_EXCEPTION; }
// public static void INSTANTIATION_FAILURE_EXCEPTION(com.mojang.brigadier.exceptions.Dynamic2CommandExceptionType value, ) { net.minecraft.server.command.FunctionCommand.INSTANTIATION_FAILURE_EXCEPTION = value; }

// public Object RESULT_REPORTER() { return wrapperContained.RESULT_REPORTER; }
// // public void RESULT_REPORTER(Object value) { wrapperContained.RESULT_REPORTER = value; }
// // public static Object RESULT_REPORTER() { return net.minecraft.server.command.FunctionCommand.RESULT_REPORTER; }
// // public static void RESULT_REPORTER(Object value, ) { net.minecraft.server.command.FunctionCommand.RESULT_REPORTER = value; }

// public void register(com.mojang.brigadier.CommandDispatcher dispatcher) { wrapperContained.register(dispatcher); }
// public static void register(com.mojang.brigadier.CommandDispatcher dispatcher, ) { net.minecraft.server.command.FunctionCommand.register(dispatcher); }
// public java.util.concurrent.CompletableFuture method_13382(com.mojang.brigadier.context.CommandContext context,com.mojang.brigadier.suggestion.SuggestionsBuilder builder) { return wrapperContained.method_13382(context,builder); }
// public static java.util.concurrent.CompletableFuture method_13382(com.mojang.brigadier.context.CommandContext context,com.mojang.brigadier.suggestion.SuggestionsBuilder builder, ) { return net.minecraft.server.command.FunctionCommand.method_13382(context,builder); }
// public com.mojang.brigadier.builder.ArgumentBuilder method_52309(Object builder) { return wrapperContained.method_52309(builder); }
// public static com.mojang.brigadier.builder.ArgumentBuilder method_52309(Object builder, ) { return net.minecraft.server.command.FunctionCommand.method_52309(builder); }
// public yarnwrap.nbt.NbtCompound getArgument(Object path,yarnwrap.command.DataCommandObject object) { return new yarnwrap.nbt.NbtCompound(wrapperContained.getArgument(path,object.wrapperContained)); }
// public static yarnwrap.nbt.NbtCompound getArgument(Object path,yarnwrap.command.DataCommandObject object, ) { return new yarnwrap.nbt.NbtCompound(net.minecraft.server.command.FunctionCommand.getArgument(path,object.wrapperContained)); }
// public com.mojang.brigadier.Message method_52314(java.lang.Object argument) { return wrapperContained.method_52314(argument); }
// public static com.mojang.brigadier.Message method_52314(java.lang.Object argument, ) { return net.minecraft.server.command.FunctionCommand.method_52314(argument); }
// public yarnwrap.server.command.ServerCommandSource createFunctionCommandSource(yarnwrap.server.command.ServerCommandSource source) { return new yarnwrap.server.command.ServerCommandSource(wrapperContained.createFunctionCommandSource(source.wrapperContained)); }
// public static yarnwrap.server.command.ServerCommandSource createFunctionCommandSource(yarnwrap.server.command.ServerCommandSource source, ) { return new yarnwrap.server.command.ServerCommandSource(net.minecraft.server.command.FunctionCommand.createFunctionCommandSource(source.wrapperContained)); }
// public com.mojang.brigadier.Message method_54273(java.lang.Object argument) { return wrapperContained.method_54273(argument); }
// public static com.mojang.brigadier.Message method_54273(java.lang.Object argument, ) { return net.minecraft.server.command.FunctionCommand.method_54273(argument); }
// public com.mojang.brigadier.Message method_54274(java.lang.Object argument,java.lang.Object argument2) { return wrapperContained.method_54274(argument,argument2); }
// public static com.mojang.brigadier.Message method_54274(java.lang.Object argument,java.lang.Object argument2, ) { return net.minecraft.server.command.FunctionCommand.method_54274(argument,argument2); }
// public void enqueueAction(java.util.Collection commandFunctions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer,yarnwrap.command.ExecutionFlags flags) { wrapperContained.enqueueAction(commandFunctions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer,flags.wrapperContained); }
// public static void enqueueAction(java.util.Collection commandFunctions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer,yarnwrap.command.ExecutionFlags flags, ) { net.minecraft.server.command.FunctionCommand.enqueueAction(commandFunctions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer,flags.wrapperContained); }
// public void method_54855(Object context,yarnwrap.command.ReturnValueConsumer frame) { wrapperContained.method_54855(context,frame.wrapperContained); }
// public static void method_54855(Object context,yarnwrap.command.ReturnValueConsumer frame, ) { net.minecraft.server.command.FunctionCommand.method_54855(context,frame.wrapperContained); }
// public void method_54856(Object successful,boolean returnValue) { wrapperContained.method_54856(successful,returnValue); }
// public static void method_54856(Object successful,boolean returnValue, ) { net.minecraft.server.command.FunctionCommand.method_54856(successful,returnValue); }
// public void method_54857(Object successful,yarnwrap.server.command.AbstractServerCommandSource returnValue) { wrapperContained.method_54857(successful,returnValue.wrapperContained); }
// public static void method_54857(Object successful,yarnwrap.server.command.AbstractServerCommandSource returnValue, ) { net.minecraft.server.command.FunctionCommand.method_54857(successful,returnValue.wrapperContained); }
// public yarnwrap.command.ReturnValueConsumer wrapReturnValueConsumer(yarnwrap.server.command.AbstractServerCommandSource flags,Object resultConsumer,yarnwrap.util.Identifier id,yarnwrap.command.ReturnValueConsumer wrapped) { return new yarnwrap.command.ReturnValueConsumer(wrapperContained.wrapReturnValueConsumer(flags.wrapperContained,resultConsumer,id.wrapperContained,wrapped.wrapperContained)); }
// public static yarnwrap.command.ReturnValueConsumer wrapReturnValueConsumer(yarnwrap.server.command.AbstractServerCommandSource flags,Object resultConsumer,yarnwrap.util.Identifier id,yarnwrap.command.ReturnValueConsumer wrapped, ) { return new yarnwrap.command.ReturnValueConsumer(net.minecraft.server.command.FunctionCommand.wrapReturnValueConsumer(flags.wrapperContained,resultConsumer,id.wrapperContained,wrapped.wrapperContained)); }
// public void enqueueInReturnRun(java.util.Collection functions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer) { wrapperContained.enqueueInReturnRun(functions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer); }
// public static void enqueueInReturnRun(java.util.Collection functions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer, ) { net.minecraft.server.command.FunctionCommand.enqueueInReturnRun(functions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer); }
// public void enqueueFunction(yarnwrap.nbt.NbtCompound args,yarnwrap.command.ExecutionControl control,com.mojang.brigadier.CommandDispatcher dispatcher,yarnwrap.server.command.AbstractServerCommandSource source,yarnwrap.server.function.CommandFunction function,yarnwrap.util.Identifier id,yarnwrap.command.ReturnValueConsumer returnValueConsumer,boolean propagateReturn) { wrapperContained.enqueueFunction(args.wrapperContained,control.wrapperContained,dispatcher,source.wrapperContained,function.wrapperContained,id.wrapperContained,returnValueConsumer.wrapperContained,propagateReturn); }
// public static void enqueueFunction(yarnwrap.nbt.NbtCompound args,yarnwrap.command.ExecutionControl control,com.mojang.brigadier.CommandDispatcher dispatcher,yarnwrap.server.command.AbstractServerCommandSource source,yarnwrap.server.function.CommandFunction function,yarnwrap.util.Identifier id,yarnwrap.command.ReturnValueConsumer returnValueConsumer,boolean propagateReturn, ) { net.minecraft.server.command.FunctionCommand.enqueueFunction(args.wrapperContained,control.wrapperContained,dispatcher,source.wrapperContained,function.wrapperContained,id.wrapperContained,returnValueConsumer.wrapperContained,propagateReturn); }
// public void enqueueOutsideReturnRun(java.util.Collection functions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer) { wrapperContained.enqueueOutsideReturnRun(functions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer); }
// public static void enqueueOutsideReturnRun(java.util.Collection functions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer, ) { net.minecraft.server.command.FunctionCommand.enqueueOutsideReturnRun(functions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer); }

}