package yarnwrap.network.listener;
public class ClientPlayPacketListener { public net.minecraft.network.listener.ClientPlayPacketListener wrapperContained; public ClientPlayPacketListener(net.minecraft.network.listener.ClientPlayPacketListener wrapperContained) { this.wrapperContained = wrapperContained; }

public void onParticle(yarnwrap.network.packet.s2c.play.ParticleS2CPacket packet) { wrapperContained.onParticle(packet.wrapperContained); }
public void onBossBar(yarnwrap.network.packet.s2c.play.BossBarS2CPacket packet) { wrapperContained.onBossBar(packet.wrapperContained); }
public void onWorldTimeUpdate(yarnwrap.network.packet.s2c.play.WorldTimeUpdateS2CPacket packet) { wrapperContained.onWorldTimeUpdate(packet.wrapperContained); }
public void onEntityPassengersSet(yarnwrap.network.packet.s2c.play.EntityPassengersSetS2CPacket packet) { wrapperContained.onEntityPassengersSet(packet.wrapperContained); }
public void onCommandSuggestions(yarnwrap.network.packet.s2c.play.CommandSuggestionsS2CPacket packet) { wrapperContained.onCommandSuggestions(packet.wrapperContained); }
public void onStopSound(yarnwrap.network.packet.s2c.play.StopSoundS2CPacket packet) { wrapperContained.onStopSound(packet.wrapperContained); }
public void onEntityStatusEffect(yarnwrap.network.packet.s2c.play.EntityStatusEffectS2CPacket packet) { wrapperContained.onEntityStatusEffect(packet.wrapperContained); }
public void onGameStateChange(yarnwrap.network.packet.s2c.play.GameStateChangeS2CPacket packet) { wrapperContained.onGameStateChange(packet.wrapperContained); }
public void onEntityPosition(yarnwrap.network.packet.s2c.play.EntityPositionS2CPacket packet) { wrapperContained.onEntityPosition(packet.wrapperContained); }
public void onCooldownUpdate(yarnwrap.network.packet.s2c.play.CooldownUpdateS2CPacket packet) { wrapperContained.onCooldownUpdate(packet.wrapperContained); }
public void onMapUpdate(yarnwrap.network.packet.s2c.play.MapUpdateS2CPacket packet) { wrapperContained.onMapUpdate(packet.wrapperContained); }
public void onOpenHorseScreen(yarnwrap.network.packet.s2c.play.OpenHorseScreenS2CPacket packet) { wrapperContained.onOpenHorseScreen(packet.wrapperContained); }
public void onCraftFailedResponse(yarnwrap.network.packet.s2c.play.CraftFailedResponseS2CPacket packet) { wrapperContained.onCraftFailedResponse(packet.wrapperContained); }
public void onExperienceOrbSpawn(yarnwrap.network.packet.s2c.play.ExperienceOrbSpawnS2CPacket packet) { wrapperContained.onExperienceOrbSpawn(packet.wrapperContained); }
public void onLookAt(yarnwrap.network.packet.s2c.play.LookAtS2CPacket packet) { wrapperContained.onLookAt(packet.wrapperContained); }
public void onEntityTrackerUpdate(yarnwrap.network.packet.s2c.play.EntityTrackerUpdateS2CPacket packet) { wrapperContained.onEntityTrackerUpdate(packet.wrapperContained); }
public void onBlockEntityUpdate(yarnwrap.network.packet.s2c.play.BlockEntityUpdateS2CPacket packet) { wrapperContained.onBlockEntityUpdate(packet.wrapperContained); }
public void onEntitiesDestroy(yarnwrap.network.packet.s2c.play.EntitiesDestroyS2CPacket packet) { wrapperContained.onEntitiesDestroy(packet.wrapperContained); }
public void onWorldEvent(yarnwrap.network.packet.s2c.play.WorldEventS2CPacket packet) { wrapperContained.onWorldEvent(packet.wrapperContained); }
public void onTeam(yarnwrap.network.packet.s2c.play.TeamS2CPacket packet) { wrapperContained.onTeam(packet.wrapperContained); }
public void onChunkDeltaUpdate(yarnwrap.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket packet) { wrapperContained.onChunkDeltaUpdate(packet.wrapperContained); }
public void onExperienceBarUpdate(yarnwrap.network.packet.s2c.play.ExperienceBarUpdateS2CPacket packet) { wrapperContained.onExperienceBarUpdate(packet.wrapperContained); }
public void onCloseScreen(yarnwrap.network.packet.s2c.play.CloseScreenS2CPacket packet) { wrapperContained.onCloseScreen(packet.wrapperContained); }
public void onPlayerListHeader(yarnwrap.network.packet.s2c.play.PlayerListHeaderS2CPacket packet) { wrapperContained.onPlayerListHeader(packet.wrapperContained); }
public void onSynchronizeRecipes(yarnwrap.network.packet.s2c.play.SynchronizeRecipesS2CPacket packet) { wrapperContained.onSynchronizeRecipes(packet.wrapperContained); }
public void onUnloadChunk(yarnwrap.network.packet.s2c.play.UnloadChunkS2CPacket packet) { wrapperContained.onUnloadChunk(packet.wrapperContained); }
public void onSignEditorOpen(yarnwrap.network.packet.s2c.play.SignEditorOpenS2CPacket packet) { wrapperContained.onSignEditorOpen(packet.wrapperContained); }
public void onScreenHandlerSlotUpdate(yarnwrap.network.packet.s2c.play.ScreenHandlerSlotUpdateS2CPacket packet) { wrapperContained.onScreenHandlerSlotUpdate(packet.wrapperContained); }
public void onEntityAttach(yarnwrap.network.packet.s2c.play.EntityAttachS2CPacket packet) { wrapperContained.onEntityAttach(packet.wrapperContained); }
public void onSetCameraEntity(yarnwrap.network.packet.s2c.play.SetCameraEntityS2CPacket packet) { wrapperContained.onSetCameraEntity(packet.wrapperContained); }
public void onEntitySpawn(yarnwrap.network.packet.s2c.play.EntitySpawnS2CPacket packet) { wrapperContained.onEntitySpawn(packet.wrapperContained); }
public void onPlayerList(yarnwrap.network.packet.s2c.play.PlayerListS2CPacket packet) { wrapperContained.onPlayerList(packet.wrapperContained); }
public void onUnlockRecipes(yarnwrap.network.packet.s2c.play.ChangeUnlockedRecipesS2CPacket packet) { wrapperContained.onUnlockRecipes(packet.wrapperContained); }
public void onBlockBreakingProgress(yarnwrap.network.packet.s2c.play.BlockBreakingProgressS2CPacket packet) { wrapperContained.onBlockBreakingProgress(packet.wrapperContained); }
public void onPlayerRespawn(yarnwrap.network.packet.s2c.play.PlayerRespawnS2CPacket packet) { wrapperContained.onPlayerRespawn(packet.wrapperContained); }
public void onScoreboardScoreUpdate(yarnwrap.network.packet.s2c.play.ScoreboardScoreUpdateS2CPacket packet) { wrapperContained.onScoreboardScoreUpdate(packet.wrapperContained); }
public void onRemoveEntityStatusEffect(yarnwrap.network.packet.s2c.play.RemoveEntityStatusEffectS2CPacket packet) { wrapperContained.onRemoveEntityStatusEffect(packet.wrapperContained); }
public void onGameJoin(yarnwrap.network.packet.s2c.play.GameJoinS2CPacket packet) { wrapperContained.onGameJoin(packet.wrapperContained); }
public void onHealthUpdate(yarnwrap.network.packet.s2c.play.HealthUpdateS2CPacket packet) { wrapperContained.onHealthUpdate(packet.wrapperContained); }
public void onExplosion(yarnwrap.network.packet.s2c.play.ExplosionS2CPacket packet) { wrapperContained.onExplosion(packet.wrapperContained); }
public void onPlaySoundFromEntity(yarnwrap.network.packet.s2c.play.PlaySoundFromEntityS2CPacket packet) { wrapperContained.onPlaySoundFromEntity(packet.wrapperContained); }
public void onNbtQueryResponse(yarnwrap.network.packet.s2c.play.NbtQueryResponseS2CPacket packet) { wrapperContained.onNbtQueryResponse(packet.wrapperContained); }
public void onChunkData(yarnwrap.network.packet.s2c.play.ChunkDataS2CPacket packet) { wrapperContained.onChunkData(packet.wrapperContained); }
public void onStatistics(yarnwrap.network.packet.s2c.play.StatisticsS2CPacket packet) { wrapperContained.onStatistics(packet.wrapperContained); }
public void onAdvancements(yarnwrap.network.packet.s2c.play.AdvancementUpdateS2CPacket packet) { wrapperContained.onAdvancements(packet.wrapperContained); }
public void onScreenHandlerPropertyUpdate(yarnwrap.network.packet.s2c.play.ScreenHandlerPropertyUpdateS2CPacket packet) { wrapperContained.onScreenHandlerPropertyUpdate(packet.wrapperContained); }
public void onEntityVelocityUpdate(yarnwrap.network.packet.s2c.play.EntityVelocityUpdateS2CPacket packet) { wrapperContained.onEntityVelocityUpdate(packet.wrapperContained); }
public void onVehicleMove(yarnwrap.network.packet.s2c.play.VehicleMoveS2CPacket packet) { wrapperContained.onVehicleMove(packet.wrapperContained); }
public void onUpdateSelectedSlot(yarnwrap.network.packet.s2c.play.UpdateSelectedSlotS2CPacket packet) { wrapperContained.onUpdateSelectedSlot(packet.wrapperContained); }
public void onBlockUpdate(yarnwrap.network.packet.s2c.play.BlockUpdateS2CPacket packet) { wrapperContained.onBlockUpdate(packet.wrapperContained); }
public void onEntitySetHeadYaw(yarnwrap.network.packet.s2c.play.EntitySetHeadYawS2CPacket packet) { wrapperContained.onEntitySetHeadYaw(packet.wrapperContained); }
public void onDifficulty(yarnwrap.network.packet.s2c.play.DifficultyS2CPacket packet) { wrapperContained.onDifficulty(packet.wrapperContained); }
public void onPlayerSpawnPosition(yarnwrap.network.packet.s2c.play.PlayerSpawnPositionS2CPacket packet) { wrapperContained.onPlayerSpawnPosition(packet.wrapperContained); }
public void onLightUpdate(yarnwrap.network.packet.s2c.play.LightUpdateS2CPacket packet) { wrapperContained.onLightUpdate(packet.wrapperContained); }
public void onScoreboardObjectiveUpdate(yarnwrap.network.packet.s2c.play.ScoreboardObjectiveUpdateS2CPacket packet) { wrapperContained.onScoreboardObjectiveUpdate(packet.wrapperContained); }
public void onCommandTree(yarnwrap.network.packet.s2c.play.CommandTreeS2CPacket packet) { wrapperContained.onCommandTree(packet.wrapperContained); }
public void onPlaySound(yarnwrap.network.packet.s2c.play.PlaySoundS2CPacket packet) { wrapperContained.onPlaySound(packet.wrapperContained); }
public void onEntityStatus(yarnwrap.network.packet.s2c.play.EntityStatusS2CPacket packet) { wrapperContained.onEntityStatus(packet.wrapperContained); }
public void onEntityAttributes(yarnwrap.network.packet.s2c.play.EntityAttributesS2CPacket packet) { wrapperContained.onEntityAttributes(packet.wrapperContained); }
public void onItemPickupAnimation(yarnwrap.network.packet.s2c.play.ItemPickupAnimationS2CPacket packet) { wrapperContained.onItemPickupAnimation(packet.wrapperContained); }
public void onEntityEquipmentUpdate(yarnwrap.network.packet.s2c.play.EntityEquipmentUpdateS2CPacket packet) { wrapperContained.onEntityEquipmentUpdate(packet.wrapperContained); }
public void onInventory(yarnwrap.network.packet.s2c.play.InventoryS2CPacket packet) { wrapperContained.onInventory(packet.wrapperContained); }
public void onPlayerAbilities(yarnwrap.network.packet.s2c.play.PlayerAbilitiesS2CPacket packet) { wrapperContained.onPlayerAbilities(packet.wrapperContained); }
public void onEntity(yarnwrap.network.packet.s2c.play.EntityS2CPacket packet) { wrapperContained.onEntity(packet.wrapperContained); }
public void onPlayerPositionLook(yarnwrap.network.packet.s2c.play.PlayerPositionLookS2CPacket packet) { wrapperContained.onPlayerPositionLook(packet.wrapperContained); }
public void onBlockEvent(yarnwrap.network.packet.s2c.play.BlockEventS2CPacket packet) { wrapperContained.onBlockEvent(packet.wrapperContained); }
public void onScoreboardDisplay(yarnwrap.network.packet.s2c.play.ScoreboardDisplayS2CPacket packet) { wrapperContained.onScoreboardDisplay(packet.wrapperContained); }
public void onEntityAnimation(yarnwrap.network.packet.s2c.play.EntityAnimationS2CPacket packet) { wrapperContained.onEntityAnimation(packet.wrapperContained); }
public void onSelectAdvancementTab(yarnwrap.network.packet.s2c.play.SelectAdvancementTabS2CPacket packet) { wrapperContained.onSelectAdvancementTab(packet.wrapperContained); }
public void onOpenWrittenBook(yarnwrap.network.packet.s2c.play.OpenWrittenBookS2CPacket packet) { wrapperContained.onOpenWrittenBook(packet.wrapperContained); }
public void onSetTradeOffers(yarnwrap.network.packet.s2c.play.SetTradeOffersS2CPacket packet) { wrapperContained.onSetTradeOffers(packet.wrapperContained); }
public void onOpenScreen(yarnwrap.network.packet.s2c.play.OpenScreenS2CPacket packet) { wrapperContained.onOpenScreen(packet.wrapperContained); }
public void onChunkLoadDistance(yarnwrap.network.packet.s2c.play.ChunkLoadDistanceS2CPacket packet) { wrapperContained.onChunkLoadDistance(packet.wrapperContained); }
public void onChunkRenderDistanceCenter(yarnwrap.network.packet.s2c.play.ChunkRenderDistanceCenterS2CPacket packet) { wrapperContained.onChunkRenderDistanceCenter(packet.wrapperContained); }
public void onPlayerActionResponse(yarnwrap.network.packet.s2c.play.PlayerActionResponseS2CPacket packet) { wrapperContained.onPlayerActionResponse(packet.wrapperContained); }
public void onTitleClear(yarnwrap.network.packet.s2c.play.ClearTitleS2CPacket packet) { wrapperContained.onTitleClear(packet.wrapperContained); }
public void onWorldBorderInitialize(yarnwrap.network.packet.s2c.play.WorldBorderInitializeS2CPacket packet) { wrapperContained.onWorldBorderInitialize(packet.wrapperContained); }
public void onEndCombat(yarnwrap.network.packet.s2c.play.EndCombatS2CPacket packet) { wrapperContained.onEndCombat(packet.wrapperContained); }
public void onEnterCombat(yarnwrap.network.packet.s2c.play.EnterCombatS2CPacket packet) { wrapperContained.onEnterCombat(packet.wrapperContained); }
public void onDeathMessage(yarnwrap.network.packet.s2c.play.DeathMessageS2CPacket packet) { wrapperContained.onDeathMessage(packet.wrapperContained); }
public void onOverlayMessage(yarnwrap.network.packet.s2c.play.OverlayMessageS2CPacket packet) { wrapperContained.onOverlayMessage(packet.wrapperContained); }
public void onWorldBorderCenterChanged(yarnwrap.network.packet.s2c.play.WorldBorderCenterChangedS2CPacket packet) { wrapperContained.onWorldBorderCenterChanged(packet.wrapperContained); }
public void onWorldBorderInterpolateSize(yarnwrap.network.packet.s2c.play.WorldBorderInterpolateSizeS2CPacket packet) { wrapperContained.onWorldBorderInterpolateSize(packet.wrapperContained); }
public void onWorldBorderSizeChanged(yarnwrap.network.packet.s2c.play.WorldBorderSizeChangedS2CPacket packet) { wrapperContained.onWorldBorderSizeChanged(packet.wrapperContained); }
public void onWorldBorderWarningTimeChanged(yarnwrap.network.packet.s2c.play.WorldBorderWarningTimeChangedS2CPacket packet) { wrapperContained.onWorldBorderWarningTimeChanged(packet.wrapperContained); }
public void onWorldBorderWarningBlocksChanged(yarnwrap.network.packet.s2c.play.WorldBorderWarningBlocksChangedS2CPacket packet) { wrapperContained.onWorldBorderWarningBlocksChanged(packet.wrapperContained); }
public void onSubtitle(yarnwrap.network.packet.s2c.play.SubtitleS2CPacket packet) { wrapperContained.onSubtitle(packet.wrapperContained); }
public void onTitle(yarnwrap.network.packet.s2c.play.TitleS2CPacket packet) { wrapperContained.onTitle(packet.wrapperContained); }
public void onTitleFade(yarnwrap.network.packet.s2c.play.TitleFadeS2CPacket packet) { wrapperContained.onTitleFade(packet.wrapperContained); }
public void onSimulationDistance(yarnwrap.network.packet.s2c.play.SimulationDistanceS2CPacket packet) { wrapperContained.onSimulationDistance(packet.wrapperContained); }
public void onChatMessage(yarnwrap.network.packet.s2c.play.ChatMessageS2CPacket packet) { wrapperContained.onChatMessage(packet.wrapperContained); }
public void onGameMessage(yarnwrap.network.packet.s2c.play.GameMessageS2CPacket packet) { wrapperContained.onGameMessage(packet.wrapperContained); }
public void onServerMetadata(yarnwrap.network.packet.s2c.play.ServerMetadataS2CPacket packet) { wrapperContained.onServerMetadata(packet.wrapperContained); }
public void onChatSuggestions(yarnwrap.network.packet.s2c.play.ChatSuggestionsS2CPacket packet) { wrapperContained.onChatSuggestions(packet.wrapperContained); }
public void onRemoveMessage(yarnwrap.network.packet.s2c.play.RemoveMessageS2CPacket packet) { wrapperContained.onRemoveMessage(packet.wrapperContained); }
public void onProfilelessChatMessage(yarnwrap.network.packet.s2c.play.ProfilelessChatMessageS2CPacket packet) { wrapperContained.onProfilelessChatMessage(packet.wrapperContained); }
public void onPlayerRemove(yarnwrap.network.packet.s2c.play.PlayerRemoveS2CPacket packet) { wrapperContained.onPlayerRemove(packet.wrapperContained); }
public void onBundle(yarnwrap.network.packet.s2c.play.BundleS2CPacket packet) { wrapperContained.onBundle(packet.wrapperContained); }
public void onDamageTilt(yarnwrap.network.packet.s2c.play.DamageTiltS2CPacket packet) { wrapperContained.onDamageTilt(packet.wrapperContained); }
public void onEntityDamage(yarnwrap.network.packet.s2c.play.EntityDamageS2CPacket packet) { wrapperContained.onEntityDamage(packet.wrapperContained); }
public void onChunkBiomeData(yarnwrap.network.packet.s2c.play.ChunkBiomeDataS2CPacket packet) { wrapperContained.onChunkBiomeData(packet.wrapperContained); }
public void onEnterReconfiguration(yarnwrap.network.packet.s2c.play.EnterReconfigurationS2CPacket packet) { wrapperContained.onEnterReconfiguration(packet.wrapperContained); }
public void onChunkSent(yarnwrap.network.packet.s2c.play.ChunkSentS2CPacket packet) { wrapperContained.onChunkSent(packet.wrapperContained); }
public void onStartChunkSend(yarnwrap.network.packet.s2c.play.StartChunkSendS2CPacket packet) { wrapperContained.onStartChunkSend(packet.wrapperContained); }
public void onUpdateTickRate(yarnwrap.network.packet.s2c.play.UpdateTickRateS2CPacket packet) { wrapperContained.onUpdateTickRate(packet.wrapperContained); }
public void onTickStep(yarnwrap.network.packet.s2c.play.TickStepS2CPacket packet) { wrapperContained.onTickStep(packet.wrapperContained); }
public void onScoreboardScoreReset(yarnwrap.network.packet.s2c.play.ScoreboardScoreResetS2CPacket packet) { wrapperContained.onScoreboardScoreReset(packet.wrapperContained); }
public void onDebugSample(yarnwrap.network.packet.s2c.play.DebugSampleS2CPacket packet) { wrapperContained.onDebugSample(packet.wrapperContained); }
public void onProjectilePower(yarnwrap.network.packet.s2c.play.ProjectilePowerS2CPacket packet) { wrapperContained.onProjectilePower(packet.wrapperContained); }

}