package yarnwrap.world.chunk;
public class ChunkGenerating { public net.minecraft.world.chunk.ChunkGenerating wrapperContained; public ChunkGenerating(net.minecraft.world.chunk.ChunkGenerating wrapperContained) { this.wrapperContained = wrapperContained; }

// public org.slf4j.Logger LOGGER() { return wrapperContained.LOGGER; }
// public void LOGGER(org.slf4j.Logger value) { wrapperContained.LOGGER = value; }
// public static org.slf4j.Logger LOGGER() { return net.minecraft.world.chunk.ChunkGenerating.LOGGER; }
// public static void LOGGER(org.slf4j.Logger value, ) { net.minecraft.world.chunk.ChunkGenerating.LOGGER = value; }

// public java.util.concurrent.CompletableFuture initializeLight(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.initializeLight(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture initializeLight(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.initializeLight(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public boolean isLightOn(yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.isLightOn(chunk.wrapperContained); }
// public static boolean isLightOn(yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.isLightOn(chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture noop(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.noop(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture noop(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.noop(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public yarnwrap.world.chunk.Chunk method_57599(yarnwrap.world.chunk.Chunk populated) { return new yarnwrap.world.chunk.Chunk(wrapperContained.method_57599(populated.wrapperContained)); }
// public static yarnwrap.world.chunk.Chunk method_57599(yarnwrap.world.chunk.Chunk populated, ) { return new yarnwrap.world.chunk.Chunk(net.minecraft.world.chunk.ChunkGenerating.method_57599(populated.wrapperContained)); }
// public java.util.concurrent.CompletableFuture loadStructures(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.loadStructures(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture loadStructures(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.loadStructures(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture generateStructures(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.generateStructures(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture generateStructures(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.generateStructures(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture generateStructureReferences(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.generateStructureReferences(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture generateStructureReferences(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.generateStructureReferences(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture populateBiomes(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.populateBiomes(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture populateBiomes(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.populateBiomes(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture populateNoise(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.populateNoise(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture populateNoise(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.populateNoise(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture buildSurface(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.buildSurface(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture buildSurface(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.buildSurface(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture carve(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.carve(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture carve(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.carve(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture generateFeatures(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.generateFeatures(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture generateFeatures(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.generateFeatures(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture generateEntities(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.generateEntities(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture generateEntities(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.generateEntities(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public void method_60551(yarnwrap.world.chunk.Chunk worldChunk) { wrapperContained.method_60551(worldChunk.wrapperContained); }
// public static void method_60551(yarnwrap.world.chunk.Chunk worldChunk, ) { net.minecraft.world.chunk.ChunkGenerating.method_60551(worldChunk.wrapperContained); }
// public void addEntities(yarnwrap.server.world.ServerWorld world,Object entities) { wrapperContained.addEntities(world.wrapperContained,entities); }
// public static void addEntities(yarnwrap.server.world.ServerWorld world,Object entities, ) { net.minecraft.world.chunk.ChunkGenerating.addEntities(world.wrapperContained,entities); }
// public java.util.concurrent.CompletableFuture light(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.light(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture light(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.light(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public java.util.concurrent.CompletableFuture convertToFullChunk(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk) { return wrapperContained.convertToFullChunk(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }
// public static java.util.concurrent.CompletableFuture convertToFullChunk(yarnwrap.world.chunk.ChunkGenerationContext context,yarnwrap.world.chunk.ChunkGenerationStep step,yarnwrap.util.collection.BoundedRegionArray chunks,yarnwrap.world.chunk.Chunk chunk, ) { return net.minecraft.world.chunk.ChunkGenerating.convertToFullChunk(context.wrapperContained,step.wrapperContained,chunks.wrapperContained,chunk.wrapperContained); }

}