package yarnwrap.world;
public class EntityLookupView { public net.minecraft.world.EntityLookupView wrapperContained; public EntityLookupView(net.minecraft.world.EntityLookupView wrapperContained) { this.wrapperContained = wrapperContained; }

public yarnwrap.server.world.ServerWorld toServerWorld() { return new yarnwrap.server.world.ServerWorld(wrapperContained.toServerWorld()); }
// public static yarnwrap.server.world.ServerWorld toServerWorld() { return new yarnwrap.server.world.ServerWorld(net.minecraft.world.EntityLookupView.toServerWorld()); }
// public boolean method_64386(yarnwrap.entity.LivingEntity entity) { return wrapperContained.method_64386(entity.wrapperContained); }
// public static boolean method_64386(yarnwrap.entity.LivingEntity entity, ) { return net.minecraft.world.EntityLookupView.method_64386(entity.wrapperContained); }
public yarnwrap.entity.player.PlayerEntity getClosestPlayer(yarnwrap.entity.ai.TargetPredicate targetPredicate,double x,double y,double z) { return new yarnwrap.entity.player.PlayerEntity(wrapperContained.getClosestPlayer(targetPredicate.wrapperContained,x,y,z)); }
// public static yarnwrap.entity.player.PlayerEntity getClosestPlayer(yarnwrap.entity.ai.TargetPredicate targetPredicate,double x,double y,double z, ) { return new yarnwrap.entity.player.PlayerEntity(net.minecraft.world.EntityLookupView.getClosestPlayer(targetPredicate.wrapperContained,x,y,z)); }
public yarnwrap.entity.player.PlayerEntity getClosestPlayer(yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity) { return new yarnwrap.entity.player.PlayerEntity(wrapperContained.getClosestPlayer(targetPredicate.wrapperContained,entity.wrapperContained)); }
// public static yarnwrap.entity.player.PlayerEntity getClosestPlayer(yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity, ) { return new yarnwrap.entity.player.PlayerEntity(net.minecraft.world.EntityLookupView.getClosestPlayer(targetPredicate.wrapperContained,entity.wrapperContained)); }
public yarnwrap.entity.player.PlayerEntity getClosestPlayer(yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,double x,double y,double z) { return new yarnwrap.entity.player.PlayerEntity(wrapperContained.getClosestPlayer(targetPredicate.wrapperContained,entity.wrapperContained,x,y,z)); }
// public static yarnwrap.entity.player.PlayerEntity getClosestPlayer(yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,double x,double y,double z, ) { return new yarnwrap.entity.player.PlayerEntity(net.minecraft.world.EntityLookupView.getClosestPlayer(targetPredicate.wrapperContained,entity.wrapperContained,x,y,z)); }
public java.util.List getPlayers(yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,yarnwrap.util.math.Box box) { return wrapperContained.getPlayers(targetPredicate.wrapperContained,entity.wrapperContained,box.wrapperContained); }
// public static java.util.List getPlayers(yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,yarnwrap.util.math.Box box, ) { return net.minecraft.world.EntityLookupView.getPlayers(targetPredicate.wrapperContained,entity.wrapperContained,box.wrapperContained); }
public yarnwrap.entity.LivingEntity getClosestEntity(java.lang.Class clazz,yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,double x,double y,double z,yarnwrap.util.math.Box box) { return new yarnwrap.entity.LivingEntity(wrapperContained.getClosestEntity(clazz,targetPredicate.wrapperContained,entity.wrapperContained,x,y,z,box.wrapperContained)); }
// public static yarnwrap.entity.LivingEntity getClosestEntity(java.lang.Class clazz,yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,double x,double y,double z,yarnwrap.util.math.Box box, ) { return new yarnwrap.entity.LivingEntity(net.minecraft.world.EntityLookupView.getClosestEntity(clazz,targetPredicate.wrapperContained,entity.wrapperContained,x,y,z,box.wrapperContained)); }
public java.util.List getTargets(java.lang.Class clazz,yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,yarnwrap.util.math.Box box) { return wrapperContained.getTargets(clazz,targetPredicate.wrapperContained,entity.wrapperContained,box.wrapperContained); }
// public static java.util.List getTargets(java.lang.Class clazz,yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,yarnwrap.util.math.Box box, ) { return net.minecraft.world.EntityLookupView.getTargets(clazz,targetPredicate.wrapperContained,entity.wrapperContained,box.wrapperContained); }
public yarnwrap.entity.LivingEntity getClosestEntity(java.util.List entities,yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,double x,double y,double z) { return new yarnwrap.entity.LivingEntity(wrapperContained.getClosestEntity(entities,targetPredicate.wrapperContained,entity.wrapperContained,x,y,z)); }
// public static yarnwrap.entity.LivingEntity getClosestEntity(java.util.List entities,yarnwrap.entity.ai.TargetPredicate targetPredicate,yarnwrap.entity.LivingEntity entity,double x,double y,double z, ) { return new yarnwrap.entity.LivingEntity(net.minecraft.world.EntityLookupView.getClosestEntity(entities,targetPredicate.wrapperContained,entity.wrapperContained,x,y,z)); }
// public boolean method_64394(yarnwrap.entity.LivingEntity potentialEntity) { return wrapperContained.method_64394(potentialEntity.wrapperContained); }
// public static boolean method_64394(yarnwrap.entity.LivingEntity potentialEntity, ) { return net.minecraft.world.EntityLookupView.method_64394(potentialEntity.wrapperContained); }

}