package yarnwrap.world;
public class WorldAccess { public net.minecraft.world.WorldAccess wrapperContained; public WorldAccess(net.minecraft.world.WorldAccess wrapperContained) { this.wrapperContained = wrapperContained; }

public void playSound(yarnwrap.entity.Entity source,yarnwrap.util.math.BlockPos pos,yarnwrap.sound.SoundEvent sound,yarnwrap.sound.SoundCategory category,float volume,float pitch) { wrapperContained.playSound(source.wrapperContained,pos.wrapperContained,sound.wrapperContained,category.wrapperContained,volume,pitch); }
// public static void playSound(yarnwrap.entity.Entity source,yarnwrap.util.math.BlockPos pos,yarnwrap.sound.SoundEvent sound,yarnwrap.sound.SoundCategory category,float volume,float pitch, ) { net.minecraft.world.WorldAccess.playSound(source.wrapperContained,pos.wrapperContained,sound.wrapperContained,category.wrapperContained,volume,pitch); }
public yarnwrap.world.chunk.ChunkManager getChunkManager() { return new yarnwrap.world.chunk.ChunkManager(wrapperContained.getChunkManager()); }
// public static yarnwrap.world.chunk.ChunkManager getChunkManager() { return new yarnwrap.world.chunk.ChunkManager(net.minecraft.world.WorldAccess.getChunkManager()); }
public yarnwrap.world.WorldProperties getLevelProperties() { return new yarnwrap.world.WorldProperties(wrapperContained.getLevelProperties()); }
// public static yarnwrap.world.WorldProperties getLevelProperties() { return new yarnwrap.world.WorldProperties(net.minecraft.world.WorldAccess.getLevelProperties()); }
public yarnwrap.world.LocalDifficulty getLocalDifficulty(yarnwrap.util.math.BlockPos pos) { return new yarnwrap.world.LocalDifficulty(wrapperContained.getLocalDifficulty(pos.wrapperContained)); }
// public static yarnwrap.world.LocalDifficulty getLocalDifficulty(yarnwrap.util.math.BlockPos pos, ) { return new yarnwrap.world.LocalDifficulty(net.minecraft.world.WorldAccess.getLocalDifficulty(pos.wrapperContained)); }
public void addParticleClient(yarnwrap.particle.ParticleEffect parameters,double x,double y,double z,double velocityX,double velocityY,double velocityZ) { wrapperContained.addParticleClient(parameters.wrapperContained,x,y,z,velocityX,velocityY,velocityZ); }
// public static void addParticleClient(yarnwrap.particle.ParticleEffect parameters,double x,double y,double z,double velocityX,double velocityY,double velocityZ, ) { net.minecraft.world.WorldAccess.addParticleClient(parameters.wrapperContained,x,y,z,velocityX,velocityY,velocityZ); }
public yarnwrap.world.Difficulty getDifficulty() { return new yarnwrap.world.Difficulty(wrapperContained.getDifficulty()); }
// public static yarnwrap.world.Difficulty getDifficulty() { return new yarnwrap.world.Difficulty(net.minecraft.world.WorldAccess.getDifficulty()); }
public void updateNeighbors(yarnwrap.util.math.BlockPos pos,yarnwrap.block.Block block) { wrapperContained.updateNeighbors(pos.wrapperContained,block.wrapperContained); }
// public static void updateNeighbors(yarnwrap.util.math.BlockPos pos,yarnwrap.block.Block block, ) { net.minecraft.world.WorldAccess.updateNeighbors(pos.wrapperContained,block.wrapperContained); }
public yarnwrap.util.math.random.Random getRandom() { return new yarnwrap.util.math.random.Random(wrapperContained.getRandom()); }
// public static yarnwrap.util.math.random.Random getRandom() { return new yarnwrap.util.math.random.Random(net.minecraft.world.WorldAccess.getRandom()); }
public void syncWorldEvent(yarnwrap.entity.Entity source,int eventId,yarnwrap.util.math.BlockPos pos,int data) { wrapperContained.syncWorldEvent(source.wrapperContained,eventId,pos.wrapperContained,data); }
// public static void syncWorldEvent(yarnwrap.entity.Entity source,int eventId,yarnwrap.util.math.BlockPos pos,int data, ) { net.minecraft.world.WorldAccess.syncWorldEvent(source.wrapperContained,eventId,pos.wrapperContained,data); }
public yarnwrap.server.MinecraftServer getServer() { return new yarnwrap.server.MinecraftServer(wrapperContained.getServer()); }
// public static yarnwrap.server.MinecraftServer getServer() { return new yarnwrap.server.MinecraftServer(net.minecraft.world.WorldAccess.getServer()); }
public void syncWorldEvent(int eventId,yarnwrap.util.math.BlockPos pos,int data) { wrapperContained.syncWorldEvent(eventId,pos.wrapperContained,data); }
// public static void syncWorldEvent(int eventId,yarnwrap.util.math.BlockPos pos,int data, ) { net.minecraft.world.WorldAccess.syncWorldEvent(eventId,pos.wrapperContained,data); }
// public void emitGameEvent(yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.Vec3d emitterPos,Object emitter) { wrapperContained.emitGameEvent(event.wrapperContained,emitterPos.wrapperContained,emitter); }
// public static void emitGameEvent(yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.Vec3d emitterPos,Object emitter, ) { net.minecraft.world.WorldAccess.emitGameEvent(event.wrapperContained,emitterPos.wrapperContained,emitter); }
public void emitGameEvent(yarnwrap.entity.Entity entity,yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.BlockPos pos) { wrapperContained.emitGameEvent(entity.wrapperContained,event.wrapperContained,pos.wrapperContained); }
// public static void emitGameEvent(yarnwrap.entity.Entity entity,yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.BlockPos pos, ) { net.minecraft.world.WorldAccess.emitGameEvent(entity.wrapperContained,event.wrapperContained,pos.wrapperContained); }
public long getTickOrder() { return wrapperContained.getTickOrder(); }
// public static long getTickOrder() { return net.minecraft.world.WorldAccess.getTickOrder(); }
public void replaceWithStateForNeighborUpdate(yarnwrap.util.math.Direction direction,yarnwrap.util.math.BlockPos pos,yarnwrap.util.math.BlockPos neighborPos,yarnwrap.block.BlockState neighborState,int flags,int maxUpdateDepth) { wrapperContained.replaceWithStateForNeighborUpdate(direction.wrapperContained,pos.wrapperContained,neighborPos.wrapperContained,neighborState.wrapperContained,flags,maxUpdateDepth); }
// public static void replaceWithStateForNeighborUpdate(yarnwrap.util.math.Direction direction,yarnwrap.util.math.BlockPos pos,yarnwrap.util.math.BlockPos neighborPos,yarnwrap.block.BlockState neighborState,int flags,int maxUpdateDepth, ) { net.minecraft.world.WorldAccess.replaceWithStateForNeighborUpdate(direction.wrapperContained,pos.wrapperContained,neighborPos.wrapperContained,neighborState.wrapperContained,flags,maxUpdateDepth); }
public void emitGameEvent(yarnwrap.entity.Entity entity,yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.Vec3d pos) { wrapperContained.emitGameEvent(entity.wrapperContained,event.wrapperContained,pos.wrapperContained); }
// public static void emitGameEvent(yarnwrap.entity.Entity entity,yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.Vec3d pos, ) { net.minecraft.world.WorldAccess.emitGameEvent(entity.wrapperContained,event.wrapperContained,pos.wrapperContained); }
// public void emitGameEvent(yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.BlockPos pos,Object emitter) { wrapperContained.emitGameEvent(event.wrapperContained,pos.wrapperContained,emitter); }
// public static void emitGameEvent(yarnwrap.registry.entry.RegistryEntry event,yarnwrap.util.math.BlockPos pos,Object emitter, ) { net.minecraft.world.WorldAccess.emitGameEvent(event.wrapperContained,pos.wrapperContained,emitter); }
public void playSound(yarnwrap.entity.Entity source,yarnwrap.util.math.BlockPos pos,yarnwrap.sound.SoundEvent sound,yarnwrap.sound.SoundCategory category) { wrapperContained.playSound(source.wrapperContained,pos.wrapperContained,sound.wrapperContained,category.wrapperContained); }
// public static void playSound(yarnwrap.entity.Entity source,yarnwrap.util.math.BlockPos pos,yarnwrap.sound.SoundEvent sound,yarnwrap.sound.SoundCategory category, ) { net.minecraft.world.WorldAccess.playSound(source.wrapperContained,pos.wrapperContained,sound.wrapperContained,category.wrapperContained); }
// public void emitGameEvent(yarnwrap.registry.RegistryKey event,yarnwrap.util.math.BlockPos pos,Object emitter) { wrapperContained.emitGameEvent(event.wrapperContained,pos.wrapperContained,emitter); }
// public static void emitGameEvent(yarnwrap.registry.RegistryKey event,yarnwrap.util.math.BlockPos pos,Object emitter, ) { net.minecraft.world.WorldAccess.emitGameEvent(event.wrapperContained,pos.wrapperContained,emitter); }

}