package yarnwrap.entity.ai.brain.task;
public class GoToSecondaryPositionTask { public net.minecraft.entity.ai.brain.task.GoToSecondaryPositionTask wrapperContained; public GoToSecondaryPositionTask(net.minecraft.entity.ai.brain.task.GoToSecondaryPositionTask wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.entity.ai.brain.task.TaskRunnable method_47159(Object walkTarget,int secondary,org.apache.commons.lang3.mutable.MutableLong primary) { return new yarnwrap.entity.ai.brain.task.TaskRunnable(wrapperContained.method_47159(walkTarget,secondary,primary)); }
// public static yarnwrap.entity.ai.brain.task.TaskRunnable method_47159(Object walkTarget,int secondary,org.apache.commons.lang3.mutable.MutableLong primary, ) { return new yarnwrap.entity.ai.brain.task.TaskRunnable(net.minecraft.entity.ai.brain.task.GoToSecondaryPositionTask.method_47159(walkTarget,secondary,primary)); }
// public boolean method_47160(Object world,yarnwrap.entity.ai.brain.MemoryQueryResult entity,yarnwrap.entity.ai.brain.MemoryQueryResult time) { return wrapperContained.method_47160(world,entity.wrapperContained,time.wrapperContained); }
// public static boolean method_47160(Object world,yarnwrap.entity.ai.brain.MemoryQueryResult entity,yarnwrap.entity.ai.brain.MemoryQueryResult time, ) { return net.minecraft.entity.ai.brain.task.GoToSecondaryPositionTask.method_47160(world,entity.wrapperContained,time.wrapperContained); }
// public yarnwrap.entity.ai.brain.task.Task create(yarnwrap.entity.ai.brain.MemoryModuleType secondaryPositions,float speed,int completionRange,int primaryPositionActivationDistance,yarnwrap.entity.ai.brain.MemoryModuleType primaryPosition) { return new yarnwrap.entity.ai.brain.task.Task(wrapperContained.create(secondaryPositions.wrapperContained,speed,completionRange,primaryPositionActivationDistance,primaryPosition.wrapperContained)); }
// public static yarnwrap.entity.ai.brain.task.Task create(yarnwrap.entity.ai.brain.MemoryModuleType secondaryPositions,float speed,int completionRange,int primaryPositionActivationDistance,yarnwrap.entity.ai.brain.MemoryModuleType primaryPosition, ) { return new yarnwrap.entity.ai.brain.task.Task(net.minecraft.entity.ai.brain.task.GoToSecondaryPositionTask.create(secondaryPositions.wrapperContained,speed,completionRange,primaryPositionActivationDistance,primaryPosition.wrapperContained)); }
// public com.mojang.datafixers.kinds.App method_47162(yarnwrap.entity.ai.brain.MemoryModuleType context) { return wrapperContained.method_47162(context.wrapperContained); }
// public static com.mojang.datafixers.kinds.App method_47162(yarnwrap.entity.ai.brain.MemoryModuleType context, ) { return net.minecraft.entity.ai.brain.task.GoToSecondaryPositionTask.method_47162(context.wrapperContained); }

}