package yarnwrap.structure.pool;
public class StructurePoolBasedGenerator { public net.minecraft.structure.pool.StructurePoolBasedGenerator wrapperContained; public StructurePoolBasedGenerator(net.minecraft.structure.pool.StructurePoolBasedGenerator wrapperContained) { this.wrapperContained = wrapperContained; }

// public org.slf4j.Logger LOGGER() { return wrapperContained.LOGGER; }
// public void generate(yarnwrap.world.gen.noise.NoiseConfig noiseConfig,int maxSize,boolean modifyBoundingBox,yarnwrap.world.gen.chunk.ChunkGenerator chunkGenerator,yarnwrap.structure.StructureTemplateManager structureTemplateManager,yarnwrap.world.HeightLimitView heightLimitView,yarnwrap.util.math.random.Random random,yarnwrap.registry.Registry structurePoolRegistry,yarnwrap.structure.PoolStructurePiece firstPiece,java.util.List pieces,yarnwrap.util.shape.VoxelShape pieceShape,yarnwrap.structure.pool.alias.StructurePoolAliasLookup aliasLookup,yarnwrap.structure.StructureLiquidSettings liquidSettings) { wrapperContained.generate(noiseConfig.wrapperContained,maxSize,modifyBoundingBox,chunkGenerator.wrapperContained,structureTemplateManager.wrapperContained,heightLimitView.wrapperContained,random.wrapperContained,structurePoolRegistry.wrapperContained,firstPiece.wrapperContained,pieces,pieceShape.wrapperContained,aliasLookup.wrapperContained,liquidSettings.wrapperContained); }
// public java.util.Optional generate(Object context,yarnwrap.registry.entry.RegistryEntry structurePool,java.util.Optional id,int size,yarnwrap.util.math.BlockPos pos,boolean useExpansionHack,java.util.Optional projectStartToHeightmap,int maxDistanceFromCenter,yarnwrap.structure.pool.alias.StructurePoolAliasLookup aliasLookup,yarnwrap.world.gen.structure.DimensionPadding dimensionPadding,yarnwrap.structure.StructureLiquidSettings liquidSettings) { return wrapperContained.generate(context,structurePool.wrapperContained,id,size,pos.wrapperContained,useExpansionHack,projectStartToHeightmap,maxDistanceFromCenter,aliasLookup.wrapperContained,dimensionPadding.wrapperContained,liquidSettings.wrapperContained); }
// public java.util.Optional findStartingJigsawPos(yarnwrap.structure.pool.StructurePoolElement pool,yarnwrap.util.Identifier id,yarnwrap.util.math.BlockPos pos,yarnwrap.util.BlockRotation rotation,yarnwrap.structure.StructureTemplateManager structureManager,yarnwrap.util.math.random.ChunkRandom random) { return wrapperContained.findStartingJigsawPos(pool.wrapperContained,id.wrapperContained,pos.wrapperContained,rotation.wrapperContained,structureManager.wrapperContained,random.wrapperContained); }
public boolean generate(yarnwrap.server.world.ServerWorld world,yarnwrap.registry.entry.RegistryEntry structurePool,yarnwrap.util.Identifier id,int size,yarnwrap.util.math.BlockPos pos,boolean keepJigsaws) { return wrapperContained.generate(world.wrapperContained,structurePool.wrapperContained,id.wrapperContained,size,pos.wrapperContained,keepJigsaws); }

}