package yarnwrap.item;
public class FilledMapItem { public net.minecraft.item.FilledMapItem wrapperContained; public FilledMapItem(net.minecraft.item.FilledMapItem wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.block.BlockState getFluidStateIfVisible(yarnwrap.world.World world,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos) { return new yarnwrap.block.BlockState(wrapperContained.getFluidStateIfVisible(world.wrapperContained,state.wrapperContained,pos.wrapperContained)); }
// public static yarnwrap.block.BlockState getFluidStateIfVisible(yarnwrap.world.World world,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos, ) { return new yarnwrap.block.BlockState(net.minecraft.item.FilledMapItem.getFluidStateIfVisible(world.wrapperContained,state.wrapperContained,pos.wrapperContained)); }
// public void scale(yarnwrap.item.ItemStack map,yarnwrap.server.world.ServerWorld world) { wrapperContained.scale(map.wrapperContained,world.wrapperContained); }
// public static void scale(yarnwrap.item.ItemStack map,yarnwrap.server.world.ServerWorld world, ) { net.minecraft.item.FilledMapItem.scale(map.wrapperContained,world.wrapperContained); }
// public yarnwrap.item.map.MapState getMapState(yarnwrap.component.type.MapIdComponent id,yarnwrap.world.World world) { return new yarnwrap.item.map.MapState(wrapperContained.getMapState(id.wrapperContained,world.wrapperContained)); }
// public static yarnwrap.item.map.MapState getMapState(yarnwrap.component.type.MapIdComponent id,yarnwrap.world.World world, ) { return new yarnwrap.item.map.MapState(net.minecraft.item.FilledMapItem.getMapState(id.wrapperContained,world.wrapperContained)); }
public void updateColors(yarnwrap.world.World world,yarnwrap.entity.Entity entity,yarnwrap.item.map.MapState state) { wrapperContained.updateColors(world.wrapperContained,entity.wrapperContained,state.wrapperContained); }
// public static void updateColors(yarnwrap.world.World world,yarnwrap.entity.Entity entity,yarnwrap.item.map.MapState state, ) { net.minecraft.item.FilledMapItem.updateColors(world.wrapperContained,entity.wrapperContained,state.wrapperContained); }
// public yarnwrap.item.map.MapState getMapState(yarnwrap.item.ItemStack map,yarnwrap.world.World world) { return new yarnwrap.item.map.MapState(wrapperContained.getMapState(map.wrapperContained,world.wrapperContained)); }
// public static yarnwrap.item.map.MapState getMapState(yarnwrap.item.ItemStack map,yarnwrap.world.World world, ) { return new yarnwrap.item.map.MapState(net.minecraft.item.FilledMapItem.getMapState(map.wrapperContained,world.wrapperContained)); }
// public void fillExplorationMap(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack map) { wrapperContained.fillExplorationMap(world.wrapperContained,map.wrapperContained); }
// public static void fillExplorationMap(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack map, ) { net.minecraft.item.FilledMapItem.fillExplorationMap(world.wrapperContained,map.wrapperContained); }
// public yarnwrap.item.ItemStack createMap(yarnwrap.server.world.ServerWorld world,int x,int z,byte scale,boolean showIcons,boolean unlimitedTracking) { return new yarnwrap.item.ItemStack(wrapperContained.createMap(world.wrapperContained,x,z,scale,showIcons,unlimitedTracking)); }
// public static yarnwrap.item.ItemStack createMap(yarnwrap.server.world.ServerWorld world,int x,int z,byte scale,boolean showIcons,boolean unlimitedTracking, ) { return new yarnwrap.item.ItemStack(net.minecraft.item.FilledMapItem.createMap(world.wrapperContained,x,z,scale,showIcons,unlimitedTracking)); }
// public void copyMap(yarnwrap.item.ItemStack stack,yarnwrap.server.world.ServerWorld world) { wrapperContained.copyMap(stack.wrapperContained,world.wrapperContained); }
// public static void copyMap(yarnwrap.item.ItemStack stack,yarnwrap.server.world.ServerWorld world, ) { net.minecraft.item.FilledMapItem.copyMap(stack.wrapperContained,world.wrapperContained); }
// public yarnwrap.component.type.MapIdComponent allocateMapId(yarnwrap.server.world.ServerWorld world,int x,int z,int scale,boolean showIcons,boolean unlimitedTracking,yarnwrap.registry.RegistryKey dimension) { return new yarnwrap.component.type.MapIdComponent(wrapperContained.allocateMapId(world.wrapperContained,x,z,scale,showIcons,unlimitedTracking,dimension.wrapperContained)); }
// public static yarnwrap.component.type.MapIdComponent allocateMapId(yarnwrap.server.world.ServerWorld world,int x,int z,int scale,boolean showIcons,boolean unlimitedTracking,yarnwrap.registry.RegistryKey dimension, ) { return new yarnwrap.component.type.MapIdComponent(net.minecraft.item.FilledMapItem.allocateMapId(world.wrapperContained,x,z,scale,showIcons,unlimitedTracking,dimension.wrapperContained)); }
// public boolean isAquaticBiome(boolean biomes,int x,int z) { return wrapperContained.isAquaticBiome(biomes,x,z); }
// public static boolean isAquaticBiome(boolean biomes,int x,int z, ) { return net.minecraft.item.FilledMapItem.isAquaticBiome(biomes,x,z); }

}