package yarnwrap.structure;
public class PostPlacementProcessor { public net.minecraft.structure.PostPlacementProcessor wrapperContained; public PostPlacementProcessor(net.minecraft.structure.PostPlacementProcessor wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.structure.PostPlacementProcessor EMPTY() { return new yarnwrap.structure.PostPlacementProcessor(wrapperContained.EMPTY); }
// public void EMPTY(yarnwrap.structure.PostPlacementProcessor value) { wrapperContained.EMPTY = value.wrapperContained; }
public static yarnwrap.structure.PostPlacementProcessor EMPTY() { return new yarnwrap.structure.PostPlacementProcessor(net.minecraft.structure.PostPlacementProcessor.EMPTY); }
// public static void EMPTY(yarnwrap.structure.PostPlacementProcessor value, ) { net.minecraft.structure.PostPlacementProcessor.EMPTY = value.wrapperContained; }

public void afterPlace(yarnwrap.world.StructureWorldAccess world,yarnwrap.world.gen.StructureAccessor structureAccessor,yarnwrap.world.gen.chunk.ChunkGenerator chunkGenerator,yarnwrap.util.math.random.Random random,yarnwrap.util.math.BlockBox chunkBox,yarnwrap.util.math.ChunkPos pos,yarnwrap.structure.StructurePiecesList children) { wrapperContained.afterPlace(world.wrapperContained,structureAccessor.wrapperContained,chunkGenerator.wrapperContained,random.wrapperContained,chunkBox.wrapperContained,pos.wrapperContained,children.wrapperContained); }
// public static void afterPlace(yarnwrap.world.StructureWorldAccess world,yarnwrap.world.gen.StructureAccessor structureAccessor,yarnwrap.world.gen.chunk.ChunkGenerator chunkGenerator,yarnwrap.util.math.random.Random random,yarnwrap.util.math.BlockBox chunkBox,yarnwrap.util.math.ChunkPos pos,yarnwrap.structure.StructurePiecesList children, ) { net.minecraft.structure.PostPlacementProcessor.afterPlace(world.wrapperContained,structureAccessor.wrapperContained,chunkGenerator.wrapperContained,random.wrapperContained,chunkBox.wrapperContained,pos.wrapperContained,children.wrapperContained); }
// public void method_38701(yarnwrap.world.StructureWorldAccess world,yarnwrap.world.gen.StructureAccessor structureAccessor,yarnwrap.world.gen.chunk.ChunkGenerator chunkGenerator,yarnwrap.util.math.random.Random random,yarnwrap.util.math.BlockBox chunkBox,yarnwrap.util.math.ChunkPos pos,yarnwrap.structure.StructurePiecesList children) { wrapperContained.method_38701(world.wrapperContained,structureAccessor.wrapperContained,chunkGenerator.wrapperContained,random.wrapperContained,chunkBox.wrapperContained,pos.wrapperContained,children.wrapperContained); }
// public static void method_38701(yarnwrap.world.StructureWorldAccess world,yarnwrap.world.gen.StructureAccessor structureAccessor,yarnwrap.world.gen.chunk.ChunkGenerator chunkGenerator,yarnwrap.util.math.random.Random random,yarnwrap.util.math.BlockBox chunkBox,yarnwrap.util.math.ChunkPos pos,yarnwrap.structure.StructurePiecesList children, ) { net.minecraft.structure.PostPlacementProcessor.method_38701(world.wrapperContained,structureAccessor.wrapperContained,chunkGenerator.wrapperContained,random.wrapperContained,chunkBox.wrapperContained,pos.wrapperContained,children.wrapperContained); }

}