package yarnwrap.structure;
public class RuinedPortalStructurePiece { public net.minecraft.structure.RuinedPortalStructurePiece wrapperContained; public RuinedPortalStructurePiece(net.minecraft.structure.RuinedPortalStructurePiece wrapperContained) { this.wrapperContained = wrapperContained; }

// public Object verticalPlacement() { return wrapperContained.verticalPlacement; }
// // public void verticalPlacement(Object value) { wrapperContained.verticalPlacement = value; }
// // public static Object verticalPlacement() { return net.minecraft.structure.RuinedPortalStructurePiece.verticalPlacement; }
// // public static void verticalPlacement(Object value, ) { net.minecraft.structure.RuinedPortalStructurePiece.verticalPlacement = value; }

// public Object properties() { return wrapperContained.properties; }
// // public void properties(Object value) { wrapperContained.properties = value; }
// // public static Object properties() { return net.minecraft.structure.RuinedPortalStructurePiece.properties; }
// // public static void properties(Object value, ) { net.minecraft.structure.RuinedPortalStructurePiece.properties = value; }

// public RuinedPortalStructurePiece(yarnwrap.structure.StructureTemplateManager manager,yarnwrap.util.math.BlockPos pos,Object verticalPlacement,Object properties,yarnwrap.util.Identifier id,yarnwrap.structure.StructureTemplate template,yarnwrap.util.BlockRotation rotation,yarnwrap.util.BlockMirror mirror) { this.wrapperContained = new net.minecraft.structure.RuinedPortalStructurePiece(manager.wrapperContained,pos.wrapperContained,verticalPlacement,properties,id.wrapperContained,template.wrapperContained,rotation.wrapperContained,mirror.wrapperContained); }
public RuinedPortalStructurePiece(yarnwrap.structure.StructureTemplateManager manager,yarnwrap.nbt.NbtCompound nbt) { this.wrapperContained = new net.minecraft.structure.RuinedPortalStructurePiece(manager.wrapperContained,nbt.wrapperContained); }
// public int getBaseHeight(yarnwrap.world.WorldAccess world,int x,int y,Object verticalPlacement) { return wrapperContained.getBaseHeight(world.wrapperContained,x,y,verticalPlacement); }
// public static int getBaseHeight(yarnwrap.world.WorldAccess world,int x,int y,Object verticalPlacement, ) { return net.minecraft.structure.RuinedPortalStructurePiece.getBaseHeight(world.wrapperContained,x,y,verticalPlacement); }
// public boolean canFillNetherrack(yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos) { return wrapperContained.canFillNetherrack(world.wrapperContained,pos.wrapperContained); }
// public static boolean canFillNetherrack(yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos, ) { return net.minecraft.structure.RuinedPortalStructurePiece.canFillNetherrack(world.wrapperContained,pos.wrapperContained); }
// public yarnwrap.structure.processor.StructureProcessorRule createReplacementRule(yarnwrap.block.Block old,float chance,yarnwrap.block.Block updated) { return new yarnwrap.structure.processor.StructureProcessorRule(wrapperContained.createReplacementRule(old.wrapperContained,chance,updated.wrapperContained)); }
// public static yarnwrap.structure.processor.StructureProcessorRule createReplacementRule(yarnwrap.block.Block old,float chance,yarnwrap.block.Block updated, ) { return new yarnwrap.structure.processor.StructureProcessorRule(net.minecraft.structure.RuinedPortalStructurePiece.createReplacementRule(old.wrapperContained,chance,updated.wrapperContained)); }
// public yarnwrap.structure.processor.StructureProcessorRule createReplacementRule(yarnwrap.block.Block old,yarnwrap.block.Block updated) { return new yarnwrap.structure.processor.StructureProcessorRule(wrapperContained.createReplacementRule(old.wrapperContained,updated.wrapperContained)); }
// public static yarnwrap.structure.processor.StructureProcessorRule createReplacementRule(yarnwrap.block.Block old,yarnwrap.block.Block updated, ) { return new yarnwrap.structure.processor.StructureProcessorRule(net.minecraft.structure.RuinedPortalStructurePiece.createReplacementRule(old.wrapperContained,updated.wrapperContained)); }
// public Object getHeightmapType(Object verticalPlacement) { return wrapperContained.getHeightmapType(verticalPlacement); }
// public static Object getHeightmapType(Object verticalPlacement, ) { return net.minecraft.structure.RuinedPortalStructurePiece.getHeightmapType(verticalPlacement); }
// public void updateNetherracksInBound(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world) { wrapperContained.updateNetherracksInBound(random.wrapperContained,world.wrapperContained); }
// public static void updateNetherracksInBound(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world, ) { net.minecraft.structure.RuinedPortalStructurePiece.updateNetherracksInBound(random.wrapperContained,world.wrapperContained); }
// public void generateVines(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos) { wrapperContained.generateVines(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public static void generateVines(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos, ) { net.minecraft.structure.RuinedPortalStructurePiece.generateVines(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public void placeNetherrackBase(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world) { wrapperContained.placeNetherrackBase(random.wrapperContained,world.wrapperContained); }
// public static void placeNetherrackBase(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world, ) { net.minecraft.structure.RuinedPortalStructurePiece.placeNetherrackBase(random.wrapperContained,world.wrapperContained); }
// public void generateOvergrownLeaves(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos) { wrapperContained.generateOvergrownLeaves(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public static void generateOvergrownLeaves(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos, ) { net.minecraft.structure.RuinedPortalStructurePiece.generateOvergrownLeaves(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public yarnwrap.structure.processor.StructureProcessorRule createLavaReplacementRule(Object verticalPlacement,Object properties) { return new yarnwrap.structure.processor.StructureProcessorRule(wrapperContained.createLavaReplacementRule(verticalPlacement,properties)); }
// public static yarnwrap.structure.processor.StructureProcessorRule createLavaReplacementRule(Object verticalPlacement,Object properties, ) { return new yarnwrap.structure.processor.StructureProcessorRule(net.minecraft.structure.RuinedPortalStructurePiece.createLavaReplacementRule(verticalPlacement,properties)); }
// public void updateNetherracks(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos) { wrapperContained.updateNetherracks(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public static void updateNetherracks(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos, ) { net.minecraft.structure.RuinedPortalStructurePiece.updateNetherracks(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public void placeNetherrackBottom(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos) { wrapperContained.placeNetherrackBottom(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public static void placeNetherrackBottom(yarnwrap.util.math.random.Random random,yarnwrap.world.WorldAccess world,yarnwrap.util.math.BlockPos pos, ) { net.minecraft.structure.RuinedPortalStructurePiece.placeNetherrackBottom(random.wrapperContained,world.wrapperContained,pos.wrapperContained); }
// public void method_27250(yarnwrap.util.math.random.Random pos) { wrapperContained.method_27250(pos.wrapperContained); }
// public static void method_27250(yarnwrap.util.math.random.Random pos, ) { net.minecraft.structure.RuinedPortalStructurePiece.method_27250(pos.wrapperContained); }
// public yarnwrap.structure.StructurePlacementData createPlacementData(yarnwrap.structure.StructureTemplateManager manager,yarnwrap.nbt.NbtCompound nbt,yarnwrap.util.Identifier id) { return new yarnwrap.structure.StructurePlacementData(wrapperContained.createPlacementData(manager.wrapperContained,nbt.wrapperContained,id.wrapperContained)); }
// public static yarnwrap.structure.StructurePlacementData createPlacementData(yarnwrap.structure.StructureTemplateManager manager,yarnwrap.nbt.NbtCompound nbt,yarnwrap.util.Identifier id, ) { return new yarnwrap.structure.StructurePlacementData(net.minecraft.structure.RuinedPortalStructurePiece.createPlacementData(manager.wrapperContained,nbt.wrapperContained,id.wrapperContained)); }
// public yarnwrap.structure.StructurePlacementData createPlacementData(yarnwrap.util.BlockMirror mirror,yarnwrap.util.BlockRotation rotation,Object verticalPlacement,yarnwrap.util.math.BlockPos pos,Object properties) { return new yarnwrap.structure.StructurePlacementData(wrapperContained.createPlacementData(mirror.wrapperContained,rotation.wrapperContained,verticalPlacement,pos.wrapperContained,properties)); }
// public static yarnwrap.structure.StructurePlacementData createPlacementData(yarnwrap.util.BlockMirror mirror,yarnwrap.util.BlockRotation rotation,Object verticalPlacement,yarnwrap.util.math.BlockPos pos,Object properties, ) { return new yarnwrap.structure.StructurePlacementData(net.minecraft.structure.RuinedPortalStructurePiece.createPlacementData(mirror.wrapperContained,rotation.wrapperContained,verticalPlacement,pos.wrapperContained,properties)); }
// public yarnwrap.structure.StructurePlacementData method_35451(yarnwrap.structure.StructureTemplateManager id) { return new yarnwrap.structure.StructurePlacementData(wrapperContained.method_35451(id.wrapperContained)); }
// public static yarnwrap.structure.StructurePlacementData method_35451(yarnwrap.structure.StructureTemplateManager id, ) { return new yarnwrap.structure.StructurePlacementData(net.minecraft.structure.RuinedPortalStructurePiece.method_35451(id.wrapperContained)); }

}