package yarnwrap.server.command;
public class FunctionCommand { public net.minecraft.server.command.FunctionCommand wrapperContained; public FunctionCommand(net.minecraft.server.command.FunctionCommand wrapperContained) { this.wrapperContained = wrapperContained; }

public com.mojang.brigadier.suggestion.SuggestionProvider SUGGESTION_PROVIDER() { return wrapperContained.SUGGESTION_PROVIDER; }
// public com.mojang.brigadier.exceptions.DynamicCommandExceptionType ARGUMENT_NOT_COMPOUND_EXCEPTION() { return wrapperContained.ARGUMENT_NOT_COMPOUND_EXCEPTION; }
// public com.mojang.brigadier.exceptions.DynamicCommandExceptionType NO_FUNCTIONS_EXCEPTION() { return wrapperContained.NO_FUNCTIONS_EXCEPTION; }
public com.mojang.brigadier.exceptions.Dynamic2CommandExceptionType INSTANTIATION_FAILURE_EXCEPTION() { return wrapperContained.INSTANTIATION_FAILURE_EXCEPTION; }
// public Object RESULT_REPORTER() { return wrapperContained.RESULT_REPORTER; }
public void register(com.mojang.brigadier.CommandDispatcher dispatcher) { wrapperContained.register(dispatcher); }
// public yarnwrap.nbt.NbtCompound getArgument(Object path,yarnwrap.command.DataCommandObject object) { return new yarnwrap.nbt.NbtCompound(wrapperContained.getArgument(path,object.wrapperContained)); }
public yarnwrap.server.command.ServerCommandSource createFunctionCommandSource(yarnwrap.server.command.ServerCommandSource source) { return new yarnwrap.server.command.ServerCommandSource(wrapperContained.createFunctionCommandSource(source.wrapperContained)); }
// public void enqueueAction(java.util.Collection commandFunctions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer,yarnwrap.command.ExecutionFlags flags) { wrapperContained.enqueueAction(commandFunctions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer,flags.wrapperContained); }
// public yarnwrap.command.ReturnValueConsumer wrapReturnValueConsumer(yarnwrap.server.command.AbstractServerCommandSource flags,Object resultConsumer,yarnwrap.util.Identifier id,yarnwrap.command.ReturnValueConsumer wrapped) { return new yarnwrap.command.ReturnValueConsumer(wrapperContained.wrapReturnValueConsumer(flags.wrapperContained,resultConsumer,id.wrapperContained,wrapped.wrapperContained)); }
// public void enqueueInReturnRun(java.util.Collection functions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer) { wrapperContained.enqueueInReturnRun(functions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer); }
// public void enqueueFunction(yarnwrap.nbt.NbtCompound args,yarnwrap.command.ExecutionControl control,com.mojang.brigadier.CommandDispatcher dispatcher,yarnwrap.server.command.AbstractServerCommandSource source,yarnwrap.server.function.CommandFunction function,yarnwrap.util.Identifier id,yarnwrap.command.ReturnValueConsumer returnValueConsumer,boolean propagateReturn) { wrapperContained.enqueueFunction(args.wrapperContained,control.wrapperContained,dispatcher,source.wrapperContained,function.wrapperContained,id.wrapperContained,returnValueConsumer.wrapperContained,propagateReturn); }
// public void enqueueOutsideReturnRun(java.util.Collection functions,yarnwrap.nbt.NbtCompound args,yarnwrap.server.command.AbstractServerCommandSource parentSource,yarnwrap.server.command.AbstractServerCommandSource functionSource,yarnwrap.command.ExecutionControl control,Object resultConsumer) { wrapperContained.enqueueOutsideReturnRun(functions,args.wrapperContained,parentSource.wrapperContained,functionSource.wrapperContained,control.wrapperContained,resultConsumer); }

}