package yarnwrap.server.command;
public class ItemCommand { public net.minecraft.server.command.ItemCommand wrapperContained; public ItemCommand(net.minecraft.server.command.ItemCommand wrapperContained) { this.wrapperContained = wrapperContained; }

// public com.mojang.brigadier.exceptions.Dynamic3CommandExceptionType NOT_A_CONTAINER_TARGET_EXCEPTION() { return wrapperContained.NOT_A_CONTAINER_TARGET_EXCEPTION; }
// public com.mojang.brigadier.exceptions.DynamicCommandExceptionType NO_SUCH_SLOT_TARGET_EXCEPTION() { return wrapperContained.NO_SUCH_SLOT_TARGET_EXCEPTION; }
// public com.mojang.brigadier.exceptions.Dynamic3CommandExceptionType NOT_A_CONTAINER_SOURCE_EXCEPTION() { return wrapperContained.NOT_A_CONTAINER_SOURCE_EXCEPTION; }
// public com.mojang.brigadier.exceptions.DynamicCommandExceptionType NO_SUCH_SLOT_SOURCE_EXCEPTION() { return wrapperContained.NO_SUCH_SLOT_SOURCE_EXCEPTION; }
// public com.mojang.brigadier.exceptions.DynamicCommandExceptionType NO_CHANGES_EXCEPTION() { return wrapperContained.NO_CHANGES_EXCEPTION; }
// public com.mojang.brigadier.exceptions.Dynamic2CommandExceptionType KNOWN_ITEM_EXCEPTION() { return wrapperContained.KNOWN_ITEM_EXCEPTION; }
// public com.mojang.brigadier.suggestion.SuggestionProvider MODIFIER_SUGGESTION_PROVIDER() { return wrapperContained.MODIFIER_SUGGESTION_PROVIDER; }
// public yarnwrap.item.ItemStack getStackInSlot(yarnwrap.entity.Entity entity,int slotId) { return new yarnwrap.item.ItemStack(wrapperContained.getStackInSlot(entity.wrapperContained,slotId)); }
public void register(com.mojang.brigadier.CommandDispatcher dispatcher,yarnwrap.command.CommandRegistryAccess commandRegistryAccess) { wrapperContained.register(dispatcher,commandRegistryAccess.wrapperContained); }
// public int executeBlockCopyEntity(yarnwrap.server.command.ServerCommandSource source,yarnwrap.entity.Entity sourceEntity,int sourceSlot,yarnwrap.util.math.BlockPos pos,int slot) { return wrapperContained.executeBlockCopyEntity(source.wrapperContained,sourceEntity.wrapperContained,sourceSlot,pos.wrapperContained,slot); }
// public int executeBlockCopyEntity(yarnwrap.server.command.ServerCommandSource source,yarnwrap.entity.Entity sourceEntity,int sourceSlot,yarnwrap.util.math.BlockPos pos,int slot,yarnwrap.registry.entry.RegistryEntry lootFunction) { return wrapperContained.executeBlockCopyEntity(source.wrapperContained,sourceEntity.wrapperContained,sourceSlot,pos.wrapperContained,slot,lootFunction.wrapperContained); }
// public int executeEntityCopyEntity(yarnwrap.server.command.ServerCommandSource source,yarnwrap.entity.Entity sourceEntity,int sourceSlot,java.util.Collection targets,int slot) { return wrapperContained.executeEntityCopyEntity(source.wrapperContained,sourceEntity.wrapperContained,sourceSlot,targets,slot); }
// public int executeEntityCopyEntity(yarnwrap.server.command.ServerCommandSource source,yarnwrap.entity.Entity sourceEntity,int sourceSlot,java.util.Collection targets,int slot,yarnwrap.registry.entry.RegistryEntry lootFunction) { return wrapperContained.executeEntityCopyEntity(source.wrapperContained,sourceEntity.wrapperContained,sourceSlot,targets,slot,lootFunction.wrapperContained); }
// public yarnwrap.item.ItemStack getStackWithModifier(yarnwrap.server.command.ServerCommandSource source,yarnwrap.registry.entry.RegistryEntry lootFunction,yarnwrap.item.ItemStack stack) { return new yarnwrap.item.ItemStack(wrapperContained.getStackWithModifier(source.wrapperContained,lootFunction.wrapperContained,stack.wrapperContained)); }
// public yarnwrap.item.ItemStack getStackInSlotFromInventoryAt(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos pos,int slotId) { return new yarnwrap.item.ItemStack(wrapperContained.getStackInSlotFromInventoryAt(source.wrapperContained,pos.wrapperContained,slotId)); }
// public int executeBlockReplace(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos pos,int slot,yarnwrap.item.ItemStack stack) { return wrapperContained.executeBlockReplace(source.wrapperContained,pos.wrapperContained,slot,stack.wrapperContained); }
// public int executeBlockModify(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos pos,int slot,yarnwrap.registry.entry.RegistryEntry lootFunction) { return wrapperContained.executeBlockModify(source.wrapperContained,pos.wrapperContained,slot,lootFunction.wrapperContained); }
// public int executeBlockCopyBlock(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos sourcePos,int sourceSlot,yarnwrap.util.math.BlockPos pos,int slot) { return wrapperContained.executeBlockCopyBlock(source.wrapperContained,sourcePos.wrapperContained,sourceSlot,pos.wrapperContained,slot); }
// public int executeBlockCopyBlock(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos sourcePos,int sourceSlot,yarnwrap.util.math.BlockPos pos,int slot,yarnwrap.registry.entry.RegistryEntry lootFunction) { return wrapperContained.executeBlockCopyBlock(source.wrapperContained,sourcePos.wrapperContained,sourceSlot,pos.wrapperContained,slot,lootFunction.wrapperContained); }
// public int executeEntityCopyBlock(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos sourcePos,int sourceSlot,java.util.Collection targets,int slot) { return wrapperContained.executeEntityCopyBlock(source.wrapperContained,sourcePos.wrapperContained,sourceSlot,targets,slot); }
// public int executeEntityCopyBlock(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos sourcePos,int sourceSlot,java.util.Collection targets,int slot,yarnwrap.registry.entry.RegistryEntry lootFunction) { return wrapperContained.executeEntityCopyBlock(source.wrapperContained,sourcePos.wrapperContained,sourceSlot,targets,slot,lootFunction.wrapperContained); }
// public yarnwrap.inventory.Inventory getInventoryAtPos(yarnwrap.server.command.ServerCommandSource source,yarnwrap.util.math.BlockPos pos,com.mojang.brigadier.exceptions.Dynamic3CommandExceptionType exception) { return new yarnwrap.inventory.Inventory(wrapperContained.getInventoryAtPos(source.wrapperContained,pos.wrapperContained,exception)); }
// public int executeEntityReplace(yarnwrap.server.command.ServerCommandSource source,java.util.Collection targets,int slot,yarnwrap.item.ItemStack stack) { return wrapperContained.executeEntityReplace(source.wrapperContained,targets,slot,stack.wrapperContained); }
// public int executeEntityModify(yarnwrap.server.command.ServerCommandSource source,java.util.Collection targets,int slot,yarnwrap.registry.entry.RegistryEntry lootFunction) { return wrapperContained.executeEntityModify(source.wrapperContained,targets,slot,lootFunction.wrapperContained); }

}