package yarnwrap.client.item;
public class ModelPredicateProviderRegistry { public net.minecraft.client.item.ModelPredicateProviderRegistry wrapperContained; public ModelPredicateProviderRegistry(net.minecraft.client.item.ModelPredicateProviderRegistry wrapperContained) { this.wrapperContained = wrapperContained; }

// public java.util.Map GLOBAL() { return wrapperContained.GLOBAL; }
// public void GLOBAL(java.util.Map value) { wrapperContained.GLOBAL = value; }
// public static java.util.Map GLOBAL() { return net.minecraft.client.item.ModelPredicateProviderRegistry.GLOBAL; }
// public static void GLOBAL(java.util.Map value, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.GLOBAL = value; }

// public yarnwrap.util.Identifier DAMAGED_ID() { return new yarnwrap.util.Identifier(wrapperContained.DAMAGED_ID); }
// public void DAMAGED_ID(yarnwrap.util.Identifier value) { wrapperContained.DAMAGED_ID = value.wrapperContained; }
// public static yarnwrap.util.Identifier DAMAGED_ID() { return new yarnwrap.util.Identifier(net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGED_ID); }
// public static void DAMAGED_ID(yarnwrap.util.Identifier value, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGED_ID = value.wrapperContained; }

// public yarnwrap.util.Identifier DAMAGE_ID() { return new yarnwrap.util.Identifier(wrapperContained.DAMAGE_ID); }
// public void DAMAGE_ID(yarnwrap.util.Identifier value) { wrapperContained.DAMAGE_ID = value.wrapperContained; }
// public static yarnwrap.util.Identifier DAMAGE_ID() { return new yarnwrap.util.Identifier(net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGE_ID); }
// public static void DAMAGE_ID(yarnwrap.util.Identifier value, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGE_ID = value.wrapperContained; }

// public yarnwrap.client.item.ClampedModelPredicateProvider DAMAGED_PROVIDER() { return new yarnwrap.client.item.ClampedModelPredicateProvider(wrapperContained.DAMAGED_PROVIDER); }
// public void DAMAGED_PROVIDER(yarnwrap.client.item.ClampedModelPredicateProvider value) { wrapperContained.DAMAGED_PROVIDER = value.wrapperContained; }
// public static yarnwrap.client.item.ClampedModelPredicateProvider DAMAGED_PROVIDER() { return new yarnwrap.client.item.ClampedModelPredicateProvider(net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGED_PROVIDER); }
// public static void DAMAGED_PROVIDER(yarnwrap.client.item.ClampedModelPredicateProvider value, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGED_PROVIDER = value.wrapperContained; }

// public yarnwrap.client.item.ClampedModelPredicateProvider DAMAGE_PROVIDER() { return new yarnwrap.client.item.ClampedModelPredicateProvider(wrapperContained.DAMAGE_PROVIDER); }
// public void DAMAGE_PROVIDER(yarnwrap.client.item.ClampedModelPredicateProvider value) { wrapperContained.DAMAGE_PROVIDER = value.wrapperContained; }
// public static yarnwrap.client.item.ClampedModelPredicateProvider DAMAGE_PROVIDER() { return new yarnwrap.client.item.ClampedModelPredicateProvider(net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGE_PROVIDER); }
// public static void DAMAGE_PROVIDER(yarnwrap.client.item.ClampedModelPredicateProvider value, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.DAMAGE_PROVIDER = value.wrapperContained; }

// public java.util.Map ITEM_SPECIFIC() { return wrapperContained.ITEM_SPECIFIC; }
// public void ITEM_SPECIFIC(java.util.Map value) { wrapperContained.ITEM_SPECIFIC = value; }
// public static java.util.Map ITEM_SPECIFIC() { return net.minecraft.client.item.ModelPredicateProviderRegistry.ITEM_SPECIFIC; }
// public static void ITEM_SPECIFIC(java.util.Map value, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.ITEM_SPECIFIC = value; }

// public java.util.Map method_27877(yarnwrap.item.Item key) { return wrapperContained.method_27877(key.wrapperContained); }
// public static java.util.Map method_27877(yarnwrap.item.Item key, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27877(key.wrapperContained); }
// public yarnwrap.client.item.ModelPredicateProvider get(yarnwrap.item.ItemStack stack,yarnwrap.util.Identifier id) { return new yarnwrap.client.item.ModelPredicateProvider(wrapperContained.get(stack.wrapperContained,id.wrapperContained)); }
// public static yarnwrap.client.item.ModelPredicateProvider get(yarnwrap.item.ItemStack stack,yarnwrap.util.Identifier id, ) { return new yarnwrap.client.item.ModelPredicateProvider(net.minecraft.client.item.ModelPredicateProviderRegistry.get(stack.wrapperContained,id.wrapperContained)); }
// public void register(yarnwrap.item.Item item,yarnwrap.util.Identifier id,yarnwrap.client.item.ClampedModelPredicateProvider provider) { wrapperContained.register(item.wrapperContained,id.wrapperContained,provider.wrapperContained); }
// public static void register(yarnwrap.item.Item item,yarnwrap.util.Identifier id,yarnwrap.client.item.ClampedModelPredicateProvider provider, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.register(item.wrapperContained,id.wrapperContained,provider.wrapperContained); }
// public float method_27880(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27880(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27880(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27880(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public yarnwrap.client.item.ClampedModelPredicateProvider register(yarnwrap.util.Identifier id,yarnwrap.client.item.ClampedModelPredicateProvider provider) { return new yarnwrap.client.item.ClampedModelPredicateProvider(wrapperContained.register(id.wrapperContained,provider.wrapperContained)); }
// public static yarnwrap.client.item.ClampedModelPredicateProvider register(yarnwrap.util.Identifier id,yarnwrap.client.item.ClampedModelPredicateProvider provider, ) { return new yarnwrap.client.item.ClampedModelPredicateProvider(net.minecraft.client.item.ModelPredicateProviderRegistry.register(id.wrapperContained,provider.wrapperContained)); }
// public float method_27882(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27882(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27882(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27882(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27883(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27883(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27883(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27883(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27884(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27884(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27884(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27884(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27885(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27885(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27885(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27885(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27886(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27886(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27886(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27886(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27887(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27887(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27887(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27887(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27888(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27888(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27888(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27888(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27889(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27889(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27889(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27889(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27890(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27890(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27890(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27890(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27891(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27891(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27891(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27891(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27892(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27892(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27892(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27892(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27893(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27893(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27893(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27893(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27894(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27894(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27894(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27894(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_27895(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_27895(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_27895(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_27895(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_32202(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_32202(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_32202(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_32202(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_35803(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_35803(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_35803(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_35803(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public void registerCustomModelData(yarnwrap.client.item.ModelPredicateProvider provider) { wrapperContained.registerCustomModelData(provider.wrapperContained); }
// public static void registerCustomModelData(yarnwrap.client.item.ModelPredicateProvider provider, ) { net.minecraft.client.item.ModelPredicateProviderRegistry.registerCustomModelData(provider.wrapperContained); }
// public yarnwrap.util.math.GlobalPos method_43219(yarnwrap.client.world.ClientWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity entity) { return new yarnwrap.util.math.GlobalPos(wrapperContained.method_43219(world.wrapperContained,stack.wrapperContained,entity.wrapperContained)); }
// public static yarnwrap.util.math.GlobalPos method_43219(yarnwrap.client.world.ClientWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity entity, ) { return new yarnwrap.util.math.GlobalPos(net.minecraft.client.item.ModelPredicateProviderRegistry.method_43219(world.wrapperContained,stack.wrapperContained,entity.wrapperContained)); }
// public yarnwrap.util.math.GlobalPos method_43220(yarnwrap.client.world.ClientWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity entity) { return new yarnwrap.util.math.GlobalPos(wrapperContained.method_43220(world.wrapperContained,stack.wrapperContained,entity.wrapperContained)); }
// public static yarnwrap.util.math.GlobalPos method_43220(yarnwrap.client.world.ClientWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity entity, ) { return new yarnwrap.util.math.GlobalPos(net.minecraft.client.item.ModelPredicateProviderRegistry.method_43220(world.wrapperContained,stack.wrapperContained,entity.wrapperContained)); }
// public float method_43611(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_43611(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_43611(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_43611(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_48484(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_48484(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_48484(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_48484(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public float method_49351(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed) { return wrapperContained.method_49351(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }
// public static float method_49351(yarnwrap.item.ItemStack stack,yarnwrap.client.world.ClientWorld world,yarnwrap.entity.LivingEntity entity,int seed, ) { return net.minecraft.client.item.ModelPredicateProviderRegistry.method_49351(stack.wrapperContained,world.wrapperContained,entity.wrapperContained,seed); }

}