package yarnwrap.block.cauldron;
public class CauldronBehavior { public net.minecraft.block.cauldron.CauldronBehavior wrapperContained; public CauldronBehavior(net.minecraft.block.cauldron.CauldronBehavior wrapperContained) { this.wrapperContained = wrapperContained; }

// public Object EMPTY_CAULDRON_BEHAVIOR() { return wrapperContained.EMPTY_CAULDRON_BEHAVIOR; }
// // public void EMPTY_CAULDRON_BEHAVIOR(Object value) { wrapperContained.EMPTY_CAULDRON_BEHAVIOR = value; }
// public static Object EMPTY_CAULDRON_BEHAVIOR() { return net.minecraft.block.cauldron.CauldronBehavior.EMPTY_CAULDRON_BEHAVIOR; }
// // public static void EMPTY_CAULDRON_BEHAVIOR(Object value, ) { net.minecraft.block.cauldron.CauldronBehavior.EMPTY_CAULDRON_BEHAVIOR = value; }

// public Object WATER_CAULDRON_BEHAVIOR() { return wrapperContained.WATER_CAULDRON_BEHAVIOR; }
// // public void WATER_CAULDRON_BEHAVIOR(Object value) { wrapperContained.WATER_CAULDRON_BEHAVIOR = value; }
// public static Object WATER_CAULDRON_BEHAVIOR() { return net.minecraft.block.cauldron.CauldronBehavior.WATER_CAULDRON_BEHAVIOR; }
// // public static void WATER_CAULDRON_BEHAVIOR(Object value, ) { net.minecraft.block.cauldron.CauldronBehavior.WATER_CAULDRON_BEHAVIOR = value; }

// public Object LAVA_CAULDRON_BEHAVIOR() { return wrapperContained.LAVA_CAULDRON_BEHAVIOR; }
// // public void LAVA_CAULDRON_BEHAVIOR(Object value) { wrapperContained.LAVA_CAULDRON_BEHAVIOR = value; }
// public static Object LAVA_CAULDRON_BEHAVIOR() { return net.minecraft.block.cauldron.CauldronBehavior.LAVA_CAULDRON_BEHAVIOR; }
// // public static void LAVA_CAULDRON_BEHAVIOR(Object value, ) { net.minecraft.block.cauldron.CauldronBehavior.LAVA_CAULDRON_BEHAVIOR = value; }

// public Object POWDER_SNOW_CAULDRON_BEHAVIOR() { return wrapperContained.POWDER_SNOW_CAULDRON_BEHAVIOR; }
// // public void POWDER_SNOW_CAULDRON_BEHAVIOR(Object value) { wrapperContained.POWDER_SNOW_CAULDRON_BEHAVIOR = value; }
// public static Object POWDER_SNOW_CAULDRON_BEHAVIOR() { return net.minecraft.block.cauldron.CauldronBehavior.POWDER_SNOW_CAULDRON_BEHAVIOR; }
// // public static void POWDER_SNOW_CAULDRON_BEHAVIOR(Object value, ) { net.minecraft.block.cauldron.CauldronBehavior.POWDER_SNOW_CAULDRON_BEHAVIOR = value; }

// public java.util.Map BEHAVIOR_MAPS() { return wrapperContained.BEHAVIOR_MAPS; }
// public void BEHAVIOR_MAPS(java.util.Map value) { wrapperContained.BEHAVIOR_MAPS = value; }
public static java.util.Map BEHAVIOR_MAPS() { return net.minecraft.block.cauldron.CauldronBehavior.BEHAVIOR_MAPS; }
// public static void BEHAVIOR_MAPS(java.util.Map value, ) { net.minecraft.block.cauldron.CauldronBehavior.BEHAVIOR_MAPS = value; }

// public com.mojang.serialization.Codec CODEC() { return wrapperContained.CODEC; }
// public void CODEC(com.mojang.serialization.Codec value) { wrapperContained.CODEC = value; }
public static com.mojang.serialization.Codec CODEC() { return net.minecraft.block.cauldron.CauldronBehavior.CODEC; }
// public static void CODEC(com.mojang.serialization.Codec value, ) { net.minecraft.block.cauldron.CauldronBehavior.CODEC = value; }

public yarnwrap.util.ActionResult interact(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.interact(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult interact(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.interact(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public Object createMap(java.lang.String name) { return wrapperContained.createMap(name); }
// public static Object createMap(java.lang.String name, ) { return net.minecraft.block.cauldron.CauldronBehavior.createMap(name); }
// public yarnwrap.util.ActionResult fillCauldron(yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack,yarnwrap.block.BlockState state,yarnwrap.sound.SoundEvent soundEvent) { return new yarnwrap.util.ActionResult(wrapperContained.fillCauldron(world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained,state.wrapperContained,soundEvent.wrapperContained)); }
// public static yarnwrap.util.ActionResult fillCauldron(yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack,yarnwrap.block.BlockState state,yarnwrap.sound.SoundEvent soundEvent, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.fillCauldron(world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained,state.wrapperContained,soundEvent.wrapperContained)); }
// public boolean method_32208(yarnwrap.block.BlockState statex) { return wrapperContained.method_32208(statex.wrapperContained); }
// public static boolean method_32208(yarnwrap.block.BlockState statex, ) { return net.minecraft.block.cauldron.CauldronBehavior.method_32208(statex.wrapperContained); }
// public yarnwrap.util.ActionResult emptyCauldron(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack,yarnwrap.item.ItemStack output,java.util.function.Predicate fullPredicate,yarnwrap.sound.SoundEvent soundEvent) { return new yarnwrap.util.ActionResult(wrapperContained.emptyCauldron(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained,output.wrapperContained,fullPredicate,soundEvent.wrapperContained)); }
// public static yarnwrap.util.ActionResult emptyCauldron(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack,yarnwrap.item.ItemStack output,java.util.function.Predicate fullPredicate,yarnwrap.sound.SoundEvent soundEvent, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.emptyCauldron(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained,output.wrapperContained,fullPredicate,soundEvent.wrapperContained)); }
// public void registerBehavior() { wrapperContained.registerBehavior(); }
public static void registerBehavior() { net.minecraft.block.cauldron.CauldronBehavior.registerBehavior(); }
// public boolean method_32213(yarnwrap.block.BlockState statex) { return wrapperContained.method_32213(statex.wrapperContained); }
// public static boolean method_32213(yarnwrap.block.BlockState statex, ) { return net.minecraft.block.cauldron.CauldronBehavior.method_32213(statex.wrapperContained); }
// public yarnwrap.util.ActionResult method_32218(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.method_32218(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult method_32218(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.method_32218(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public yarnwrap.util.ActionResult method_32219(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.method_32219(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult method_32219(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.method_32219(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public yarnwrap.util.ActionResult method_32220(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.method_32220(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult method_32220(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.method_32220(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public yarnwrap.util.ActionResult method_32221(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.method_32221(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult method_32221(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.method_32221(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public yarnwrap.util.ActionResult method_32222(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.method_32222(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult method_32222(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.method_32222(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public yarnwrap.util.ActionResult method_32223(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.method_32223(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult method_32223(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.method_32223(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public boolean method_32696(yarnwrap.block.BlockState statex) { return wrapperContained.method_32696(statex.wrapperContained); }
// public static boolean method_32696(yarnwrap.block.BlockState statex, ) { return net.minecraft.block.cauldron.CauldronBehavior.method_32696(statex.wrapperContained); }
// public yarnwrap.util.ActionResult method_32698(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.method_32698(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult method_32698(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.method_32698(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public void registerBucketBehavior(java.util.Map behavior) { wrapperContained.registerBucketBehavior(behavior); }
// public static void registerBucketBehavior(java.util.Map behavior, ) { net.minecraft.block.cauldron.CauldronBehavior.registerBucketBehavior(behavior); }
// // public boolean isUnderwater(yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos) { return wrapperContained.isUnderwater(world.wrapperContained,pos.wrapperContained); }
// public static boolean isUnderwater(yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos, ) { return net.minecraft.block.cauldron.CauldronBehavior.isUnderwater(world.wrapperContained,pos.wrapperContained); }
// // public yarnwrap.util.ActionResult tryFillWithWater(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.tryFillWithWater(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult tryFillWithWater(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.tryFillWithWater(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// // public yarnwrap.util.ActionResult tryFillWithLava(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.tryFillWithLava(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult tryFillWithLava(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.tryFillWithLava(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// // public yarnwrap.util.ActionResult tryFillWithPowderSnow(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.tryFillWithPowderSnow(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult tryFillWithPowderSnow(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.tryFillWithPowderSnow(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// // public yarnwrap.util.ActionResult cleanShulkerBox(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.cleanShulkerBox(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult cleanShulkerBox(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.cleanShulkerBox(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// // public yarnwrap.util.ActionResult cleanBanner(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.cleanBanner(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult cleanBanner(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.cleanBanner(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// // public yarnwrap.util.ActionResult cleanArmor(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack) { return new yarnwrap.util.ActionResult(wrapperContained.cleanArmor(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }
// public static yarnwrap.util.ActionResult cleanArmor(yarnwrap.block.BlockState state,yarnwrap.world.World world,yarnwrap.util.math.BlockPos pos,yarnwrap.entity.player.PlayerEntity player,yarnwrap.util.Hand hand,yarnwrap.item.ItemStack stack, ) { return new yarnwrap.util.ActionResult(net.minecraft.block.cauldron.CauldronBehavior.cleanArmor(state.wrapperContained,world.wrapperContained,pos.wrapperContained,player.wrapperContained,hand.wrapperContained,stack.wrapperContained)); }

}