package yarnwrap.client.render.entity.model;
public class ArmPosing { public net.minecraft.client.render.entity.model.ArmPosing wrapperContained; public ArmPosing(net.minecraft.client.render.entity.model.ArmPosing wrapperContained) { this.wrapperContained = wrapperContained; }

// public void charge(yarnwrap.client.model.ModelPart holdingArm,yarnwrap.client.model.ModelPart pullingArm,float crossbowPullTime,int itemUseTime,boolean rightArm) { wrapperContained.charge(holdingArm.wrapperContained,pullingArm.wrapperContained,crossbowPullTime,itemUseTime,rightArm); }
// public static void charge(yarnwrap.client.model.ModelPart holdingArm,yarnwrap.client.model.ModelPart pullingArm,float crossbowPullTime,int itemUseTime,boolean rightArm, ) { net.minecraft.client.render.entity.model.ArmPosing.charge(holdingArm.wrapperContained,pullingArm.wrapperContained,crossbowPullTime,itemUseTime,rightArm); }
// public void hold(yarnwrap.client.model.ModelPart holdingArm,yarnwrap.client.model.ModelPart otherArm,yarnwrap.client.model.ModelPart head,boolean rightArm) { wrapperContained.hold(holdingArm.wrapperContained,otherArm.wrapperContained,head.wrapperContained,rightArm); }
// public static void hold(yarnwrap.client.model.ModelPart holdingArm,yarnwrap.client.model.ModelPart otherArm,yarnwrap.client.model.ModelPart head,boolean rightArm, ) { net.minecraft.client.render.entity.model.ArmPosing.hold(holdingArm.wrapperContained,otherArm.wrapperContained,head.wrapperContained,rightArm); }
// public void swingArm(yarnwrap.client.model.ModelPart arm,float animationProgress,float sigma) { wrapperContained.swingArm(arm.wrapperContained,animationProgress,sigma); }
// public static void swingArm(yarnwrap.client.model.ModelPart arm,float animationProgress,float sigma, ) { net.minecraft.client.render.entity.model.ArmPosing.swingArm(arm.wrapperContained,animationProgress,sigma); }
// public void meleeAttack(yarnwrap.client.model.ModelPart rightArm,yarnwrap.client.model.ModelPart leftArm,yarnwrap.util.Arm mainArm,float swingProgress,float animationProgress) { wrapperContained.meleeAttack(rightArm.wrapperContained,leftArm.wrapperContained,mainArm.wrapperContained,swingProgress,animationProgress); }
// public static void meleeAttack(yarnwrap.client.model.ModelPart rightArm,yarnwrap.client.model.ModelPart leftArm,yarnwrap.util.Arm mainArm,float swingProgress,float animationProgress, ) { net.minecraft.client.render.entity.model.ArmPosing.meleeAttack(rightArm.wrapperContained,leftArm.wrapperContained,mainArm.wrapperContained,swingProgress,animationProgress); }
// public void zombieArms(yarnwrap.client.model.ModelPart leftArm,yarnwrap.client.model.ModelPart rightArm,boolean attacking,float swingProgress,float animationProgress) { wrapperContained.zombieArms(leftArm.wrapperContained,rightArm.wrapperContained,attacking,swingProgress,animationProgress); }
// public static void zombieArms(yarnwrap.client.model.ModelPart leftArm,yarnwrap.client.model.ModelPart rightArm,boolean attacking,float swingProgress,float animationProgress, ) { net.minecraft.client.render.entity.model.ArmPosing.zombieArms(leftArm.wrapperContained,rightArm.wrapperContained,attacking,swingProgress,animationProgress); }
// public void swingArms(yarnwrap.client.model.ModelPart rightArm,yarnwrap.client.model.ModelPart leftArm,float animationProgress) { wrapperContained.swingArms(rightArm.wrapperContained,leftArm.wrapperContained,animationProgress); }
// public static void swingArms(yarnwrap.client.model.ModelPart rightArm,yarnwrap.client.model.ModelPart leftArm,float animationProgress, ) { net.minecraft.client.render.entity.model.ArmPosing.swingArms(rightArm.wrapperContained,leftArm.wrapperContained,animationProgress); }

}