package yarnwrap.entity.projectile;
public class ProjectileUtil { public net.minecraft.entity.projectile.ProjectileUtil wrapperContained; public ProjectileUtil(net.minecraft.entity.projectile.ProjectileUtil wrapperContained) { this.wrapperContained = wrapperContained; }

// public float DEFAULT_MARGIN() { return wrapperContained.DEFAULT_MARGIN; }
// public void DEFAULT_MARGIN(float value) { wrapperContained.DEFAULT_MARGIN = value; }
// public static float DEFAULT_MARGIN() { return net.minecraft.entity.projectile.ProjectileUtil.DEFAULT_MARGIN; }
// public static void DEFAULT_MARGIN(float value, ) { net.minecraft.entity.projectile.ProjectileUtil.DEFAULT_MARGIN = value; }

// public void setRotationFromVelocity(yarnwrap.entity.Entity entity,float tickProgress) { wrapperContained.setRotationFromVelocity(entity.wrapperContained,tickProgress); }
// public static void setRotationFromVelocity(yarnwrap.entity.Entity entity,float tickProgress, ) { net.minecraft.entity.projectile.ProjectileUtil.setRotationFromVelocity(entity.wrapperContained,tickProgress); }
// public yarnwrap.util.hit.HitResult getCollision(yarnwrap.util.math.Vec3d pos,yarnwrap.entity.Entity entity,java.util.function.Predicate predicate,yarnwrap.util.math.Vec3d velocity,yarnwrap.world.World world,float margin,Object raycastShapeType) { return new yarnwrap.util.hit.HitResult(wrapperContained.getCollision(pos.wrapperContained,entity.wrapperContained,predicate,velocity.wrapperContained,world.wrapperContained,margin,raycastShapeType)); }
// public static yarnwrap.util.hit.HitResult getCollision(yarnwrap.util.math.Vec3d pos,yarnwrap.entity.Entity entity,java.util.function.Predicate predicate,yarnwrap.util.math.Vec3d velocity,yarnwrap.world.World world,float margin,Object raycastShapeType, ) { return new yarnwrap.util.hit.HitResult(net.minecraft.entity.projectile.ProjectileUtil.getCollision(pos.wrapperContained,entity.wrapperContained,predicate,velocity.wrapperContained,world.wrapperContained,margin,raycastShapeType)); }
// public yarnwrap.util.hit.EntityHitResult raycast(yarnwrap.entity.Entity entity,yarnwrap.util.math.Vec3d min,yarnwrap.util.math.Vec3d max,yarnwrap.util.math.Box box,java.util.function.Predicate predicate,double maxDistance) { return new yarnwrap.util.hit.EntityHitResult(wrapperContained.raycast(entity.wrapperContained,min.wrapperContained,max.wrapperContained,box.wrapperContained,predicate,maxDistance)); }
// public static yarnwrap.util.hit.EntityHitResult raycast(yarnwrap.entity.Entity entity,yarnwrap.util.math.Vec3d min,yarnwrap.util.math.Vec3d max,yarnwrap.util.math.Box box,java.util.function.Predicate predicate,double maxDistance, ) { return new yarnwrap.util.hit.EntityHitResult(net.minecraft.entity.projectile.ProjectileUtil.raycast(entity.wrapperContained,min.wrapperContained,max.wrapperContained,box.wrapperContained,predicate,maxDistance)); }
// public yarnwrap.util.hit.EntityHitResult getEntityCollision(yarnwrap.world.World world,yarnwrap.entity.projectile.ProjectileEntity projectile,yarnwrap.util.math.Vec3d min,yarnwrap.util.math.Vec3d max,yarnwrap.util.math.Box box,java.util.function.Predicate predicate) { return new yarnwrap.util.hit.EntityHitResult(wrapperContained.getEntityCollision(world.wrapperContained,projectile.wrapperContained,min.wrapperContained,max.wrapperContained,box.wrapperContained,predicate)); }
// public static yarnwrap.util.hit.EntityHitResult getEntityCollision(yarnwrap.world.World world,yarnwrap.entity.projectile.ProjectileEntity projectile,yarnwrap.util.math.Vec3d min,yarnwrap.util.math.Vec3d max,yarnwrap.util.math.Box box,java.util.function.Predicate predicate, ) { return new yarnwrap.util.hit.EntityHitResult(net.minecraft.entity.projectile.ProjectileUtil.getEntityCollision(world.wrapperContained,projectile.wrapperContained,min.wrapperContained,max.wrapperContained,box.wrapperContained,predicate)); }
// public yarnwrap.util.Hand getHandPossiblyHolding(yarnwrap.entity.LivingEntity entity,yarnwrap.item.Item item) { return new yarnwrap.util.Hand(wrapperContained.getHandPossiblyHolding(entity.wrapperContained,item.wrapperContained)); }
// public static yarnwrap.util.Hand getHandPossiblyHolding(yarnwrap.entity.LivingEntity entity,yarnwrap.item.Item item, ) { return new yarnwrap.util.Hand(net.minecraft.entity.projectile.ProjectileUtil.getHandPossiblyHolding(entity.wrapperContained,item.wrapperContained)); }
// public yarnwrap.entity.projectile.PersistentProjectileEntity createArrowProjectile(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,float damageModifier,yarnwrap.item.ItemStack bow) { return new yarnwrap.entity.projectile.PersistentProjectileEntity(wrapperContained.createArrowProjectile(entity.wrapperContained,stack.wrapperContained,damageModifier,bow.wrapperContained)); }
// public static yarnwrap.entity.projectile.PersistentProjectileEntity createArrowProjectile(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,float damageModifier,yarnwrap.item.ItemStack bow, ) { return new yarnwrap.entity.projectile.PersistentProjectileEntity(net.minecraft.entity.projectile.ProjectileUtil.createArrowProjectile(entity.wrapperContained,stack.wrapperContained,damageModifier,bow.wrapperContained)); }
// public yarnwrap.util.hit.EntityHitResult getEntityCollision(yarnwrap.world.World world,yarnwrap.entity.Entity entity,yarnwrap.util.math.Vec3d min,yarnwrap.util.math.Vec3d max,yarnwrap.util.math.Box box,java.util.function.Predicate predicate,float margin) { return new yarnwrap.util.hit.EntityHitResult(wrapperContained.getEntityCollision(world.wrapperContained,entity.wrapperContained,min.wrapperContained,max.wrapperContained,box.wrapperContained,predicate,margin)); }
// public static yarnwrap.util.hit.EntityHitResult getEntityCollision(yarnwrap.world.World world,yarnwrap.entity.Entity entity,yarnwrap.util.math.Vec3d min,yarnwrap.util.math.Vec3d max,yarnwrap.util.math.Box box,java.util.function.Predicate predicate,float margin, ) { return new yarnwrap.util.hit.EntityHitResult(net.minecraft.entity.projectile.ProjectileUtil.getEntityCollision(world.wrapperContained,entity.wrapperContained,min.wrapperContained,max.wrapperContained,box.wrapperContained,predicate,margin)); }
// public yarnwrap.util.hit.HitResult getCollision(yarnwrap.entity.Entity entity,java.util.function.Predicate predicate) { return new yarnwrap.util.hit.HitResult(wrapperContained.getCollision(entity.wrapperContained,predicate)); }
// public static yarnwrap.util.hit.HitResult getCollision(yarnwrap.entity.Entity entity,java.util.function.Predicate predicate, ) { return new yarnwrap.util.hit.HitResult(net.minecraft.entity.projectile.ProjectileUtil.getCollision(entity.wrapperContained,predicate)); }
// public yarnwrap.util.hit.HitResult getCollision(yarnwrap.entity.Entity entity,java.util.function.Predicate predicate,double range) { return new yarnwrap.util.hit.HitResult(wrapperContained.getCollision(entity.wrapperContained,predicate,range)); }
// public static yarnwrap.util.hit.HitResult getCollision(yarnwrap.entity.Entity entity,java.util.function.Predicate predicate,double range, ) { return new yarnwrap.util.hit.HitResult(net.minecraft.entity.projectile.ProjectileUtil.getCollision(entity.wrapperContained,predicate,range)); }
// // public yarnwrap.util.hit.HitResult getCollision(yarnwrap.entity.Entity entity,java.util.function.Predicate predicate,Object raycastShapeType) { return new yarnwrap.util.hit.HitResult(wrapperContained.getCollision(entity.wrapperContained,predicate,raycastShapeType)); }
// public static yarnwrap.util.hit.HitResult getCollision(yarnwrap.entity.Entity entity,java.util.function.Predicate predicate,Object raycastShapeType, ) { return new yarnwrap.util.hit.HitResult(net.minecraft.entity.projectile.ProjectileUtil.getCollision(entity.wrapperContained,predicate,raycastShapeType)); }
// public float getToleranceMargin(yarnwrap.entity.Entity entity) { return wrapperContained.getToleranceMargin(entity.wrapperContained); }
// public static float getToleranceMargin(yarnwrap.entity.Entity entity, ) { return net.minecraft.entity.projectile.ProjectileUtil.getToleranceMargin(entity.wrapperContained); }

}