package yarnwrap.enchantment;
public class Enchantment { public net.minecraft.enchantment.Enchantment wrapperContained; public Enchantment(net.minecraft.enchantment.Enchantment wrapperContained) { this.wrapperContained = wrapperContained; }

public com.mojang.serialization.Codec CODEC() { return wrapperContained.CODEC; }
public com.mojang.serialization.Codec ENTRY_CODEC() { return wrapperContained.ENTRY_CODEC; }
public int MAX_LEVEL() { return wrapperContained.MAX_LEVEL; }
public yarnwrap.network.codec.PacketCodec ENTRY_PACKET_CODEC() { return new yarnwrap.network.codec.PacketCodec(wrapperContained.ENTRY_PACKET_CODEC); }
public int getMaxPower(int level) { return wrapperContained.getMaxPower(level); }
public yarnwrap.registry.entry.RegistryEntryList getApplicableItems() { return new yarnwrap.registry.entry.RegistryEntryList(wrapperContained.getApplicableItems()); }
public Object constantCost(int base) { return wrapperContained.constantCost(base); }
public Object leveledCost(int base,int perLevel) { return wrapperContained.leveledCost(base,perLevel); }
// public Object definition(yarnwrap.registry.entry.RegistryEntryList supportedItems,int weight,int maxLevel,Object minCost,Object maxCost,int anvilCost,net.minecraft.component.type.AttributeModifierSlot[] slots) { return wrapperContained.definition(supportedItems.wrapperContained,weight,maxLevel,minCost,maxCost,anvilCost,slots); }
// public Object definition(yarnwrap.registry.entry.RegistryEntryList supportedItems,yarnwrap.registry.entry.RegistryEntryList primaryItems,int weight,int maxLevel,Object minCost,Object maxCost,int anvilCost,net.minecraft.component.type.AttributeModifierSlot[] slots) { return wrapperContained.definition(supportedItems.wrapperContained,primaryItems.wrapperContained,weight,maxLevel,minCost,maxCost,anvilCost,slots); }
public boolean isPrimaryItem(yarnwrap.item.ItemStack stack) { return wrapperContained.isPrimaryItem(stack.wrapperContained); }
public int getWeight() { return wrapperContained.getWeight(); }
public int getAnvilCost() { return wrapperContained.getAnvilCost(); }
public void removeLocationBasedEffects(int level,yarnwrap.enchantment.EnchantmentEffectContext context,yarnwrap.entity.LivingEntity user) { wrapperContained.removeLocationBasedEffects(level,context.wrapperContained,user.wrapperContained); }
public boolean hasDamageImmunityTo(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource) { return wrapperContained.hasDamageImmunityTo(world.wrapperContained,level,user.wrapperContained,damageSource.wrapperContained); }
// public yarnwrap.loot.context.LootContext createEnchantedEntityLootContext(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.entity.Entity entity,yarnwrap.util.math.Vec3d pos) { return new yarnwrap.loot.context.LootContext(wrapperContained.createEnchantedEntityLootContext(world.wrapperContained,level,entity.wrapperContained,pos.wrapperContained)); }
// public yarnwrap.loot.context.LootContext createEnchantedLocationLootContext(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.entity.Entity entity,boolean enchantmentActive) { return new yarnwrap.loot.context.LootContext(wrapperContained.createEnchantedLocationLootContext(world.wrapperContained,level,entity.wrapperContained,enchantmentActive)); }
// public yarnwrap.loot.context.LootContext createEnchantedItemLootContext(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack) { return new yarnwrap.loot.context.LootContext(wrapperContained.createEnchantedItemLootContext(world.wrapperContained,level,stack.wrapperContained)); }
public void modifyDamageProtection(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,org.apache.commons.lang3.mutable.MutableFloat damageProtection) { wrapperContained.modifyDamageProtection(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,damageProtection); }
public void modifyMobExperience(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,org.apache.commons.lang3.mutable.MutableFloat mobExperience) { wrapperContained.modifyMobExperience(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,mobExperience); }
public void modifyItemDamage(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,org.apache.commons.lang3.mutable.MutableFloat itemDamage) { wrapperContained.modifyItemDamage(world.wrapperContained,level,stack.wrapperContained,itemDamage); }
public void onTick(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.enchantment.EnchantmentEffectContext context,yarnwrap.entity.Entity user) { wrapperContained.onTick(world.wrapperContained,level,context.wrapperContained,user.wrapperContained); }
public void onHitBlock(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.enchantment.EnchantmentEffectContext context,yarnwrap.entity.Entity enchantedEntity,yarnwrap.util.math.Vec3d pos,yarnwrap.block.BlockState state) { wrapperContained.onHitBlock(world.wrapperContained,level,context.wrapperContained,enchantedEntity.wrapperContained,pos.wrapperContained,state.wrapperContained); }
public void applyLocationBasedEffects(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.enchantment.EnchantmentEffectContext context,yarnwrap.entity.LivingEntity user) { wrapperContained.applyLocationBasedEffects(world.wrapperContained,level,context.wrapperContained,user.wrapperContained); }
public boolean slotMatches(yarnwrap.entity.EquipmentSlot slot) { return wrapperContained.slotMatches(slot.wrapperContained); }
// public Object builder(Object definition) { return wrapperContained.builder(definition); }
public void applyTargetedEffect(yarnwrap.enchantment.effect.TargetedEnchantmentEffect effect,yarnwrap.server.world.ServerWorld world,int level,yarnwrap.enchantment.EnchantmentEffectContext context,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource) { wrapperContained.applyTargetedEffect(effect.wrapperContained,world.wrapperContained,level,context.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
// public void applyEffects(java.util.List entries,yarnwrap.loot.context.LootContext lootContext,java.util.function.Consumer effectConsumer) { wrapperContained.applyEffects(entries,lootContext.wrapperContained,effectConsumer); }
public boolean canBeCombined(yarnwrap.registry.entry.RegistryEntry first,yarnwrap.registry.entry.RegistryEntry second) { return wrapperContained.canBeCombined(first.wrapperContained,second.wrapperContained); }
public java.util.List getEffect(yarnwrap.component.ComponentType type) { return wrapperContained.getEffect(type.wrapperContained); }
// public void modifyValue(yarnwrap.component.ComponentType type,yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,org.apache.commons.lang3.mutable.MutableFloat value) { wrapperContained.modifyValue(type.wrapperContained,world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,value); }
// public void modifyValue(yarnwrap.component.ComponentType type,yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,org.apache.commons.lang3.mutable.MutableFloat value) { wrapperContained.modifyValue(type.wrapperContained,world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,value); }
// public void modifyValue(yarnwrap.component.ComponentType type,yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,org.apache.commons.lang3.mutable.MutableFloat value) { wrapperContained.modifyValue(type.wrapperContained,world.wrapperContained,level,stack.wrapperContained,value); }
public yarnwrap.loot.context.LootContext createEnchantedDamageLootContext(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.entity.Entity entity,yarnwrap.entity.damage.DamageSource damageSource) { return new yarnwrap.loot.context.LootContext(wrapperContained.createEnchantedDamageLootContext(world.wrapperContained,level,entity.wrapperContained,damageSource.wrapperContained)); }
public void modifyDamage(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,org.apache.commons.lang3.mutable.MutableFloat damage) { wrapperContained.modifyDamage(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,damage); }
public void modifyTridentReturnAcceleration(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,org.apache.commons.lang3.mutable.MutableFloat tridentReturnAcceleration) { wrapperContained.modifyTridentReturnAcceleration(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,tridentReturnAcceleration); }
public void modifyAmmoUse(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack projectileStack,org.apache.commons.lang3.mutable.MutableFloat ammoUse) { wrapperContained.modifyAmmoUse(world.wrapperContained,level,projectileStack.wrapperContained,ammoUse); }
public void onProjectileSpawned(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.enchantment.EnchantmentEffectContext context,yarnwrap.entity.Entity user) { wrapperContained.onProjectileSpawned(world.wrapperContained,level,context.wrapperContained,user.wrapperContained); }
public boolean isSupportedItem(yarnwrap.item.ItemStack stack) { return wrapperContained.isSupportedItem(stack.wrapperContained); }
public void modifySmashDamagePerFallenBlock(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,org.apache.commons.lang3.mutable.MutableFloat smashDamagePerFallenBlock) { wrapperContained.modifySmashDamagePerFallenBlock(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,smashDamagePerFallenBlock); }
public void modifyTridentSpinAttackStrength(yarnwrap.util.math.random.Random random,int level,org.apache.commons.lang3.mutable.MutableFloat tridentSpinAttackStrength) { wrapperContained.modifyTridentSpinAttackStrength(random.wrapperContained,level,tridentSpinAttackStrength); }
public void modifyProjectilePiercing(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,org.apache.commons.lang3.mutable.MutableFloat projectilePiercing) { wrapperContained.modifyProjectilePiercing(world.wrapperContained,level,stack.wrapperContained,projectilePiercing); }
public void modifyKnockback(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,org.apache.commons.lang3.mutable.MutableFloat knockback) { wrapperContained.modifyKnockback(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,knockback); }
public void modifyFishingTimeReduction(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,org.apache.commons.lang3.mutable.MutableFloat fishingTimeReduction) { wrapperContained.modifyFishingTimeReduction(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,fishingTimeReduction); }
public void modifyBlockExperience(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,org.apache.commons.lang3.mutable.MutableFloat blockExperience) { wrapperContained.modifyBlockExperience(world.wrapperContained,level,stack.wrapperContained,blockExperience); }
public void modifyArmorEffectiveness(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,org.apache.commons.lang3.mutable.MutableFloat armorEffectiveness) { wrapperContained.modifyArmorEffectiveness(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,armorEffectiveness); }
public void modifyFishingLuckBonus(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,org.apache.commons.lang3.mutable.MutableFloat fishingLuckBonus) { wrapperContained.modifyFishingLuckBonus(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,fishingLuckBonus); }
public void modifyRepairWithXp(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,org.apache.commons.lang3.mutable.MutableFloat repairWithXp) { wrapperContained.modifyRepairWithXp(world.wrapperContained,level,stack.wrapperContained,repairWithXp); }
public void modifyProjectileCount(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,org.apache.commons.lang3.mutable.MutableFloat projectileCount) { wrapperContained.modifyProjectileCount(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,projectileCount); }
public void modifyCrossbowChargeTime(yarnwrap.util.math.random.Random random,int level,org.apache.commons.lang3.mutable.MutableFloat crossbowChargeTime) { wrapperContained.modifyCrossbowChargeTime(random.wrapperContained,level,crossbowChargeTime); }
public void modifyProjectileSpread(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,org.apache.commons.lang3.mutable.MutableFloat projectileSpread) { wrapperContained.modifyProjectileSpread(world.wrapperContained,level,stack.wrapperContained,user.wrapperContained,projectileSpread); }
public void modifyValue(yarnwrap.component.ComponentType type,yarnwrap.util.math.random.Random random,int level,org.apache.commons.lang3.mutable.MutableFloat value) { wrapperContained.modifyValue(type.wrapperContained,random.wrapperContained,level,value); }
// public yarnwrap.loot.context.LootContext createHitBlockLootContext(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.entity.Entity entity,yarnwrap.util.math.Vec3d pos,yarnwrap.block.BlockState state) { return new yarnwrap.loot.context.LootContext(wrapperContained.createHitBlockLootContext(world.wrapperContained,level,entity.wrapperContained,pos.wrapperContained,state.wrapperContained)); }
public yarnwrap.text.Text getName(yarnwrap.registry.entry.RegistryEntry enchantment,int level) { return new yarnwrap.text.Text(wrapperContained.getName(enchantment.wrapperContained,level)); }
public int getMinPower(int level) { return wrapperContained.getMinPower(level); }
public int getMaxLevel() { return wrapperContained.getMaxLevel(); }
public java.util.Map getEquipment(yarnwrap.entity.LivingEntity entity) { return wrapperContained.getEquipment(entity.wrapperContained); }
public int getMinLevel() { return wrapperContained.getMinLevel(); }
public void onTargetDamaged(yarnwrap.server.world.ServerWorld world,int level,yarnwrap.enchantment.EnchantmentEffectContext context,yarnwrap.enchantment.effect.EnchantmentEffectTarget target,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource) { wrapperContained.onTargetDamaged(world.wrapperContained,level,context.wrapperContained,target.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
public boolean isAcceptableItem(yarnwrap.item.ItemStack stack) { return wrapperContained.isAcceptableItem(stack.wrapperContained); }

}