package yarnwrap.world;
public class WorldEvents { public net.minecraft.world.WorldEvents wrapperContained; public WorldEvents(net.minecraft.world.WorldEvents wrapperContained) { this.wrapperContained = wrapperContained; }

public int ZOMBIE_INFECTS_VILLAGER() { return wrapperContained.ZOMBIE_INFECTS_VILLAGER; }
public int ZOMBIE_VILLAGER_CURED() { return wrapperContained.ZOMBIE_VILLAGER_CURED; }
public int ENDER_DRAGON_DIES() { return wrapperContained.ENDER_DRAGON_DIES; }
public int ANVIL_DESTROYED() { return wrapperContained.ANVIL_DESTROYED; }
public int ANVIL_USED() { return wrapperContained.ANVIL_USED; }
public int ANVIL_LANDS() { return wrapperContained.ANVIL_LANDS; }
public int TRAVEL_THROUGH_PORTAL() { return wrapperContained.TRAVEL_THROUGH_PORTAL; }
public int CHORUS_FLOWER_GROWS() { return wrapperContained.CHORUS_FLOWER_GROWS; }
public int CHORUS_FLOWER_DIES() { return wrapperContained.CHORUS_FLOWER_DIES; }
public int BREWING_STAND_BREWS() { return wrapperContained.BREWING_STAND_BREWS; }
public int END_PORTAL_OPENED() { return wrapperContained.END_PORTAL_OPENED; }
public int PHANTOM_BITES() { return wrapperContained.PHANTOM_BITES; }
public int ZOMBIE_CONVERTS_TO_DROWNED() { return wrapperContained.ZOMBIE_CONVERTS_TO_DROWNED; }
public int HUSK_CONVERTS_TO_ZOMBIE() { return wrapperContained.HUSK_CONVERTS_TO_ZOMBIE; }
public int GRINDSTONE_USED() { return wrapperContained.GRINDSTONE_USED; }
public int LECTERN_BOOK_PAGE_TURNED() { return wrapperContained.LECTERN_BOOK_PAGE_TURNED; }
public int SMITHING_TABLE_USED() { return wrapperContained.SMITHING_TABLE_USED; }
public int POINTED_DRIPSTONE_LANDS() { return wrapperContained.POINTED_DRIPSTONE_LANDS; }
public int POINTED_DRIPSTONE_DRIPS_LAVA_INTO_CAULDRON() { return wrapperContained.POINTED_DRIPSTONE_DRIPS_LAVA_INTO_CAULDRON; }
public int POINTED_DRIPSTONE_DRIPS_WATER_INTO_CAULDRON() { return wrapperContained.POINTED_DRIPSTONE_DRIPS_WATER_INTO_CAULDRON; }
public int SKELETON_CONVERTS_TO_STRAY() { return wrapperContained.SKELETON_CONVERTS_TO_STRAY; }
public int COMPOSTER_USED() { return wrapperContained.COMPOSTER_USED; }
public int LAVA_EXTINGUISHED() { return wrapperContained.LAVA_EXTINGUISHED; }
public int REDSTONE_TORCH_BURNS_OUT() { return wrapperContained.REDSTONE_TORCH_BURNS_OUT; }
public int DISPENSER_DISPENSES() { return wrapperContained.DISPENSER_DISPENSES; }
public int END_PORTAL_FRAME_FILLED() { return wrapperContained.END_PORTAL_FRAME_FILLED; }
public int POINTED_DRIPSTONE_DRIPS() { return wrapperContained.POINTED_DRIPSTONE_DRIPS; }
public int DISPENSER_ACTIVATED() { return wrapperContained.DISPENSER_ACTIVATED; }
public int BLOCK_BROKEN() { return wrapperContained.BLOCK_BROKEN; }
public int SPLASH_POTION_SPLASHED() { return wrapperContained.SPLASH_POTION_SPLASHED; }
public int EYE_OF_ENDER_BREAKS() { return wrapperContained.EYE_OF_ENDER_BREAKS; }
public int SPAWNER_SPAWNS_MOB() { return wrapperContained.SPAWNER_SPAWNS_MOB; }
public int DRAGON_BREATH_CLOUD_SPAWNS() { return wrapperContained.DRAGON_BREATH_CLOUD_SPAWNS; }
public int INSTANT_SPLASH_POTION_SPLASHED() { return wrapperContained.INSTANT_SPLASH_POTION_SPLASHED; }
public int ENDER_DRAGON_BREAKS_BLOCK() { return wrapperContained.ENDER_DRAGON_BREAKS_BLOCK; }
public int WET_SPONGE_DRIES_OUT() { return wrapperContained.WET_SPONGE_DRIES_OUT; }
public int END_GATEWAY_SPAWNS() { return wrapperContained.END_GATEWAY_SPAWNS; }
public int ENDER_DRAGON_RESURRECTED() { return wrapperContained.ENDER_DRAGON_RESURRECTED; }
public int ELECTRICITY_SPARKS() { return wrapperContained.ELECTRICITY_SPARKS; }
public int BLOCK_WAXED() { return wrapperContained.BLOCK_WAXED; }
public int WAX_REMOVED() { return wrapperContained.WAX_REMOVED; }
public int BLOCK_SCRAPED() { return wrapperContained.BLOCK_SCRAPED; }
public int DISPENSER_FAILS() { return wrapperContained.DISPENSER_FAILS; }
public int DISPENSER_LAUNCHES_PROJECTILE() { return wrapperContained.DISPENSER_LAUNCHES_PROJECTILE; }
public int FIREWORK_ROCKET_SHOOTS() { return wrapperContained.FIREWORK_ROCKET_SHOOTS; }
public int FIRE_EXTINGUISHED() { return wrapperContained.FIRE_EXTINGUISHED; }
public int GHAST_WARNS() { return wrapperContained.GHAST_WARNS; }
public int GHAST_SHOOTS() { return wrapperContained.GHAST_SHOOTS; }
public int ENDER_DRAGON_SHOOTS() { return wrapperContained.ENDER_DRAGON_SHOOTS; }
public int BLAZE_SHOOTS() { return wrapperContained.BLAZE_SHOOTS; }
public int ZOMBIE_ATTACKS_WOODEN_DOOR() { return wrapperContained.ZOMBIE_ATTACKS_WOODEN_DOOR; }
public int ZOMBIE_ATTACKS_IRON_DOOR() { return wrapperContained.ZOMBIE_ATTACKS_IRON_DOOR; }
public int ZOMBIE_BREAKS_WOODEN_DOOR() { return wrapperContained.ZOMBIE_BREAKS_WOODEN_DOOR; }
public int WITHER_BREAKS_BLOCK() { return wrapperContained.WITHER_BREAKS_BLOCK; }
public int WITHER_SPAWNS() { return wrapperContained.WITHER_SPAWNS; }
public int WITHER_SHOOTS() { return wrapperContained.WITHER_SHOOTS; }
public int BAT_TAKES_OFF() { return wrapperContained.BAT_TAKES_OFF; }
public int BONE_MEAL_USED() { return wrapperContained.BONE_MEAL_USED; }
public int SCULK_CHARGE() { return wrapperContained.SCULK_CHARGE; }
public int SCULK_SHRIEKS() { return wrapperContained.SCULK_SHRIEKS; }
public int BLOCK_FINISHED_BRUSHING() { return wrapperContained.BLOCK_FINISHED_BRUSHING; }
public int JUKEBOX_STARTS_PLAYING() { return wrapperContained.JUKEBOX_STARTS_PLAYING; }
public int JUKEBOX_STOPS_PLAYING() { return wrapperContained.JUKEBOX_STOPS_PLAYING; }
public int SNIFFER_EGG_CRACKS() { return wrapperContained.SNIFFER_EGG_CRACKS; }
public int CRAFTER_CRAFTS() { return wrapperContained.CRAFTER_CRAFTS; }
public int CRAFTER_FAILS() { return wrapperContained.CRAFTER_FAILS; }
public int CRAFTER_SHOOTS() { return wrapperContained.CRAFTER_SHOOTS; }
public int TRIAL_SPAWNER_SPAWNS_MOB() { return wrapperContained.TRIAL_SPAWNER_SPAWNS_MOB; }
public int TRIAL_SPAWNER_SPAWNS_MOB_AT_SPAWN_POS() { return wrapperContained.TRIAL_SPAWNER_SPAWNS_MOB_AT_SPAWN_POS; }
public int TRIAL_SPAWNER_DETECTS_PLAYER() { return wrapperContained.TRIAL_SPAWNER_DETECTS_PLAYER; }
public int TRIAL_SPAWNER_EJECTS_ITEM() { return wrapperContained.TRIAL_SPAWNER_EJECTS_ITEM; }
public int BEE_FERTILIZES_PLANT() { return wrapperContained.BEE_FERTILIZES_PLANT; }
public int TURTLE_EGG_PLACED() { return wrapperContained.TURTLE_EGG_PLACED; }
public int VAULT_ACTIVATES() { return wrapperContained.VAULT_ACTIVATES; }
public int VAULT_DEACTIVATES() { return wrapperContained.VAULT_DEACTIVATES; }
public int VAULT_EJECTS_ITEM() { return wrapperContained.VAULT_EJECTS_ITEM; }
public int COBWEB_WEAVED() { return wrapperContained.COBWEB_WEAVED; }
public int OMINOUS_TRIAL_SPAWNER_DETECTS_PLAYER() { return wrapperContained.OMINOUS_TRIAL_SPAWNER_DETECTS_PLAYER; }
public int TRIAL_SPAWNER_TURNS_OMINOUS() { return wrapperContained.TRIAL_SPAWNER_TURNS_OMINOUS; }
public int OMINOUS_ITEM_SPAWNER_SPAWNS_ITEM() { return wrapperContained.OMINOUS_ITEM_SPAWNER_SPAWNS_ITEM; }
public int SMASH_ATTACK() { return wrapperContained.SMASH_ATTACK; }

}