package yarnwrap.entity.ai.brain.task;
public class LookTargetUtil { public net.minecraft.entity.ai.brain.task.LookTargetUtil wrapperContained; public LookTargetUtil(net.minecraft.entity.ai.brain.task.LookTargetUtil wrapperContained) { this.wrapperContained = wrapperContained; }

public void lookAtAndWalkTowardsEachOther(yarnwrap.entity.LivingEntity first,yarnwrap.entity.LivingEntity second,float speed,int walkCompletionRange) { wrapperContained.lookAtAndWalkTowardsEachOther(first.wrapperContained,second.wrapperContained,speed,walkCompletionRange); }
public boolean canSee(yarnwrap.entity.ai.brain.Brain brain,yarnwrap.entity.LivingEntity target) { return wrapperContained.canSee(brain.wrapperContained,target.wrapperContained); }
public boolean canSee(yarnwrap.entity.ai.brain.Brain brain,yarnwrap.entity.ai.brain.MemoryModuleType memoryModuleType,yarnwrap.entity.EntityType entityType) { return wrapperContained.canSee(brain.wrapperContained,memoryModuleType.wrapperContained,entityType.wrapperContained); }
// public void lookAtEachOther(yarnwrap.entity.LivingEntity first,yarnwrap.entity.LivingEntity second) { wrapperContained.lookAtEachOther(first.wrapperContained,second.wrapperContained); }
public void lookAt(yarnwrap.entity.LivingEntity entity,yarnwrap.entity.LivingEntity target) { wrapperContained.lookAt(entity.wrapperContained,target.wrapperContained); }
// public void walkTowardsEachOther(yarnwrap.entity.LivingEntity first,yarnwrap.entity.LivingEntity second,float speed,int completionRange) { wrapperContained.walkTowardsEachOther(first.wrapperContained,second.wrapperContained,speed,completionRange); }
public void give(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,yarnwrap.util.math.Vec3d targetLocation) { wrapperContained.give(entity.wrapperContained,stack.wrapperContained,targetLocation.wrapperContained); }
public yarnwrap.util.math.ChunkSectionPos getPosClosestToOccupiedPointOfInterest(yarnwrap.server.world.ServerWorld world,yarnwrap.util.math.ChunkSectionPos center,int radius) { return new yarnwrap.util.math.ChunkSectionPos(wrapperContained.getPosClosestToOccupiedPointOfInterest(world.wrapperContained,center.wrapperContained,radius)); }
public void walkTowards(yarnwrap.entity.LivingEntity entity,yarnwrap.entity.Entity target,float speed,int completionRange) { wrapperContained.walkTowards(entity.wrapperContained,target.wrapperContained,speed,completionRange); }
public boolean isNewTargetTooFar(yarnwrap.entity.LivingEntity source,yarnwrap.entity.LivingEntity target,double extraDistance) { return wrapperContained.isNewTargetTooFar(source.wrapperContained,target.wrapperContained,extraDistance); }
public yarnwrap.entity.LivingEntity getCloserEntity(yarnwrap.entity.LivingEntity source,yarnwrap.entity.LivingEntity first,yarnwrap.entity.LivingEntity second) { return new yarnwrap.entity.LivingEntity(wrapperContained.getCloserEntity(source.wrapperContained,first.wrapperContained,second.wrapperContained)); }
public java.util.Optional getEntity(yarnwrap.entity.LivingEntity entity,yarnwrap.entity.ai.brain.MemoryModuleType uuidMemoryModule) { return wrapperContained.getEntity(entity.wrapperContained,uuidMemoryModule.wrapperContained); }
public void walkTowards(yarnwrap.entity.LivingEntity entity,yarnwrap.util.math.BlockPos target,float speed,int completionRange) { wrapperContained.walkTowards(entity.wrapperContained,target.wrapperContained,speed,completionRange); }
public yarnwrap.entity.LivingEntity getCloserEntity(yarnwrap.entity.LivingEntity source,java.util.Optional first,yarnwrap.entity.LivingEntity second) { return new yarnwrap.entity.LivingEntity(wrapperContained.getCloserEntity(source.wrapperContained,first,second.wrapperContained)); }
// public boolean canSee(yarnwrap.entity.ai.brain.Brain brain,yarnwrap.entity.ai.brain.MemoryModuleType memoryType,java.util.function.Predicate filter) { return wrapperContained.canSee(brain.wrapperContained,memoryType.wrapperContained,filter); }
public boolean isVisibleInMemory(yarnwrap.entity.LivingEntity source,yarnwrap.entity.LivingEntity target) { return wrapperContained.isVisibleInMemory(source.wrapperContained,target.wrapperContained); }
public boolean isTargetWithinAttackRange(yarnwrap.entity.mob.MobEntity mob,yarnwrap.entity.LivingEntity target,int rangedWeaponReachReduction) { return wrapperContained.isTargetWithinAttackRange(mob.wrapperContained,target.wrapperContained,rangedWeaponReachReduction); }
public yarnwrap.util.math.Vec3d find(yarnwrap.entity.mob.PathAwareEntity entity,int horizontalRange,int verticalRange) { return new yarnwrap.util.math.Vec3d(wrapperContained.find(entity.wrapperContained,horizontalRange,verticalRange)); }
public boolean hasBreedTarget(yarnwrap.entity.LivingEntity entity) { return wrapperContained.hasBreedTarget(entity.wrapperContained); }
public void walkTowards(yarnwrap.entity.LivingEntity entity,yarnwrap.entity.ai.brain.LookTarget target,float speed,int completionRange) { wrapperContained.walkTowards(entity.wrapperContained,target.wrapperContained,speed,completionRange); }
public void give(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,yarnwrap.util.math.Vec3d targetLocation,yarnwrap.util.math.Vec3d velocityFactor,float yOffset) { wrapperContained.give(entity.wrapperContained,stack.wrapperContained,targetLocation.wrapperContained,velocityFactor.wrapperContained,yOffset); }

}