package yarnwrap.world.biome;
public class TheEndBiomeCreator { public net.minecraft.world.biome.TheEndBiomeCreator wrapperContained; public TheEndBiomeCreator(net.minecraft.world.biome.TheEndBiomeCreator wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.world.biome.Biome createEndBarrens(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup) { return new yarnwrap.world.biome.Biome(wrapperContained.createEndBarrens(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public static yarnwrap.world.biome.Biome createEndBarrens(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup, ) { return new yarnwrap.world.biome.Biome(net.minecraft.world.biome.TheEndBiomeCreator.createEndBarrens(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public yarnwrap.world.biome.Biome createEndBiome(Object builder) { return new yarnwrap.world.biome.Biome(wrapperContained.createEndBiome(builder)); }
// public static yarnwrap.world.biome.Biome createEndBiome(Object builder, ) { return new yarnwrap.world.biome.Biome(net.minecraft.world.biome.TheEndBiomeCreator.createEndBiome(builder)); }
// public yarnwrap.world.biome.Biome createTheEnd(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup) { return new yarnwrap.world.biome.Biome(wrapperContained.createTheEnd(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public static yarnwrap.world.biome.Biome createTheEnd(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup, ) { return new yarnwrap.world.biome.Biome(net.minecraft.world.biome.TheEndBiomeCreator.createTheEnd(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public yarnwrap.world.biome.Biome createEndMidlands(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup) { return new yarnwrap.world.biome.Biome(wrapperContained.createEndMidlands(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public static yarnwrap.world.biome.Biome createEndMidlands(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup, ) { return new yarnwrap.world.biome.Biome(net.minecraft.world.biome.TheEndBiomeCreator.createEndMidlands(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public yarnwrap.world.biome.Biome createEndHighlands(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup) { return new yarnwrap.world.biome.Biome(wrapperContained.createEndHighlands(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public static yarnwrap.world.biome.Biome createEndHighlands(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup, ) { return new yarnwrap.world.biome.Biome(net.minecraft.world.biome.TheEndBiomeCreator.createEndHighlands(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public yarnwrap.world.biome.Biome createSmallEndIslands(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup) { return new yarnwrap.world.biome.Biome(wrapperContained.createSmallEndIslands(featureLookup.wrapperContained,carverLookup.wrapperContained)); }
// public static yarnwrap.world.biome.Biome createSmallEndIslands(yarnwrap.registry.RegistryEntryLookup featureLookup,yarnwrap.registry.RegistryEntryLookup carverLookup, ) { return new yarnwrap.world.biome.Biome(net.minecraft.world.biome.TheEndBiomeCreator.createSmallEndIslands(featureLookup.wrapperContained,carverLookup.wrapperContained)); }

}