package yarnwrap.entity;
public class EntityStatuses { public net.minecraft.entity.EntityStatuses wrapperContained; public EntityStatuses(net.minecraft.entity.EntityStatuses wrapperContained) { this.wrapperContained = wrapperContained; }

public byte SET_OP_LEVEL_3() { return wrapperContained.SET_OP_LEVEL_3; }
public byte SET_OP_LEVEL_4() { return wrapperContained.SET_OP_LEVEL_4; }
public byte BLOCK_WITH_SHIELD() { return wrapperContained.BLOCK_WITH_SHIELD; }
public byte BREAK_SHIELD() { return wrapperContained.BREAK_SHIELD; }
public byte PULL_HOOKED_ENTITY() { return wrapperContained.PULL_HOOKED_ENTITY; }
public byte HIT_ARMOR_STAND() { return wrapperContained.HIT_ARMOR_STAND; }
public byte STOP_LOOKING_AT_VILLAGER() { return wrapperContained.STOP_LOOKING_AT_VILLAGER; }
public byte USE_TOTEM_OF_UNDYING() { return wrapperContained.USE_TOTEM_OF_UNDYING; }
public byte ADD_DOLPHIN_HAPPY_VILLAGER_PARTICLES() { return wrapperContained.ADD_DOLPHIN_HAPPY_VILLAGER_PARTICLES; }
public byte STUN_RAVAGER() { return wrapperContained.STUN_RAVAGER; }
public byte TAME_OCELOT_FAILED() { return wrapperContained.TAME_OCELOT_FAILED; }
public byte TAME_OCELOT_SUCCESS() { return wrapperContained.TAME_OCELOT_SUCCESS; }
public byte ADD_SPLASH_PARTICLES() { return wrapperContained.ADD_SPLASH_PARTICLES; }
public byte CREATE_EATING_PARTICLES() { return wrapperContained.CREATE_EATING_PARTICLES; }
public byte ADD_PORTAL_PARTICLES() { return wrapperContained.ADD_PORTAL_PARTICLES; }
public byte BREAK_MAINHAND() { return wrapperContained.BREAK_MAINHAND; }
public byte BREAK_OFFHAND() { return wrapperContained.BREAK_OFFHAND; }
public byte BREAK_HEAD() { return wrapperContained.BREAK_HEAD; }
public byte BREAK_CHEST() { return wrapperContained.BREAK_CHEST; }
public byte BREAK_LEGS() { return wrapperContained.BREAK_LEGS; }
public byte BREAK_FEET() { return wrapperContained.BREAK_FEET; }
public byte ADD_SPRINTING_PARTICLES_OR_RESET_SPAWNER_MINECART_SPAWN_DELAY() { return wrapperContained.ADD_SPRINTING_PARTICLES_OR_RESET_SPAWNER_MINECART_SPAWN_DELAY; }
public byte DRIP_HONEY() { return wrapperContained.DRIP_HONEY; }
public byte DRIP_RICH_HONEY() { return wrapperContained.DRIP_RICH_HONEY; }
public byte SWAP_HANDS() { return wrapperContained.SWAP_HANDS; }
public byte RESET_WOLF_SHAKE() { return wrapperContained.RESET_WOLF_SHAKE; }
public byte PLAY_DEATH_SOUND_OR_ADD_PROJECTILE_HIT_PARTICLES() { return wrapperContained.PLAY_DEATH_SOUND_OR_ADD_PROJECTILE_HIT_PARTICLES; }
public byte PLAY_ATTACK_SOUND() { return wrapperContained.PLAY_ATTACK_SOUND; }
public byte ADD_NEGATIVE_PLAYER_REACTION_PARTICLES() { return wrapperContained.ADD_NEGATIVE_PLAYER_REACTION_PARTICLES; }
public byte ADD_POSITIVE_PLAYER_REACTION_PARTICLES() { return wrapperContained.ADD_POSITIVE_PLAYER_REACTION_PARTICLES; }
public byte SHAKE_OFF_WATER() { return wrapperContained.SHAKE_OFF_WATER; }
public byte CONSUME_ITEM() { return wrapperContained.CONSUME_ITEM; }
public byte SET_SHEEP_EAT_GRASS_TIMER_OR_PRIME_TNT_MINECART() { return wrapperContained.SET_SHEEP_EAT_GRASS_TIMER_OR_PRIME_TNT_MINECART; }
public byte LOOK_AT_VILLAGER() { return wrapperContained.LOOK_AT_VILLAGER; }
public byte ADD_VILLAGER_HEART_PARTICLES() { return wrapperContained.ADD_VILLAGER_HEART_PARTICLES; }
public byte ADD_VILLAGER_ANGRY_PARTICLES() { return wrapperContained.ADD_VILLAGER_ANGRY_PARTICLES; }
public byte ADD_VILLAGER_HAPPY_PARTICLES() { return wrapperContained.ADD_VILLAGER_HAPPY_PARTICLES; }
public byte ADD_WITCH_PARTICLES() { return wrapperContained.ADD_WITCH_PARTICLES; }
public byte PLAY_CURE_ZOMBIE_VILLAGER_SOUND() { return wrapperContained.PLAY_CURE_ZOMBIE_VILLAGER_SOUND; }
public byte EXPLODE_FIREWORK_CLIENT() { return wrapperContained.EXPLODE_FIREWORK_CLIENT; }
public byte ADD_BREEDING_PARTICLES() { return wrapperContained.ADD_BREEDING_PARTICLES; }
public byte RESET_SQUID_THRUST_TIMER() { return wrapperContained.RESET_SQUID_THRUST_TIMER; }
public byte PLAY_SPAWN_EFFECTS() { return wrapperContained.PLAY_SPAWN_EFFECTS; }
public byte PLAY_GUARDIAN_ATTACK_SOUND() { return wrapperContained.PLAY_GUARDIAN_ATTACK_SOUND; }
public byte USE_REDUCED_DEBUG_INFO() { return wrapperContained.USE_REDUCED_DEBUG_INFO; }
public byte USE_FULL_DEBUG_INFO() { return wrapperContained.USE_FULL_DEBUG_INFO; }
public byte SET_OP_LEVEL_0() { return wrapperContained.SET_OP_LEVEL_0; }
public byte SET_OP_LEVEL_1() { return wrapperContained.SET_OP_LEVEL_1; }
public byte SET_OP_LEVEL_2() { return wrapperContained.SET_OP_LEVEL_2; }
public byte PREPARE_RAM() { return wrapperContained.PREPARE_RAM; }
public byte FINISH_RAM() { return wrapperContained.FINISH_RAM; }
public byte ADD_DEATH_PARTICLES() { return wrapperContained.ADD_DEATH_PARTICLES; }
public byte EARS_TWITCH() { return wrapperContained.EARS_TWITCH; }
public byte SONIC_BOOM() { return wrapperContained.SONIC_BOOM; }
public byte START_DIGGING() { return wrapperContained.START_DIGGING; }
public byte PEEKING() { return wrapperContained.PEEKING; }
public byte BREAK_BODY() { return wrapperContained.BREAK_BODY; }

}