package yarnwrap.enchantment;
public class EnchantmentHelper { public net.minecraft.enchantment.EnchantmentHelper wrapperContained; public EnchantmentHelper(net.minecraft.enchantment.EnchantmentHelper wrapperContained) { this.wrapperContained = wrapperContained; }

public boolean canHaveEnchantments(yarnwrap.item.ItemStack stack) { return wrapperContained.canHaveEnchantments(stack.wrapperContained); }
public void set(yarnwrap.item.ItemStack stack,yarnwrap.component.type.ItemEnchantmentsComponent enchantments) { wrapperContained.set(stack.wrapperContained,enchantments.wrapperContained); }
public yarnwrap.component.type.ItemEnchantmentsComponent apply(yarnwrap.item.ItemStack stack,java.util.function.Consumer applier) { return new yarnwrap.component.type.ItemEnchantmentsComponent(wrapperContained.apply(stack.wrapperContained,applier)); }
public yarnwrap.component.type.ItemEnchantmentsComponent getEnchantments(yarnwrap.item.ItemStack stack) { return new yarnwrap.component.type.ItemEnchantmentsComponent(wrapperContained.getEnchantments(stack.wrapperContained)); }
// public yarnwrap.component.ComponentType getEnchantmentsComponentType(yarnwrap.item.ItemStack stack) { return new yarnwrap.component.ComponentType(wrapperContained.getEnchantmentsComponentType(stack.wrapperContained)); }
public boolean hasEnchantments(yarnwrap.item.ItemStack stack) { return wrapperContained.hasEnchantments(stack.wrapperContained); }
public void onTargetDamaged(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource) { wrapperContained.onTargetDamaged(world.wrapperContained,target.wrapperContained,damageSource.wrapperContained); }
public int getMobExperience(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity attacker,yarnwrap.entity.Entity mob,int baseMobExperience) { return wrapperContained.getMobExperience(world.wrapperContained,attacker.wrapperContained,mob.wrapperContained,baseMobExperience); }
public void applyLocationBasedEffects(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user) { wrapperContained.applyLocationBasedEffects(world.wrapperContained,user.wrapperContained); }
public boolean isInvulnerableTo(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user,yarnwrap.entity.damage.DamageSource damageSource) { return wrapperContained.isInvulnerableTo(world.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
public float getEquipmentDropChance(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity attacker,yarnwrap.entity.damage.DamageSource damageSource,float baseEquipmentDropChance) { return wrapperContained.getEquipmentDropChance(world.wrapperContained,attacker.wrapperContained,damageSource.wrapperContained,baseEquipmentDropChance); }
public int getItemDamage(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseItemDamage) { return wrapperContained.getItemDamage(world.wrapperContained,stack.wrapperContained,baseItemDamage); }
public float getProjectileSpread(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,float baseProjectileSpread) { return wrapperContained.getProjectileSpread(world.wrapperContained,stack.wrapperContained,user.wrapperContained,baseProjectileSpread); }
public int getProjectileCount(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,int baseProjectileCount) { return wrapperContained.getProjectileCount(world.wrapperContained,stack.wrapperContained,user.wrapperContained,baseProjectileCount); }
public float getDamage(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseDamage) { return wrapperContained.getDamage(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseDamage); }
public float getTridentSpinAttackStrength(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user) { return wrapperContained.getTridentSpinAttackStrength(stack.wrapperContained,user.wrapperContained); }
public void onHitBlock(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.Entity enchantedEntity,yarnwrap.entity.EquipmentSlot slot,yarnwrap.util.math.Vec3d pos,yarnwrap.block.BlockState state,java.util.function.Consumer onBreak) { wrapperContained.onHitBlock(world.wrapperContained,stack.wrapperContained,user.wrapperContained,enchantedEntity.wrapperContained,slot.wrapperContained,pos.wrapperContained,state.wrapperContained,onBreak); }
public void applyLocationBasedEffects(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.EquipmentSlot slot) { wrapperContained.applyLocationBasedEffects(world.wrapperContained,stack.wrapperContained,user.wrapperContained,slot.wrapperContained); }
public void onProjectileSpawned(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack weaponStack,yarnwrap.entity.projectile.PersistentProjectileEntity projectileEntity,java.util.function.Consumer onBreak) { wrapperContained.onProjectileSpawned(world.wrapperContained,weaponStack.wrapperContained,projectileEntity.wrapperContained,onBreak); }
public int getProjectilePiercing(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack weaponStack,yarnwrap.item.ItemStack projectileStack) { return wrapperContained.getProjectilePiercing(world.wrapperContained,weaponStack.wrapperContained,projectileStack.wrapperContained); }
public int getAmmoUse(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack rangedWeaponStack,yarnwrap.item.ItemStack projectileStack,int baseAmmoUse) { return wrapperContained.getAmmoUse(world.wrapperContained,rangedWeaponStack.wrapperContained,projectileStack.wrapperContained,baseAmmoUse); }
public yarnwrap.item.ItemStack enchant(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,yarnwrap.registry.DynamicRegistryManager dynamicRegistryManager,java.util.Optional enchantments) { return new yarnwrap.item.ItemStack(wrapperContained.enchant(random.wrapperContained,stack.wrapperContained,level,dynamicRegistryManager.wrapperContained,enchantments)); }
public void removeLocationBasedEffects(yarnwrap.entity.LivingEntity user) { wrapperContained.removeLocationBasedEffects(user.wrapperContained); }
public void applyEnchantmentProvider(yarnwrap.item.ItemStack stack,yarnwrap.registry.DynamicRegistryManager registryManager,yarnwrap.registry.RegistryKey providerKey,yarnwrap.world.LocalDifficulty localDifficulty,yarnwrap.util.math.random.Random random) { wrapperContained.applyEnchantmentProvider(stack.wrapperContained,registryManager.wrapperContained,providerKey.wrapperContained,localDifficulty.wrapperContained,random.wrapperContained); }
public boolean hasAnyEnchantmentsIn(yarnwrap.item.ItemStack stack,yarnwrap.registry.tag.TagKey tag) { return wrapperContained.hasAnyEnchantmentsIn(stack.wrapperContained,tag.wrapperContained); }
// public void forEachEnchantment(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,yarnwrap.entity.LivingEntity entity,Object contextAwareConsumer) { wrapperContained.forEachEnchantment(stack.wrapperContained,slot.wrapperContained,entity.wrapperContained,contextAwareConsumer); }
public void applyAttributeModifiers(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,java.util.function.BiConsumer attributeModifierConsumer) { wrapperContained.applyAttributeModifiers(stack.wrapperContained,slot.wrapperContained,attributeModifierConsumer); }
public void removeLocationBasedEffects(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.EquipmentSlot slot) { wrapperContained.removeLocationBasedEffects(stack.wrapperContained,user.wrapperContained,slot.wrapperContained); }
public boolean hasAnyEnchantmentsWith(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType) { return wrapperContained.hasAnyEnchantmentsWith(stack.wrapperContained,componentType.wrapperContained); }
public void onTick(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user) { wrapperContained.onTick(world.wrapperContained,user.wrapperContained); }
public int getBlockExperience(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseBlockExperience) { return wrapperContained.getBlockExperience(world.wrapperContained,stack.wrapperContained,baseBlockExperience); }
public float getFishingTimeReduction(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user) { return wrapperContained.getFishingTimeReduction(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
public float getCrossbowChargeTime(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,float baseCrossbowChargeTime) { return wrapperContained.getCrossbowChargeTime(stack.wrapperContained,user.wrapperContained,baseCrossbowChargeTime); }
public float getSmashDamagePerFallenBlock(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseSmashDamagePerFallenBlock) { return wrapperContained.getSmashDamagePerFallenBlock(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseSmashDamagePerFallenBlock); }
public java.util.Optional getEffect(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType) { return wrapperContained.getEffect(stack.wrapperContained,componentType.wrapperContained); }
public int getRepairWithXp(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseRepairWithXp) { return wrapperContained.getRepairWithXp(world.wrapperContained,stack.wrapperContained,baseRepairWithXp); }
public int getTridentReturnAcceleration(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user) { return wrapperContained.getTridentReturnAcceleration(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
public float getArmorEffectiveness(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,float baseArmorEffectiveness) { return wrapperContained.getArmorEffectiveness(world.wrapperContained,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,baseArmorEffectiveness); }
public com.mojang.datafixers.util.Pair getEffectListAndLevel(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType) { return wrapperContained.getEffectListAndLevel(stack.wrapperContained,componentType.wrapperContained); }
public float modifyKnockback(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseKnockback) { return wrapperContained.modifyKnockback(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseKnockback); }
public void onTargetDamaged(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,yarnwrap.item.ItemStack weapon) { wrapperContained.onTargetDamaged(world.wrapperContained,target.wrapperContained,damageSource.wrapperContained,weapon.wrapperContained); }
public void applyAttributeModifiers(yarnwrap.item.ItemStack stack,yarnwrap.component.type.AttributeModifierSlot slot,java.util.function.BiConsumer attributeModifierConsumer) { wrapperContained.applyAttributeModifiers(stack.wrapperContained,slot.wrapperContained,attributeModifierConsumer); }
public boolean isCompatible(java.util.Collection existing,yarnwrap.registry.entry.RegistryEntry candidate) { return wrapperContained.isCompatible(existing,candidate.wrapperContained); }
public int getEquipmentLevel(yarnwrap.registry.entry.RegistryEntry enchantment,yarnwrap.entity.LivingEntity entity) { return wrapperContained.getEquipmentLevel(enchantment.wrapperContained,entity.wrapperContained); }
public java.util.Optional chooseEquipmentWith(yarnwrap.component.ComponentType componentType,yarnwrap.entity.LivingEntity entity,java.util.function.Predicate stackPredicate) { return wrapperContained.chooseEquipmentWith(componentType.wrapperContained,entity.wrapperContained,stackPredicate); }
// public void forEachEnchantment(yarnwrap.entity.LivingEntity entity,Object contextAwareConsumer) { wrapperContained.forEachEnchantment(entity.wrapperContained,contextAwareConsumer); }
public float getProtectionAmount(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user,yarnwrap.entity.damage.DamageSource damageSource) { return wrapperContained.getProtectionAmount(world.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
// public void forEachEnchantment(yarnwrap.item.ItemStack stack,Object consumer) { wrapperContained.forEachEnchantment(stack.wrapperContained,consumer); }
public int getFishingLuckBonus(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user) { return wrapperContained.getFishingLuckBonus(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
public int getLevel(yarnwrap.registry.entry.RegistryEntry enchantment,yarnwrap.item.ItemStack stack) { return wrapperContained.getLevel(enchantment.wrapperContained,stack.wrapperContained); }
public int calculateRequiredExperienceLevel(yarnwrap.util.math.random.Random random,int slotIndex,int bookshelfCount,yarnwrap.item.ItemStack stack) { return wrapperContained.calculateRequiredExperienceLevel(random.wrapperContained,slotIndex,bookshelfCount,stack.wrapperContained); }
public java.util.List getPossibleEntries(int level,yarnwrap.item.ItemStack stack,java.util.stream.Stream possibleEnchantments) { return wrapperContained.getPossibleEntries(level,stack.wrapperContained,possibleEnchantments); }
public java.util.List generateEnchantments(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,java.util.stream.Stream possibleEnchantments) { return wrapperContained.generateEnchantments(random.wrapperContained,stack.wrapperContained,level,possibleEnchantments); }
public void removeConflicts(java.util.List possibleEntries,yarnwrap.enchantment.EnchantmentLevelEntry pickedEntry) { wrapperContained.removeConflicts(possibleEntries,pickedEntry.wrapperContained); }
public yarnwrap.item.ItemStack enchant(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,java.util.stream.Stream possibleEnchantments) { return new yarnwrap.item.ItemStack(wrapperContained.enchant(random.wrapperContained,stack.wrapperContained,level,possibleEnchantments)); }

}