package yarnwrap.enchantment;
public class EnchantmentHelper { public net.minecraft.enchantment.EnchantmentHelper wrapperContained; public EnchantmentHelper(net.minecraft.enchantment.EnchantmentHelper wrapperContained) { this.wrapperContained = wrapperContained; }

// public boolean canHaveEnchantments(yarnwrap.item.ItemStack stack) { return wrapperContained.canHaveEnchantments(stack.wrapperContained); }
// public static boolean canHaveEnchantments(yarnwrap.item.ItemStack stack, ) { return net.minecraft.enchantment.EnchantmentHelper.canHaveEnchantments(stack.wrapperContained); }
// public void set(yarnwrap.item.ItemStack stack,yarnwrap.component.type.ItemEnchantmentsComponent enchantments) { wrapperContained.set(stack.wrapperContained,enchantments.wrapperContained); }
// public static void set(yarnwrap.item.ItemStack stack,yarnwrap.component.type.ItemEnchantmentsComponent enchantments, ) { net.minecraft.enchantment.EnchantmentHelper.set(stack.wrapperContained,enchantments.wrapperContained); }
// public yarnwrap.component.type.ItemEnchantmentsComponent apply(yarnwrap.item.ItemStack stack,java.util.function.Consumer applier) { return new yarnwrap.component.type.ItemEnchantmentsComponent(wrapperContained.apply(stack.wrapperContained,applier)); }
// public static yarnwrap.component.type.ItemEnchantmentsComponent apply(yarnwrap.item.ItemStack stack,java.util.function.Consumer applier, ) { return new yarnwrap.component.type.ItemEnchantmentsComponent(net.minecraft.enchantment.EnchantmentHelper.apply(stack.wrapperContained,applier)); }
// public yarnwrap.component.type.ItemEnchantmentsComponent getEnchantments(yarnwrap.item.ItemStack stack) { return new yarnwrap.component.type.ItemEnchantmentsComponent(wrapperContained.getEnchantments(stack.wrapperContained)); }
// public static yarnwrap.component.type.ItemEnchantmentsComponent getEnchantments(yarnwrap.item.ItemStack stack, ) { return new yarnwrap.component.type.ItemEnchantmentsComponent(net.minecraft.enchantment.EnchantmentHelper.getEnchantments(stack.wrapperContained)); }
// public yarnwrap.component.ComponentType getEnchantmentsComponentType(yarnwrap.item.ItemStack stack) { return new yarnwrap.component.ComponentType(wrapperContained.getEnchantmentsComponentType(stack.wrapperContained)); }
// public static yarnwrap.component.ComponentType getEnchantmentsComponentType(yarnwrap.item.ItemStack stack, ) { return new yarnwrap.component.ComponentType(net.minecraft.enchantment.EnchantmentHelper.getEnchantmentsComponentType(stack.wrapperContained)); }
// public boolean hasEnchantments(yarnwrap.item.ItemStack stack) { return wrapperContained.hasEnchantments(stack.wrapperContained); }
// public static boolean hasEnchantments(yarnwrap.item.ItemStack stack, ) { return net.minecraft.enchantment.EnchantmentHelper.hasEnchantments(stack.wrapperContained); }
// public void method_60106(int enchantmentx) { wrapperContained.method_60106(enchantmentx); }
// public static void method_60106(int enchantmentx, ) { net.minecraft.enchantment.EnchantmentHelper.method_60106(enchantmentx); }
// public void onTargetDamaged(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource) { wrapperContained.onTargetDamaged(world.wrapperContained,target.wrapperContained,damageSource.wrapperContained); }
// public static void onTargetDamaged(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource, ) { net.minecraft.enchantment.EnchantmentHelper.onTargetDamaged(world.wrapperContained,target.wrapperContained,damageSource.wrapperContained); }
// public int getMobExperience(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity attacker,yarnwrap.entity.Entity mob,int baseMobExperience) { return wrapperContained.getMobExperience(world.wrapperContained,attacker.wrapperContained,mob.wrapperContained,baseMobExperience); }
// public static int getMobExperience(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity attacker,yarnwrap.entity.Entity mob,int baseMobExperience, ) { return net.minecraft.enchantment.EnchantmentHelper.getMobExperience(world.wrapperContained,attacker.wrapperContained,mob.wrapperContained,baseMobExperience); }
// public void method_60110(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.Entity level,org.apache.commons.lang3.mutable.MutableFloat context) { wrapperContained.method_60110(enchantment.wrapperContained,level.wrapperContained,context); }
// public static void method_60110(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.Entity level,org.apache.commons.lang3.mutable.MutableFloat context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60110(enchantment.wrapperContained,level.wrapperContained,context); }
// public void applyLocationBasedEffects(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user) { wrapperContained.applyLocationBasedEffects(world.wrapperContained,user.wrapperContained); }
// public static void applyLocationBasedEffects(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user, ) { net.minecraft.enchantment.EnchantmentHelper.applyLocationBasedEffects(world.wrapperContained,user.wrapperContained); }
// public boolean isInvulnerableTo(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user,yarnwrap.entity.damage.DamageSource damageSource) { return wrapperContained.isInvulnerableTo(world.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
// public static boolean isInvulnerableTo(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user,yarnwrap.entity.damage.DamageSource damageSource, ) { return net.minecraft.enchantment.EnchantmentHelper.isInvulnerableTo(world.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
// public float getEquipmentDropChance(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity attacker,yarnwrap.entity.damage.DamageSource damageSource,float baseEquipmentDropChance) { return wrapperContained.getEquipmentDropChance(world.wrapperContained,attacker.wrapperContained,damageSource.wrapperContained,baseEquipmentDropChance); }
// public static float getEquipmentDropChance(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity attacker,yarnwrap.entity.damage.DamageSource damageSource,float baseEquipmentDropChance, ) { return net.minecraft.enchantment.EnchantmentHelper.getEquipmentDropChance(world.wrapperContained,attacker.wrapperContained,damageSource.wrapperContained,baseEquipmentDropChance); }
// public void method_60114(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.entity.damage.DamageSource context) { wrapperContained.method_60114(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60114(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.entity.damage.DamageSource context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60114(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public void method_60115(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.entity.damage.DamageSource context) { wrapperContained.method_60115(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60115(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.entity.damage.DamageSource context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60115(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public void method_60116(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.registry.entry.RegistryEntry context) { wrapperContained.method_60116(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60116(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.registry.entry.RegistryEntry context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60116(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public int getItemDamage(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseItemDamage) { return wrapperContained.getItemDamage(world.wrapperContained,stack.wrapperContained,baseItemDamage); }
// public static int getItemDamage(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseItemDamage, ) { return net.minecraft.enchantment.EnchantmentHelper.getItemDamage(world.wrapperContained,stack.wrapperContained,baseItemDamage); }
// public float getProjectileSpread(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,float baseProjectileSpread) { return wrapperContained.getProjectileSpread(world.wrapperContained,stack.wrapperContained,user.wrapperContained,baseProjectileSpread); }
// public static float getProjectileSpread(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,float baseProjectileSpread, ) { return net.minecraft.enchantment.EnchantmentHelper.getProjectileSpread(world.wrapperContained,stack.wrapperContained,user.wrapperContained,baseProjectileSpread); }
// public int getProjectileCount(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,int baseProjectileCount) { return wrapperContained.getProjectileCount(world.wrapperContained,stack.wrapperContained,user.wrapperContained,baseProjectileCount); }
// public static int getProjectileCount(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,int baseProjectileCount, ) { return net.minecraft.enchantment.EnchantmentHelper.getProjectileCount(world.wrapperContained,stack.wrapperContained,user.wrapperContained,baseProjectileCount); }
// public float getDamage(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseDamage) { return wrapperContained.getDamage(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseDamage); }
// public static float getDamage(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseDamage, ) { return net.minecraft.enchantment.EnchantmentHelper.getDamage(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseDamage); }
// public void method_60121(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60121(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60121(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60121(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60122(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60122(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60122(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60122(enchantment.wrapperContained,level.wrapperContained); }
// public float getTridentSpinAttackStrength(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user) { return wrapperContained.getTridentSpinAttackStrength(stack.wrapperContained,user.wrapperContained); }
// public static float getTridentSpinAttackStrength(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user, ) { return net.minecraft.enchantment.EnchantmentHelper.getTridentSpinAttackStrength(stack.wrapperContained,user.wrapperContained); }
// public void onHitBlock(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.Entity enchantedEntity,yarnwrap.entity.EquipmentSlot slot,yarnwrap.util.math.Vec3d pos,yarnwrap.block.BlockState state,java.util.function.Consumer onBreak) { wrapperContained.onHitBlock(world.wrapperContained,stack.wrapperContained,user.wrapperContained,enchantedEntity.wrapperContained,slot.wrapperContained,pos.wrapperContained,state.wrapperContained,onBreak); }
// public static void onHitBlock(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.Entity enchantedEntity,yarnwrap.entity.EquipmentSlot slot,yarnwrap.util.math.Vec3d pos,yarnwrap.block.BlockState state,java.util.function.Consumer onBreak, ) { net.minecraft.enchantment.EnchantmentHelper.onHitBlock(world.wrapperContained,stack.wrapperContained,user.wrapperContained,enchantedEntity.wrapperContained,slot.wrapperContained,pos.wrapperContained,state.wrapperContained,onBreak); }
// public void applyLocationBasedEffects(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.EquipmentSlot slot) { wrapperContained.applyLocationBasedEffects(world.wrapperContained,stack.wrapperContained,user.wrapperContained,slot.wrapperContained); }
// public static void applyLocationBasedEffects(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.EquipmentSlot slot, ) { net.minecraft.enchantment.EnchantmentHelper.applyLocationBasedEffects(world.wrapperContained,stack.wrapperContained,user.wrapperContained,slot.wrapperContained); }
// public void method_60126(yarnwrap.entity.LivingEntity enchantment,org.apache.commons.lang3.mutable.MutableFloat level) { wrapperContained.method_60126(enchantment.wrapperContained,level); }
// public static void method_60126(yarnwrap.entity.LivingEntity enchantment,org.apache.commons.lang3.mutable.MutableFloat level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60126(enchantment.wrapperContained,level); }
// public void onProjectileSpawned(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack weaponStack,yarnwrap.entity.projectile.PersistentProjectileEntity projectileEntity,java.util.function.Consumer onBreak) { wrapperContained.onProjectileSpawned(world.wrapperContained,weaponStack.wrapperContained,projectileEntity.wrapperContained,onBreak); }
// public static void onProjectileSpawned(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack weaponStack,yarnwrap.entity.projectile.PersistentProjectileEntity projectileEntity,java.util.function.Consumer onBreak, ) { net.minecraft.enchantment.EnchantmentHelper.onProjectileSpawned(world.wrapperContained,weaponStack.wrapperContained,projectileEntity.wrapperContained,onBreak); }
// public int getProjectilePiercing(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack weaponStack,yarnwrap.item.ItemStack projectileStack) { return wrapperContained.getProjectilePiercing(world.wrapperContained,weaponStack.wrapperContained,projectileStack.wrapperContained); }
// public static int getProjectilePiercing(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack weaponStack,yarnwrap.item.ItemStack projectileStack, ) { return net.minecraft.enchantment.EnchantmentHelper.getProjectilePiercing(world.wrapperContained,weaponStack.wrapperContained,projectileStack.wrapperContained); }
// public int getAmmoUse(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack rangedWeaponStack,yarnwrap.item.ItemStack projectileStack,int baseAmmoUse) { return wrapperContained.getAmmoUse(world.wrapperContained,rangedWeaponStack.wrapperContained,projectileStack.wrapperContained,baseAmmoUse); }
// public static int getAmmoUse(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack rangedWeaponStack,yarnwrap.item.ItemStack projectileStack,int baseAmmoUse, ) { return net.minecraft.enchantment.EnchantmentHelper.getAmmoUse(world.wrapperContained,rangedWeaponStack.wrapperContained,projectileStack.wrapperContained,baseAmmoUse); }
// public void method_60130(yarnwrap.entity.LivingEntity enchantment,org.apache.commons.lang3.mutable.MutableFloat level) { wrapperContained.method_60130(enchantment.wrapperContained,level); }
// public static void method_60130(yarnwrap.entity.LivingEntity enchantment,org.apache.commons.lang3.mutable.MutableFloat level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60130(enchantment.wrapperContained,level); }
// public void method_60131(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.enchantment.EnchantmentEffectContext level) { wrapperContained.method_60131(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60131(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.enchantment.EnchantmentEffectContext level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60131(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60132(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.enchantment.EnchantmentEffectContext level) { wrapperContained.method_60132(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60132(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.enchantment.EnchantmentEffectContext level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60132(enchantment.wrapperContained,level.wrapperContained); }
// public yarnwrap.item.ItemStack enchant(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,yarnwrap.registry.DynamicRegistryManager dynamicRegistryManager,java.util.Optional enchantments) { return new yarnwrap.item.ItemStack(wrapperContained.enchant(random.wrapperContained,stack.wrapperContained,level,dynamicRegistryManager.wrapperContained,enchantments)); }
// public static yarnwrap.item.ItemStack enchant(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,yarnwrap.registry.DynamicRegistryManager dynamicRegistryManager,java.util.Optional enchantments, ) { return new yarnwrap.item.ItemStack(net.minecraft.enchantment.EnchantmentHelper.enchant(random.wrapperContained,stack.wrapperContained,level,dynamicRegistryManager.wrapperContained,enchantments)); }
// public void method_60134(yarnwrap.entity.EquipmentSlot enchantment,java.util.function.BiConsumer level) { wrapperContained.method_60134(enchantment.wrapperContained,level); }
// public static void method_60134(yarnwrap.entity.EquipmentSlot enchantment,java.util.function.BiConsumer level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60134(enchantment.wrapperContained,level); }
// public void removeLocationBasedEffects(yarnwrap.entity.LivingEntity user) { wrapperContained.removeLocationBasedEffects(user.wrapperContained); }
// public static void removeLocationBasedEffects(yarnwrap.entity.LivingEntity user, ) { net.minecraft.enchantment.EnchantmentHelper.removeLocationBasedEffects(user.wrapperContained); }
// public void method_60136(yarnwrap.entity.LivingEntity enchantment,yarnwrap.registry.entry.RegistryEntry level,int context) { wrapperContained.method_60136(enchantment.wrapperContained,level.wrapperContained,context); }
// public static void method_60136(yarnwrap.entity.LivingEntity enchantment,yarnwrap.registry.entry.RegistryEntry level,int context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60136(enchantment.wrapperContained,level.wrapperContained,context); }
// public void applyEnchantmentProvider(yarnwrap.item.ItemStack stack,yarnwrap.registry.DynamicRegistryManager registryManager,yarnwrap.registry.RegistryKey providerKey,yarnwrap.world.LocalDifficulty localDifficulty,yarnwrap.util.math.random.Random random) { wrapperContained.applyEnchantmentProvider(stack.wrapperContained,registryManager.wrapperContained,providerKey.wrapperContained,localDifficulty.wrapperContained,random.wrapperContained); }
// public static void applyEnchantmentProvider(yarnwrap.item.ItemStack stack,yarnwrap.registry.DynamicRegistryManager registryManager,yarnwrap.registry.RegistryKey providerKey,yarnwrap.world.LocalDifficulty localDifficulty,yarnwrap.util.math.random.Random random, ) { net.minecraft.enchantment.EnchantmentHelper.applyEnchantmentProvider(stack.wrapperContained,registryManager.wrapperContained,providerKey.wrapperContained,localDifficulty.wrapperContained,random.wrapperContained); }
// public boolean hasAnyEnchantmentsIn(yarnwrap.item.ItemStack stack,yarnwrap.registry.tag.TagKey tag) { return wrapperContained.hasAnyEnchantmentsIn(stack.wrapperContained,tag.wrapperContained); }
// public static boolean hasAnyEnchantmentsIn(yarnwrap.item.ItemStack stack,yarnwrap.registry.tag.TagKey tag, ) { return net.minecraft.enchantment.EnchantmentHelper.hasAnyEnchantmentsIn(stack.wrapperContained,tag.wrapperContained); }
// public void forEachEnchantment(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,yarnwrap.entity.LivingEntity entity,Object contextAwareConsumer) { wrapperContained.forEachEnchantment(stack.wrapperContained,slot.wrapperContained,entity.wrapperContained,contextAwareConsumer); }
// public static void forEachEnchantment(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,yarnwrap.entity.LivingEntity entity,Object contextAwareConsumer, ) { net.minecraft.enchantment.EnchantmentHelper.forEachEnchantment(stack.wrapperContained,slot.wrapperContained,entity.wrapperContained,contextAwareConsumer); }
// public void applyAttributeModifiers(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,java.util.function.BiConsumer attributeModifierConsumer) { wrapperContained.applyAttributeModifiers(stack.wrapperContained,slot.wrapperContained,attributeModifierConsumer); }
// public static void applyAttributeModifiers(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,java.util.function.BiConsumer attributeModifierConsumer, ) { net.minecraft.enchantment.EnchantmentHelper.applyAttributeModifiers(stack.wrapperContained,slot.wrapperContained,attributeModifierConsumer); }
// public void removeLocationBasedEffects(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.EquipmentSlot slot) { wrapperContained.removeLocationBasedEffects(stack.wrapperContained,user.wrapperContained,slot.wrapperContained); }
// public static void removeLocationBasedEffects(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,yarnwrap.entity.EquipmentSlot slot, ) { net.minecraft.enchantment.EnchantmentHelper.removeLocationBasedEffects(stack.wrapperContained,user.wrapperContained,slot.wrapperContained); }
// public boolean hasAnyEnchantmentsWith(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType) { return wrapperContained.hasAnyEnchantmentsWith(stack.wrapperContained,componentType.wrapperContained); }
// public static boolean hasAnyEnchantmentsWith(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType, ) { return net.minecraft.enchantment.EnchantmentHelper.hasAnyEnchantmentsWith(stack.wrapperContained,componentType.wrapperContained); }
// public boolean method_60143(yarnwrap.item.ItemStack enchantment) { return wrapperContained.method_60143(enchantment.wrapperContained); }
// public static boolean method_60143(yarnwrap.item.ItemStack enchantment, ) { return net.minecraft.enchantment.EnchantmentHelper.method_60143(enchantment.wrapperContained); }
// public boolean method_60144(yarnwrap.enchantment.EnchantmentLevelEntry entry) { return wrapperContained.method_60144(entry.wrapperContained); }
// public static boolean method_60144(yarnwrap.enchantment.EnchantmentLevelEntry entry, ) { return net.minecraft.enchantment.EnchantmentHelper.method_60144(entry.wrapperContained); }
// public void method_60145(yarnwrap.enchantment.provider.EnchantmentProvider componentBuilder) { wrapperContained.method_60145(componentBuilder.wrapperContained); }
// public static void method_60145(yarnwrap.enchantment.provider.EnchantmentProvider componentBuilder, ) { net.minecraft.enchantment.EnchantmentHelper.method_60145(componentBuilder.wrapperContained); }
// public void method_60146(yarnwrap.loot.context.LootContext effect) { wrapperContained.method_60146(effect.wrapperContained); }
// public static void method_60146(yarnwrap.loot.context.LootContext effect, ) { net.minecraft.enchantment.EnchantmentHelper.method_60146(effect.wrapperContained); }
// public void method_60148(yarnwrap.registry.entry.RegistryEntry effect) { wrapperContained.method_60148(effect.wrapperContained); }
// public static void method_60148(yarnwrap.registry.entry.RegistryEntry effect, ) { net.minecraft.enchantment.EnchantmentHelper.method_60148(effect.wrapperContained); }
// public void method_60150(yarnwrap.component.ComponentType enchantment,org.apache.commons.lang3.mutable.MutableBoolean level) { wrapperContained.method_60150(enchantment.wrapperContained,level); }
// public static void method_60150(yarnwrap.component.ComponentType enchantment,org.apache.commons.lang3.mutable.MutableBoolean level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60150(enchantment.wrapperContained,level); }
// public void method_60151(org.apache.commons.lang3.mutable.MutableBoolean enchantment,yarnwrap.server.world.ServerWorld level,yarnwrap.entity.LivingEntity context) { wrapperContained.method_60151(enchantment,level.wrapperContained,context.wrapperContained); }
// public static void method_60151(org.apache.commons.lang3.mutable.MutableBoolean enchantment,yarnwrap.server.world.ServerWorld level,yarnwrap.entity.LivingEntity context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60151(enchantment,level.wrapperContained,context.wrapperContained); }
// public void method_60152(org.apache.commons.lang3.mutable.MutableObject enchantment,yarnwrap.component.ComponentType level) { wrapperContained.method_60152(enchantment,level.wrapperContained); }
// public static void method_60152(org.apache.commons.lang3.mutable.MutableObject enchantment,yarnwrap.component.ComponentType level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60152(enchantment,level.wrapperContained); }
// public void onTick(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user) { wrapperContained.onTick(world.wrapperContained,user.wrapperContained); }
// public static void onTick(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user, ) { net.minecraft.enchantment.EnchantmentHelper.onTick(world.wrapperContained,user.wrapperContained); }
// public void method_60155(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.entity.damage.DamageSource context) { wrapperContained.method_60155(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60155(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.entity.damage.DamageSource context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60155(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public void method_60156(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.registry.entry.RegistryEntry context) { wrapperContained.method_60156(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60156(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.registry.entry.RegistryEntry context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60156(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public int getBlockExperience(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseBlockExperience) { return wrapperContained.getBlockExperience(world.wrapperContained,stack.wrapperContained,baseBlockExperience); }
// public static int getBlockExperience(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseBlockExperience, ) { return net.minecraft.enchantment.EnchantmentHelper.getBlockExperience(world.wrapperContained,stack.wrapperContained,baseBlockExperience); }
// public float getFishingTimeReduction(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user) { return wrapperContained.getFishingTimeReduction(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
// public static float getFishingTimeReduction(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user, ) { return net.minecraft.enchantment.EnchantmentHelper.getFishingTimeReduction(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
// public float getCrossbowChargeTime(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,float baseCrossbowChargeTime) { return wrapperContained.getCrossbowChargeTime(stack.wrapperContained,user.wrapperContained,baseCrossbowChargeTime); }
// public static float getCrossbowChargeTime(yarnwrap.item.ItemStack stack,yarnwrap.entity.LivingEntity user,float baseCrossbowChargeTime, ) { return net.minecraft.enchantment.EnchantmentHelper.getCrossbowChargeTime(stack.wrapperContained,user.wrapperContained,baseCrossbowChargeTime); }
// public float getSmashDamagePerFallenBlock(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseSmashDamagePerFallenBlock) { return wrapperContained.getSmashDamagePerFallenBlock(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseSmashDamagePerFallenBlock); }
// public static float getSmashDamagePerFallenBlock(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseSmashDamagePerFallenBlock, ) { return net.minecraft.enchantment.EnchantmentHelper.getSmashDamagePerFallenBlock(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseSmashDamagePerFallenBlock); }
// public void method_60161(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60161(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60161(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60161(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60162(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60162(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60162(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60162(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60163(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60163(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60163(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60163(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60164(yarnwrap.entity.LivingEntity enchantment,yarnwrap.registry.entry.RegistryEntry level,int context) { wrapperContained.method_60164(enchantment.wrapperContained,level.wrapperContained,context); }
// public static void method_60164(yarnwrap.entity.LivingEntity enchantment,yarnwrap.registry.entry.RegistryEntry level,int context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60164(enchantment.wrapperContained,level.wrapperContained,context); }
// public java.util.Optional getEffect(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType) { return wrapperContained.getEffect(stack.wrapperContained,componentType.wrapperContained); }
// public static java.util.Optional getEffect(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType, ) { return net.minecraft.enchantment.EnchantmentHelper.getEffect(stack.wrapperContained,componentType.wrapperContained); }
// public void method_60166(yarnwrap.loot.context.LootContext effect) { wrapperContained.method_60166(effect.wrapperContained); }
// public static void method_60166(yarnwrap.loot.context.LootContext effect, ) { net.minecraft.enchantment.EnchantmentHelper.method_60166(effect.wrapperContained); }
// public void method_60167(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.registry.entry.RegistryEntry context) { wrapperContained.method_60167(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60167(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.LivingEntity level,yarnwrap.registry.entry.RegistryEntry context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60167(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public int getRepairWithXp(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseRepairWithXp) { return wrapperContained.getRepairWithXp(world.wrapperContained,stack.wrapperContained,baseRepairWithXp); }
// public static int getRepairWithXp(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,int baseRepairWithXp, ) { return net.minecraft.enchantment.EnchantmentHelper.getRepairWithXp(world.wrapperContained,stack.wrapperContained,baseRepairWithXp); }
// public int getTridentReturnAcceleration(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user) { return wrapperContained.getTridentReturnAcceleration(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
// public static int getTridentReturnAcceleration(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user, ) { return net.minecraft.enchantment.EnchantmentHelper.getTridentReturnAcceleration(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
// public float getArmorEffectiveness(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,float baseArmorEffectiveness) { return wrapperContained.getArmorEffectiveness(world.wrapperContained,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,baseArmorEffectiveness); }
// public static float getArmorEffectiveness(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user,yarnwrap.entity.damage.DamageSource damageSource,float baseArmorEffectiveness, ) { return net.minecraft.enchantment.EnchantmentHelper.getArmorEffectiveness(world.wrapperContained,stack.wrapperContained,user.wrapperContained,damageSource.wrapperContained,baseArmorEffectiveness); }
// public void method_60171(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60171(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60171(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60171(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60172(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60172(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60172(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60172(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60173(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60173(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60173(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60173(enchantment.wrapperContained,level.wrapperContained); }
// public com.mojang.datafixers.util.Pair getEffectListAndLevel(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType) { return wrapperContained.getEffectListAndLevel(stack.wrapperContained,componentType.wrapperContained); }
// public static com.mojang.datafixers.util.Pair getEffectListAndLevel(yarnwrap.item.ItemStack stack,yarnwrap.component.ComponentType componentType, ) { return net.minecraft.enchantment.EnchantmentHelper.getEffectListAndLevel(stack.wrapperContained,componentType.wrapperContained); }
// public float modifyKnockback(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseKnockback) { return wrapperContained.modifyKnockback(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseKnockback); }
// public static float modifyKnockback(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,float baseKnockback, ) { return net.minecraft.enchantment.EnchantmentHelper.modifyKnockback(world.wrapperContained,stack.wrapperContained,target.wrapperContained,damageSource.wrapperContained,baseKnockback); }
// public void method_60176(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60176(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60176(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60176(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60177(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60177(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60177(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60177(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60178(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60178(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60178(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60178(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60179(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60179(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60179(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60179(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60180(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60180(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60180(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60180(enchantment.wrapperContained,level.wrapperContained); }
// public void method_60181(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level) { wrapperContained.method_60181(enchantment.wrapperContained,level.wrapperContained); }
// public static void method_60181(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.item.ItemStack level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60181(enchantment.wrapperContained,level.wrapperContained); }
// public void onTargetDamaged(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,yarnwrap.item.ItemStack weapon) { wrapperContained.onTargetDamaged(world.wrapperContained,target.wrapperContained,damageSource.wrapperContained,weapon.wrapperContained); }
// public static void onTargetDamaged(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.Entity target,yarnwrap.entity.damage.DamageSource damageSource,yarnwrap.item.ItemStack weapon, ) { net.minecraft.enchantment.EnchantmentHelper.onTargetDamaged(world.wrapperContained,target.wrapperContained,damageSource.wrapperContained,weapon.wrapperContained); }
// public void method_60620(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.Entity level,yarnwrap.entity.damage.DamageSource context) { wrapperContained.method_60620(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60620(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.Entity level,yarnwrap.entity.damage.DamageSource context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60620(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public void method_60621(yarnwrap.component.type.AttributeModifierSlot enchantment,java.util.function.BiConsumer level) { wrapperContained.method_60621(enchantment.wrapperContained,level); }
// public static void method_60621(yarnwrap.component.type.AttributeModifierSlot enchantment,java.util.function.BiConsumer level, ) { net.minecraft.enchantment.EnchantmentHelper.method_60621(enchantment.wrapperContained,level); }
// public void applyAttributeModifiers(yarnwrap.item.ItemStack stack,yarnwrap.component.type.AttributeModifierSlot slot,java.util.function.BiConsumer attributeModifierConsumer) { wrapperContained.applyAttributeModifiers(stack.wrapperContained,slot.wrapperContained,attributeModifierConsumer); }
// public static void applyAttributeModifiers(yarnwrap.item.ItemStack stack,yarnwrap.component.type.AttributeModifierSlot slot,java.util.function.BiConsumer attributeModifierConsumer, ) { net.minecraft.enchantment.EnchantmentHelper.applyAttributeModifiers(stack.wrapperContained,slot.wrapperContained,attributeModifierConsumer); }
// public void method_60623(yarnwrap.registry.entry.RegistryEntry effect) { wrapperContained.method_60623(effect.wrapperContained); }
// public static void method_60623(yarnwrap.registry.entry.RegistryEntry effect, ) { net.minecraft.enchantment.EnchantmentHelper.method_60623(effect.wrapperContained); }
// public void method_60624(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.Entity level,yarnwrap.entity.damage.DamageSource context) { wrapperContained.method_60624(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public static void method_60624(yarnwrap.server.world.ServerWorld enchantment,yarnwrap.entity.Entity level,yarnwrap.entity.damage.DamageSource context, ) { net.minecraft.enchantment.EnchantmentHelper.method_60624(enchantment.wrapperContained,level.wrapperContained,context.wrapperContained); }
// public boolean isCompatible(java.util.Collection existing,yarnwrap.registry.entry.RegistryEntry candidate) { return wrapperContained.isCompatible(existing,candidate.wrapperContained); }
// public static boolean isCompatible(java.util.Collection existing,yarnwrap.registry.entry.RegistryEntry candidate, ) { return net.minecraft.enchantment.EnchantmentHelper.isCompatible(existing,candidate.wrapperContained); }
// public int getEquipmentLevel(yarnwrap.registry.entry.RegistryEntry enchantment,yarnwrap.entity.LivingEntity entity) { return wrapperContained.getEquipmentLevel(enchantment.wrapperContained,entity.wrapperContained); }
// public static int getEquipmentLevel(yarnwrap.registry.entry.RegistryEntry enchantment,yarnwrap.entity.LivingEntity entity, ) { return net.minecraft.enchantment.EnchantmentHelper.getEquipmentLevel(enchantment.wrapperContained,entity.wrapperContained); }
// public java.util.Optional chooseEquipmentWith(yarnwrap.component.ComponentType componentType,yarnwrap.entity.LivingEntity entity,java.util.function.Predicate stackPredicate) { return wrapperContained.chooseEquipmentWith(componentType.wrapperContained,entity.wrapperContained,stackPredicate); }
// public static java.util.Optional chooseEquipmentWith(yarnwrap.component.ComponentType componentType,yarnwrap.entity.LivingEntity entity,java.util.function.Predicate stackPredicate, ) { return net.minecraft.enchantment.EnchantmentHelper.chooseEquipmentWith(componentType.wrapperContained,entity.wrapperContained,stackPredicate); }
// public void forEachEnchantment(yarnwrap.entity.LivingEntity entity,Object contextAwareConsumer) { wrapperContained.forEachEnchantment(entity.wrapperContained,contextAwareConsumer); }
// public static void forEachEnchantment(yarnwrap.entity.LivingEntity entity,Object contextAwareConsumer, ) { net.minecraft.enchantment.EnchantmentHelper.forEachEnchantment(entity.wrapperContained,contextAwareConsumer); }
// public float getProtectionAmount(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user,yarnwrap.entity.damage.DamageSource damageSource) { return wrapperContained.getProtectionAmount(world.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
// public static float getProtectionAmount(yarnwrap.server.world.ServerWorld world,yarnwrap.entity.LivingEntity user,yarnwrap.entity.damage.DamageSource damageSource, ) { return net.minecraft.enchantment.EnchantmentHelper.getProtectionAmount(world.wrapperContained,user.wrapperContained,damageSource.wrapperContained); }
// public void forEachEnchantment(yarnwrap.item.ItemStack stack,Object consumer) { wrapperContained.forEachEnchantment(stack.wrapperContained,consumer); }
// public static void forEachEnchantment(yarnwrap.item.ItemStack stack,Object consumer, ) { net.minecraft.enchantment.EnchantmentHelper.forEachEnchantment(stack.wrapperContained,consumer); }
// public int getFishingLuckBonus(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user) { return wrapperContained.getFishingLuckBonus(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
// public static int getFishingLuckBonus(yarnwrap.server.world.ServerWorld world,yarnwrap.item.ItemStack stack,yarnwrap.entity.Entity user, ) { return net.minecraft.enchantment.EnchantmentHelper.getFishingLuckBonus(world.wrapperContained,stack.wrapperContained,user.wrapperContained); }
// public int getLevel(yarnwrap.registry.entry.RegistryEntry enchantment,yarnwrap.item.ItemStack stack) { return wrapperContained.getLevel(enchantment.wrapperContained,stack.wrapperContained); }
// public static int getLevel(yarnwrap.registry.entry.RegistryEntry enchantment,yarnwrap.item.ItemStack stack, ) { return net.minecraft.enchantment.EnchantmentHelper.getLevel(enchantment.wrapperContained,stack.wrapperContained); }
// public int calculateRequiredExperienceLevel(yarnwrap.util.math.random.Random random,int slotIndex,int bookshelfCount,yarnwrap.item.ItemStack stack) { return wrapperContained.calculateRequiredExperienceLevel(random.wrapperContained,slotIndex,bookshelfCount,stack.wrapperContained); }
// public static int calculateRequiredExperienceLevel(yarnwrap.util.math.random.Random random,int slotIndex,int bookshelfCount,yarnwrap.item.ItemStack stack, ) { return net.minecraft.enchantment.EnchantmentHelper.calculateRequiredExperienceLevel(random.wrapperContained,slotIndex,bookshelfCount,stack.wrapperContained); }
// public java.util.List getPossibleEntries(int level,yarnwrap.item.ItemStack stack,java.util.stream.Stream possibleEnchantments) { return wrapperContained.getPossibleEntries(level,stack.wrapperContained,possibleEnchantments); }
// public static java.util.List getPossibleEntries(int level,yarnwrap.item.ItemStack stack,java.util.stream.Stream possibleEnchantments, ) { return net.minecraft.enchantment.EnchantmentHelper.getPossibleEntries(level,stack.wrapperContained,possibleEnchantments); }
// public java.util.List generateEnchantments(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,java.util.stream.Stream possibleEnchantments) { return wrapperContained.generateEnchantments(random.wrapperContained,stack.wrapperContained,level,possibleEnchantments); }
// public static java.util.List generateEnchantments(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,java.util.stream.Stream possibleEnchantments, ) { return net.minecraft.enchantment.EnchantmentHelper.generateEnchantments(random.wrapperContained,stack.wrapperContained,level,possibleEnchantments); }
// public void removeConflicts(java.util.List possibleEntries,yarnwrap.enchantment.EnchantmentLevelEntry pickedEntry) { wrapperContained.removeConflicts(possibleEntries,pickedEntry.wrapperContained); }
// public static void removeConflicts(java.util.List possibleEntries,yarnwrap.enchantment.EnchantmentLevelEntry pickedEntry, ) { net.minecraft.enchantment.EnchantmentHelper.removeConflicts(possibleEntries,pickedEntry.wrapperContained); }
// public yarnwrap.item.ItemStack enchant(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,java.util.stream.Stream possibleEnchantments) { return new yarnwrap.item.ItemStack(wrapperContained.enchant(random.wrapperContained,stack.wrapperContained,level,possibleEnchantments)); }
// public static yarnwrap.item.ItemStack enchant(yarnwrap.util.math.random.Random random,yarnwrap.item.ItemStack stack,int level,java.util.stream.Stream possibleEnchantments, ) { return new yarnwrap.item.ItemStack(net.minecraft.enchantment.EnchantmentHelper.enchant(random.wrapperContained,stack.wrapperContained,level,possibleEnchantments)); }

}