package yarnwrap.client.render.entity.feature;
public class ArmorFeatureRenderer { public net.minecraft.client.render.entity.feature.ArmorFeatureRenderer wrapperContained; public ArmorFeatureRenderer(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.client.texture.SpriteAtlasTexture armorTrimsAtlas() { return new yarnwrap.client.texture.SpriteAtlasTexture(wrapperContained.armorTrimsAtlas); }
// public void armorTrimsAtlas(yarnwrap.client.texture.SpriteAtlasTexture value) { wrapperContained.armorTrimsAtlas = value.wrapperContained; }
// public static yarnwrap.client.texture.SpriteAtlasTexture armorTrimsAtlas() { return new yarnwrap.client.texture.SpriteAtlasTexture(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.armorTrimsAtlas); }
// public static void armorTrimsAtlas(yarnwrap.client.texture.SpriteAtlasTexture value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.armorTrimsAtlas = value.wrapperContained; }

// public java.util.Map ARMOR_TEXTURE_CACHE() { return wrapperContained.ARMOR_TEXTURE_CACHE; }
// public void ARMOR_TEXTURE_CACHE(java.util.Map value) { wrapperContained.ARMOR_TEXTURE_CACHE = value; }
// public static java.util.Map ARMOR_TEXTURE_CACHE() { return net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.ARMOR_TEXTURE_CACHE; }
// public static void ARMOR_TEXTURE_CACHE(java.util.Map value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.ARMOR_TEXTURE_CACHE = value; }

// public yarnwrap.client.render.entity.model.BipedEntityModel innerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.innerModel); }
// public void innerModel(yarnwrap.client.render.entity.model.BipedEntityModel value) { wrapperContained.innerModel = value.wrapperContained; }
// public static yarnwrap.client.render.entity.model.BipedEntityModel innerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.innerModel); }
// public static void innerModel(yarnwrap.client.render.entity.model.BipedEntityModel value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.innerModel = value.wrapperContained; }

// public yarnwrap.client.render.entity.model.BipedEntityModel outerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.outerModel); }
// public void outerModel(yarnwrap.client.render.entity.model.BipedEntityModel value) { wrapperContained.outerModel = value.wrapperContained; }
// public static yarnwrap.client.render.entity.model.BipedEntityModel outerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.outerModel); }
// public static void outerModel(yarnwrap.client.render.entity.model.BipedEntityModel value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.outerModel = value.wrapperContained; }

public ArmorFeatureRenderer(yarnwrap.client.render.entity.feature.FeatureRendererContext context,yarnwrap.client.render.entity.model.BipedEntityModel innerModel,yarnwrap.client.render.entity.model.BipedEntityModel outerModel,yarnwrap.client.render.model.BakedModelManager bakery) { this.wrapperContained = new net.minecraft.client.render.entity.feature.ArmorFeatureRenderer(context.wrapperContained,innerModel.wrapperContained,outerModel.wrapperContained,bakery.wrapperContained); }
// public void renderArmorParts(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.model.BipedEntityModel model) { wrapperContained.renderArmorParts(matrices.wrapperContained,vertexConsumers.wrapperContained,light,model.wrapperContained); }
// public static void renderArmorParts(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.model.BipedEntityModel model, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmorParts(matrices.wrapperContained,vertexConsumers.wrapperContained,light,model.wrapperContained); }
// public void renderArmor(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.entity.LivingEntity entity,yarnwrap.entity.EquipmentSlot armorSlot,int light,yarnwrap.client.render.entity.model.BipedEntityModel model) { wrapperContained.renderArmor(matrices.wrapperContained,vertexConsumers.wrapperContained,entity.wrapperContained,armorSlot.wrapperContained,light,model.wrapperContained); }
// public static void renderArmor(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.entity.LivingEntity entity,yarnwrap.entity.EquipmentSlot armorSlot,int light,yarnwrap.client.render.entity.model.BipedEntityModel model, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmor(matrices.wrapperContained,vertexConsumers.wrapperContained,entity.wrapperContained,armorSlot.wrapperContained,light,model.wrapperContained); }
// public void setVisible(yarnwrap.client.render.entity.model.BipedEntityModel bipedModel,yarnwrap.entity.EquipmentSlot slot) { wrapperContained.setVisible(bipedModel.wrapperContained,slot.wrapperContained); }
// public static void setVisible(yarnwrap.client.render.entity.model.BipedEntityModel bipedModel,yarnwrap.entity.EquipmentSlot slot, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.setVisible(bipedModel.wrapperContained,slot.wrapperContained); }
// public yarnwrap.client.render.entity.model.BipedEntityModel getModel(yarnwrap.entity.EquipmentSlot slot) { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.getModel(slot.wrapperContained)); }
// public static yarnwrap.client.render.entity.model.BipedEntityModel getModel(yarnwrap.entity.EquipmentSlot slot, ) { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.getModel(slot.wrapperContained)); }
// public boolean usesInnerModel(yarnwrap.entity.EquipmentSlot slot) { return wrapperContained.usesInnerModel(slot.wrapperContained); }
// public static boolean usesInnerModel(yarnwrap.entity.EquipmentSlot slot, ) { return net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.usesInnerModel(slot.wrapperContained); }
// public void renderTrim(yarnwrap.registry.entry.RegistryEntry armorMaterial,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.item.trim.ArmorTrim trim,yarnwrap.client.render.entity.model.BipedEntityModel model,boolean leggings) { wrapperContained.renderTrim(armorMaterial.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,trim.wrapperContained,model.wrapperContained,leggings); }
// public static void renderTrim(yarnwrap.registry.entry.RegistryEntry armorMaterial,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.item.trim.ArmorTrim trim,yarnwrap.client.render.entity.model.BipedEntityModel model,boolean leggings, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderTrim(armorMaterial.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,trim.wrapperContained,model.wrapperContained,leggings); }
// public void renderGlint(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.model.BipedEntityModel model) { wrapperContained.renderGlint(matrices.wrapperContained,vertexConsumers.wrapperContained,light,model.wrapperContained); }
// public static void renderGlint(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.model.BipedEntityModel model, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderGlint(matrices.wrapperContained,vertexConsumers.wrapperContained,light,model.wrapperContained); }

}