package yarnwrap.client.render.entity.feature;
public class ArmorFeatureRenderer { public net.minecraft.client.render.entity.feature.ArmorFeatureRenderer wrapperContained; public ArmorFeatureRenderer(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.client.render.entity.model.BipedEntityModel innerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.innerModel); }
// public void innerModel(yarnwrap.client.render.entity.model.BipedEntityModel value) { wrapperContained.innerModel = value.wrapperContained; }
// public static yarnwrap.client.render.entity.model.BipedEntityModel innerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.innerModel); }
// public static void innerModel(yarnwrap.client.render.entity.model.BipedEntityModel value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.innerModel = value.wrapperContained; }

// public yarnwrap.client.render.entity.model.BipedEntityModel outerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.outerModel); }
// public void outerModel(yarnwrap.client.render.entity.model.BipedEntityModel value) { wrapperContained.outerModel = value.wrapperContained; }
// public static yarnwrap.client.render.entity.model.BipedEntityModel outerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.outerModel); }
// public static void outerModel(yarnwrap.client.render.entity.model.BipedEntityModel value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.outerModel = value.wrapperContained; }

// public yarnwrap.client.render.entity.model.BipedEntityModel babyInnerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.babyInnerModel); }
// public void babyInnerModel(yarnwrap.client.render.entity.model.BipedEntityModel value) { wrapperContained.babyInnerModel = value.wrapperContained; }
// public static yarnwrap.client.render.entity.model.BipedEntityModel babyInnerModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.babyInnerModel); }
// public static void babyInnerModel(yarnwrap.client.render.entity.model.BipedEntityModel value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.babyInnerModel = value.wrapperContained; }

// public yarnwrap.client.render.entity.model.BipedEntityModel babyOuterModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.babyOuterModel); }
// public void babyOuterModel(yarnwrap.client.render.entity.model.BipedEntityModel value) { wrapperContained.babyOuterModel = value.wrapperContained; }
// public static yarnwrap.client.render.entity.model.BipedEntityModel babyOuterModel() { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.babyOuterModel); }
// public static void babyOuterModel(yarnwrap.client.render.entity.model.BipedEntityModel value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.babyOuterModel = value.wrapperContained; }

// public yarnwrap.client.render.entity.equipment.EquipmentRenderer equipmentRenderer() { return new yarnwrap.client.render.entity.equipment.EquipmentRenderer(wrapperContained.equipmentRenderer); }
// public void equipmentRenderer(yarnwrap.client.render.entity.equipment.EquipmentRenderer value) { wrapperContained.equipmentRenderer = value.wrapperContained; }
// public static yarnwrap.client.render.entity.equipment.EquipmentRenderer equipmentRenderer() { return new yarnwrap.client.render.entity.equipment.EquipmentRenderer(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.equipmentRenderer); }
// public static void equipmentRenderer(yarnwrap.client.render.entity.equipment.EquipmentRenderer value, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.equipmentRenderer = value.wrapperContained; }

public ArmorFeatureRenderer(yarnwrap.client.render.entity.feature.FeatureRendererContext context,yarnwrap.client.render.entity.model.BipedEntityModel innerModel,yarnwrap.client.render.entity.model.BipedEntityModel outerModel,yarnwrap.client.render.entity.model.BipedEntityModel babyInnerModel,yarnwrap.client.render.entity.model.BipedEntityModel babyOuterModel,yarnwrap.client.render.entity.equipment.EquipmentRenderer equipmentRenderer) { this.wrapperContained = new net.minecraft.client.render.entity.feature.ArmorFeatureRenderer(context.wrapperContained,innerModel.wrapperContained,outerModel.wrapperContained,babyInnerModel.wrapperContained,babyOuterModel.wrapperContained,equipmentRenderer.wrapperContained); }
public ArmorFeatureRenderer(yarnwrap.client.render.entity.feature.FeatureRendererContext context,yarnwrap.client.render.entity.model.BipedEntityModel innerModel,yarnwrap.client.render.entity.model.BipedEntityModel outerModel,yarnwrap.client.render.entity.equipment.EquipmentRenderer equipmentRenderer) { this.wrapperContained = new net.minecraft.client.render.entity.feature.ArmorFeatureRenderer(context.wrapperContained,innerModel.wrapperContained,outerModel.wrapperContained,equipmentRenderer.wrapperContained); }
// public void renderArmor(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,int light,yarnwrap.client.render.entity.model.BipedEntityModel armorModel) { wrapperContained.renderArmor(matrices.wrapperContained,vertexConsumers.wrapperContained,stack.wrapperContained,slot.wrapperContained,light,armorModel.wrapperContained); }
// public static void renderArmor(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot,int light,yarnwrap.client.render.entity.model.BipedEntityModel armorModel, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmor(matrices.wrapperContained,vertexConsumers.wrapperContained,stack.wrapperContained,slot.wrapperContained,light,armorModel.wrapperContained); }
// public void setVisible(yarnwrap.client.render.entity.model.BipedEntityModel bipedModel,yarnwrap.entity.EquipmentSlot slot) { wrapperContained.setVisible(bipedModel.wrapperContained,slot.wrapperContained); }
// public static void setVisible(yarnwrap.client.render.entity.model.BipedEntityModel bipedModel,yarnwrap.entity.EquipmentSlot slot, ) { net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.setVisible(bipedModel.wrapperContained,slot.wrapperContained); }
// public yarnwrap.client.render.entity.model.BipedEntityModel getModel(yarnwrap.client.render.entity.state.BipedEntityRenderState state,yarnwrap.entity.EquipmentSlot slot) { return new yarnwrap.client.render.entity.model.BipedEntityModel(wrapperContained.getModel(state.wrapperContained,slot.wrapperContained)); }
// public static yarnwrap.client.render.entity.model.BipedEntityModel getModel(yarnwrap.client.render.entity.state.BipedEntityRenderState state,yarnwrap.entity.EquipmentSlot slot, ) { return new yarnwrap.client.render.entity.model.BipedEntityModel(net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.getModel(state.wrapperContained,slot.wrapperContained)); }
// public boolean usesInnerModel(yarnwrap.entity.EquipmentSlot slot) { return wrapperContained.usesInnerModel(slot.wrapperContained); }
// public static boolean usesInnerModel(yarnwrap.entity.EquipmentSlot slot, ) { return net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.usesInnerModel(slot.wrapperContained); }
// public boolean hasModel(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot) { return wrapperContained.hasModel(stack.wrapperContained,slot.wrapperContained); }
// public static boolean hasModel(yarnwrap.item.ItemStack stack,yarnwrap.entity.EquipmentSlot slot, ) { return net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.hasModel(stack.wrapperContained,slot.wrapperContained); }
// public boolean hasModel(yarnwrap.component.type.EquippableComponent component,yarnwrap.entity.EquipmentSlot slot) { return wrapperContained.hasModel(component.wrapperContained,slot.wrapperContained); }
// public static boolean hasModel(yarnwrap.component.type.EquippableComponent component,yarnwrap.entity.EquipmentSlot slot, ) { return net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.hasModel(component.wrapperContained,slot.wrapperContained); }

}