package yarnwrap.client.render.entity.feature;
public class FeatureRenderer { public net.minecraft.client.render.entity.feature.FeatureRenderer wrapperContained; public FeatureRenderer(net.minecraft.client.render.entity.feature.FeatureRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.client.render.entity.feature.FeatureRendererContext context() { return new yarnwrap.client.render.entity.feature.FeatureRendererContext(wrapperContained.context); }
// public void context(yarnwrap.client.render.entity.feature.FeatureRendererContext value) { wrapperContained.context = value.wrapperContained; }
// public static yarnwrap.client.render.entity.feature.FeatureRendererContext context() { return new yarnwrap.client.render.entity.feature.FeatureRendererContext(net.minecraft.client.render.entity.feature.FeatureRenderer.context); }
// public static void context(yarnwrap.client.render.entity.feature.FeatureRendererContext value, ) { net.minecraft.client.render.entity.feature.FeatureRenderer.context = value.wrapperContained; }

// public FeatureRenderer(yarnwrap.client.render.entity.feature.FeatureRendererContext context) { this.wrapperContained = new net.minecraft.client.render.entity.feature.FeatureRenderer(context.wrapperContained); }
public void render(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.state.EntityRenderState state,float limbAngle,float limbDistance) { wrapperContained.render(matrices.wrapperContained,vertexConsumers.wrapperContained,light,state.wrapperContained,limbAngle,limbDistance); }
// public static void render(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.state.EntityRenderState state,float limbAngle,float limbDistance, ) { net.minecraft.client.render.entity.feature.FeatureRenderer.render(matrices.wrapperContained,vertexConsumers.wrapperContained,light,state.wrapperContained,limbAngle,limbDistance); }
public yarnwrap.client.render.entity.model.EntityModel getContextModel() { return new yarnwrap.client.render.entity.model.EntityModel(wrapperContained.getContextModel()); }
// public static yarnwrap.client.render.entity.model.EntityModel getContextModel() { return new yarnwrap.client.render.entity.model.EntityModel(net.minecraft.client.render.entity.feature.FeatureRenderer.getContextModel()); }
// public void render(yarnwrap.client.render.entity.model.EntityModel contextModel,yarnwrap.util.Identifier texture,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.state.LivingEntityRenderState state,int color) { wrapperContained.render(contextModel.wrapperContained,texture.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,state.wrapperContained,color); }
// public static void render(yarnwrap.client.render.entity.model.EntityModel contextModel,yarnwrap.util.Identifier texture,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.state.LivingEntityRenderState state,int color, ) { net.minecraft.client.render.entity.feature.FeatureRenderer.render(contextModel.wrapperContained,texture.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,state.wrapperContained,color); }
// public void renderModel(yarnwrap.client.render.entity.model.EntityModel model,yarnwrap.util.Identifier texture,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.state.LivingEntityRenderState state,int color) { wrapperContained.renderModel(model.wrapperContained,texture.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,state.wrapperContained,color); }
// public static void renderModel(yarnwrap.client.render.entity.model.EntityModel model,yarnwrap.util.Identifier texture,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,yarnwrap.client.render.entity.state.LivingEntityRenderState state,int color, ) { net.minecraft.client.render.entity.feature.FeatureRenderer.renderModel(model.wrapperContained,texture.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,state.wrapperContained,color); }

}