package yarnwrap.client.render.entity.model;
public class EntityModelPartNames { public net.minecraft.client.render.entity.model.EntityModelPartNames wrapperContained; public EntityModelPartNames(net.minecraft.client.render.entity.model.EntityModelPartNames wrapperContained) { this.wrapperContained = wrapperContained; }

public java.lang.String RIGHT_FRONT_FOOT() { return wrapperContained.RIGHT_FRONT_FOOT; }
public java.lang.String LEFT_HIND_LEG_TIP() { return wrapperContained.LEFT_HIND_LEG_TIP; }
public java.lang.String RIGHT_HIND_LEG_TIP() { return wrapperContained.RIGHT_HIND_LEG_TIP; }
public java.lang.String LEFT_FRONT_LEG_TIP() { return wrapperContained.LEFT_FRONT_LEG_TIP; }
public java.lang.String RIGHT_FRONT_LEG_TIP() { return wrapperContained.RIGHT_FRONT_LEG_TIP; }
public java.lang.String LEFT_LID() { return wrapperContained.LEFT_LID; }
public java.lang.String RIGHT_LID() { return wrapperContained.RIGHT_LID; }
public java.lang.String LEFT_CHEST() { return wrapperContained.LEFT_CHEST; }
public java.lang.String RIGHT_CHEST() { return wrapperContained.RIGHT_CHEST; }
public java.lang.String LEFT_HORN() { return wrapperContained.LEFT_HORN; }
public java.lang.String RIGHT_HORN() { return wrapperContained.RIGHT_HORN; }
public java.lang.String LEFT_EYE() { return wrapperContained.LEFT_EYE; }
public java.lang.String RIGHT_EYE() { return wrapperContained.RIGHT_EYE; }
public java.lang.String JAW() { return wrapperContained.JAW; }
public java.lang.String NOSE() { return wrapperContained.NOSE; }
public java.lang.String ARMS() { return wrapperContained.ARMS; }
public java.lang.String TAIL() { return wrapperContained.TAIL; }
public java.lang.String CUBE() { return wrapperContained.CUBE; }
public java.lang.String BEAK() { return wrapperContained.BEAK; }
public java.lang.String BACK_FIN() { return wrapperContained.BACK_FIN; }
public java.lang.String MANE() { return wrapperContained.MANE; }
public java.lang.String NECK() { return wrapperContained.NECK; }
public java.lang.String MOUTH() { return wrapperContained.MOUTH; }
public java.lang.String HEAD() { return wrapperContained.HEAD; }
public java.lang.String HAT() { return wrapperContained.HAT; }
public java.lang.String BODY() { return wrapperContained.BODY; }
public java.lang.String LEFT_FIN() { return wrapperContained.LEFT_FIN; }
public java.lang.String HAT_RIM() { return wrapperContained.HAT_RIM; }
public java.lang.String JACKET() { return wrapperContained.JACKET; }
public java.lang.String TOP_GILLS() { return wrapperContained.TOP_GILLS; }
public java.lang.String LEFT_GILLS() { return wrapperContained.LEFT_GILLS; }
public java.lang.String RIGHT_GILLS() { return wrapperContained.RIGHT_GILLS; }
public java.lang.String RIGHT_FIN() { return wrapperContained.RIGHT_FIN; }
public java.lang.String TOP_FIN() { return wrapperContained.TOP_FIN; }
public java.lang.String BOTTOM_FIN() { return wrapperContained.BOTTOM_FIN; }
public java.lang.String TAIL_FIN() { return wrapperContained.TAIL_FIN; }
public java.lang.String LEFT_BLUE_FIN() { return wrapperContained.LEFT_BLUE_FIN; }
public java.lang.String RIGHT_BLUE_FIN() { return wrapperContained.RIGHT_BLUE_FIN; }
public java.lang.String LEFT_ARM() { return wrapperContained.LEFT_ARM; }
public java.lang.String RIGHT_ARM() { return wrapperContained.RIGHT_ARM; }
public java.lang.String LEFT_WING() { return wrapperContained.LEFT_WING; }
public java.lang.String RIGHT_WING() { return wrapperContained.RIGHT_WING; }
public java.lang.String LEFT_WING_BASE() { return wrapperContained.LEFT_WING_BASE; }
public java.lang.String RIGHT_WING_BASE() { return wrapperContained.RIGHT_WING_BASE; }
public java.lang.String LEFT_WING_TIP() { return wrapperContained.LEFT_WING_TIP; }
public java.lang.String RIGHT_WING_TIP() { return wrapperContained.RIGHT_WING_TIP; }
public java.lang.String LEFT_EAR() { return wrapperContained.LEFT_EAR; }
public java.lang.String RIGHT_EAR() { return wrapperContained.RIGHT_EAR; }
public java.lang.String LEFT_LEG() { return wrapperContained.LEFT_LEG; }
public java.lang.String RIGHT_LEG() { return wrapperContained.RIGHT_LEG; }
public java.lang.String LEFT_HIND_LEG() { return wrapperContained.LEFT_HIND_LEG; }
public java.lang.String RIGHT_HIND_LEG() { return wrapperContained.RIGHT_HIND_LEG; }
public java.lang.String LEFT_FRONT_LEG() { return wrapperContained.LEFT_FRONT_LEG; }
public java.lang.String RIGHT_FRONT_LEG() { return wrapperContained.RIGHT_FRONT_LEG; }
public java.lang.String LEFT_HIND_FOOT() { return wrapperContained.LEFT_HIND_FOOT; }
public java.lang.String RIGHT_HIND_FOOT() { return wrapperContained.RIGHT_HIND_FOOT; }
public java.lang.String LEFT_FRONT_FOOT() { return wrapperContained.LEFT_FRONT_FOOT; }
public java.lang.String ROOT() { return wrapperContained.ROOT; }
public java.lang.String CROAKING_BODY() { return wrapperContained.CROAKING_BODY; }
public java.lang.String TONGUE() { return wrapperContained.TONGUE; }
public java.lang.String TONGUE_RL() { return wrapperContained.TONGUE_RL; }
public java.lang.String LEFT_HAND() { return wrapperContained.LEFT_HAND; }
public java.lang.String RIGHT_HAND() { return wrapperContained.RIGHT_HAND; }
public java.lang.String LEFT_FOOT() { return wrapperContained.LEFT_FOOT; }
public java.lang.String RIGHT_FOOT() { return wrapperContained.RIGHT_FOOT; }
public java.lang.String EYES() { return wrapperContained.EYES; }
public java.lang.String RIGHT_TENDRIL() { return wrapperContained.RIGHT_TENDRIL; }
public java.lang.String LEFT_TENDRIL() { return wrapperContained.LEFT_TENDRIL; }
public java.lang.String BONE() { return wrapperContained.BONE; }
public java.lang.String RIGHT_RIBCAGE() { return wrapperContained.RIGHT_RIBCAGE; }
public java.lang.String LEFT_RIBCAGE() { return wrapperContained.LEFT_RIBCAGE; }
public java.lang.String LEFT_MID_LEG() { return wrapperContained.LEFT_MID_LEG; }
public java.lang.String RIGHT_MID_LEG() { return wrapperContained.RIGHT_MID_LEG; }
public java.lang.String FEET() { return wrapperContained.FEET; }
public java.lang.String WIND_BODY() { return wrapperContained.WIND_BODY; }
public java.lang.String WIND_TOP() { return wrapperContained.WIND_TOP; }
public java.lang.String WIND_MID() { return wrapperContained.WIND_MID; }
public java.lang.String WIND_BOTTOM() { return wrapperContained.WIND_BOTTOM; }
public java.lang.String RODS() { return wrapperContained.RODS; }
public java.lang.String MUSHROOMS() { return wrapperContained.MUSHROOMS; }

}