package yarnwrap.client.render;
public class RenderPhase { public net.minecraft.client.render.RenderPhase wrapperContained; public RenderPhase(net.minecraft.client.render.RenderPhase wrapperContained) { this.wrapperContained = wrapperContained; }

// public Object ENABLE_CULLING() { return wrapperContained.ENABLE_CULLING; }
// public Object DISABLE_CULLING() { return wrapperContained.DISABLE_CULLING; }
// public Object ALWAYS_DEPTH_TEST() { return wrapperContained.ALWAYS_DEPTH_TEST; }
// public Object EQUAL_DEPTH_TEST() { return wrapperContained.EQUAL_DEPTH_TEST; }
// public Object LEQUAL_DEPTH_TEST() { return wrapperContained.LEQUAL_DEPTH_TEST; }
// public Object ALL_MASK() { return wrapperContained.ALL_MASK; }
// public Object COLOR_MASK() { return wrapperContained.COLOR_MASK; }
// public Object DEPTH_MASK() { return wrapperContained.DEPTH_MASK; }
// public Object NO_LAYERING() { return wrapperContained.NO_LAYERING; }
// public Object POLYGON_OFFSET_LAYERING() { return wrapperContained.POLYGON_OFFSET_LAYERING; }
// public Object MAIN_TARGET() { return wrapperContained.MAIN_TARGET; }
// public Object OUTLINE_TARGET() { return wrapperContained.OUTLINE_TARGET; }
// public Object FULL_LINE_WIDTH() { return wrapperContained.FULL_LINE_WIDTH; }
// public java.lang.Runnable beginAction() { return wrapperContained.beginAction; }
// public java.lang.Runnable endAction() { return wrapperContained.endAction; }
// public java.lang.String name() { return wrapperContained.name; }
// public Object NO_TRANSPARENCY() { return wrapperContained.NO_TRANSPARENCY; }
// public Object ADDITIVE_TRANSPARENCY() { return wrapperContained.ADDITIVE_TRANSPARENCY; }
// public Object LIGHTNING_TRANSPARENCY() { return wrapperContained.LIGHTNING_TRANSPARENCY; }
// public Object GLINT_TRANSPARENCY() { return wrapperContained.GLINT_TRANSPARENCY; }
// public Object CRUMBLING_TRANSPARENCY() { return wrapperContained.CRUMBLING_TRANSPARENCY; }
// public Object TRANSLUCENT_TRANSPARENCY() { return wrapperContained.TRANSLUCENT_TRANSPARENCY; }
// public Object MIPMAP_BLOCK_ATLAS_TEXTURE() { return wrapperContained.MIPMAP_BLOCK_ATLAS_TEXTURE; }
// public Object BLOCK_ATLAS_TEXTURE() { return wrapperContained.BLOCK_ATLAS_TEXTURE; }
// public Object NO_TEXTURE() { return wrapperContained.NO_TEXTURE; }
// public Object DEFAULT_TEXTURING() { return wrapperContained.DEFAULT_TEXTURING; }
// public Object GLINT_TEXTURING() { return wrapperContained.GLINT_TEXTURING; }
// public Object ENTITY_GLINT_TEXTURING() { return wrapperContained.ENTITY_GLINT_TEXTURING; }
// public Object ENABLE_LIGHTMAP() { return wrapperContained.ENABLE_LIGHTMAP; }
// public Object DISABLE_LIGHTMAP() { return wrapperContained.DISABLE_LIGHTMAP; }
// public Object ENABLE_OVERLAY_COLOR() { return wrapperContained.ENABLE_OVERLAY_COLOR; }
// public Object DISABLE_OVERLAY_COLOR() { return wrapperContained.DISABLE_OVERLAY_COLOR; }
// public Object VIEW_OFFSET_Z_LAYERING() { return wrapperContained.VIEW_OFFSET_Z_LAYERING; }
// public Object TRANSLUCENT_TARGET() { return wrapperContained.TRANSLUCENT_TARGET; }
// public Object PARTICLES_TARGET() { return wrapperContained.PARTICLES_TARGET; }
// public Object WEATHER_TARGET() { return wrapperContained.WEATHER_TARGET; }
// public Object CLOUDS_TARGET() { return wrapperContained.CLOUDS_TARGET; }
// public Object ITEM_ENTITY_TARGET() { return wrapperContained.ITEM_ENTITY_TARGET; }
// public Object ENTITY_CUTOUT_NONULL_OFFSET_Z_PROGRAM() { return wrapperContained.ENTITY_CUTOUT_NONULL_OFFSET_Z_PROGRAM; }
// public Object ITEM_ENTITY_TRANSLUCENT_CULL_PROGRAM() { return wrapperContained.ITEM_ENTITY_TRANSLUCENT_CULL_PROGRAM; }
// public Object ENTITY_TRANSLUCENT_CULL_PROGRAM() { return wrapperContained.ENTITY_TRANSLUCENT_CULL_PROGRAM; }
// public Object ENTITY_TRANSLUCENT_PROGRAM() { return wrapperContained.ENTITY_TRANSLUCENT_PROGRAM; }
// public Object ENTITY_SMOOTH_CUTOUT_PROGRAM() { return wrapperContained.ENTITY_SMOOTH_CUTOUT_PROGRAM; }
// public Object BEACON_BEAM_PROGRAM() { return wrapperContained.BEACON_BEAM_PROGRAM; }
// public Object ENTITY_DECAL_PROGRAM() { return wrapperContained.ENTITY_DECAL_PROGRAM; }
// public Object ENTITY_NO_OUTLINE_PROGRAM() { return wrapperContained.ENTITY_NO_OUTLINE_PROGRAM; }
// public Object ENTITY_SHADOW_PROGRAM() { return wrapperContained.ENTITY_SHADOW_PROGRAM; }
// public Object ENTITY_ALPHA_PROGRAM() { return wrapperContained.ENTITY_ALPHA_PROGRAM; }
// public Object EYES_PROGRAM() { return wrapperContained.EYES_PROGRAM; }
// public Object ENERGY_SWIRL_PROGRAM() { return wrapperContained.ENERGY_SWIRL_PROGRAM; }
// public Object LEASH_PROGRAM() { return wrapperContained.LEASH_PROGRAM; }
// public Object WATER_MASK_PROGRAM() { return wrapperContained.WATER_MASK_PROGRAM; }
// public Object OUTLINE_PROGRAM() { return wrapperContained.OUTLINE_PROGRAM; }
// public Object ARMOR_ENTITY_GLINT_PROGRAM() { return wrapperContained.ARMOR_ENTITY_GLINT_PROGRAM; }
// public Object TRANSLUCENT_GLINT_PROGRAM() { return wrapperContained.TRANSLUCENT_GLINT_PROGRAM; }
// public Object GLINT_PROGRAM() { return wrapperContained.GLINT_PROGRAM; }
// public Object ENTITY_GLINT_PROGRAM() { return wrapperContained.ENTITY_GLINT_PROGRAM; }
// public Object DIRECT_ENTITY_GLINT_PROGRAM() { return wrapperContained.DIRECT_ENTITY_GLINT_PROGRAM; }
// public Object CRUMBLING_PROGRAM() { return wrapperContained.CRUMBLING_PROGRAM; }
// public Object TEXT_PROGRAM() { return wrapperContained.TEXT_PROGRAM; }
// public Object TRANSPARENT_TEXT_PROGRAM() { return wrapperContained.TRANSPARENT_TEXT_PROGRAM; }
// public Object LIGHTNING_PROGRAM() { return wrapperContained.LIGHTNING_PROGRAM; }
// public Object TRIPWIRE_PROGRAM() { return wrapperContained.TRIPWIRE_PROGRAM; }
// public Object END_PORTAL_PROGRAM() { return wrapperContained.END_PORTAL_PROGRAM; }
// public Object END_GATEWAY_PROGRAM() { return wrapperContained.END_GATEWAY_PROGRAM; }
// public Object LINES_PROGRAM() { return wrapperContained.LINES_PROGRAM; }
// public Object NO_PROGRAM() { return wrapperContained.NO_PROGRAM; }
// public Object POSITION_COLOR_LIGHTMAP_PROGRAM() { return wrapperContained.POSITION_COLOR_LIGHTMAP_PROGRAM; }
// public Object POSITION_PROGRAM() { return wrapperContained.POSITION_PROGRAM; }
// public Object POSITION_TEXTURE_PROGRAM() { return wrapperContained.POSITION_TEXTURE_PROGRAM; }
// public Object POSITION_COLOR_TEXTURE_LIGHTMAP_PROGRAM() { return wrapperContained.POSITION_COLOR_TEXTURE_LIGHTMAP_PROGRAM; }
// public Object COLOR_PROGRAM() { return wrapperContained.COLOR_PROGRAM; }
// public Object SOLID_PROGRAM() { return wrapperContained.SOLID_PROGRAM; }
// public Object CUTOUT_MIPPED_PROGRAM() { return wrapperContained.CUTOUT_MIPPED_PROGRAM; }
// public Object CUTOUT_PROGRAM() { return wrapperContained.CUTOUT_PROGRAM; }
// public Object TRANSLUCENT_PROGRAM() { return wrapperContained.TRANSLUCENT_PROGRAM; }
// public Object TRANSLUCENT_MOVING_BLOCK_PROGRAM() { return wrapperContained.TRANSLUCENT_MOVING_BLOCK_PROGRAM; }
// public Object ARMOR_CUTOUT_NO_CULL_PROGRAM() { return wrapperContained.ARMOR_CUTOUT_NO_CULL_PROGRAM; }
// public Object ENTITY_SOLID_PROGRAM() { return wrapperContained.ENTITY_SOLID_PROGRAM; }
// public Object ENTITY_CUTOUT_PROGRAM() { return wrapperContained.ENTITY_CUTOUT_PROGRAM; }
// public Object ENTITY_CUTOUT_NONULL_PROGRAM() { return wrapperContained.ENTITY_CUTOUT_NONULL_PROGRAM; }
// public float VIEW_OFFSET_Z_LAYERING_SCALE() { return wrapperContained.VIEW_OFFSET_Z_LAYERING_SCALE; }
// public Object TEXT_INTENSITY_PROGRAM() { return wrapperContained.TEXT_INTENSITY_PROGRAM; }
// public Object TRANSPARENT_TEXT_INTENSITY_PROGRAM() { return wrapperContained.TRANSPARENT_TEXT_INTENSITY_PROGRAM; }
// public Object ENTITY_TRANSLUCENT_EMISSIVE_PROGRAM() { return wrapperContained.ENTITY_TRANSLUCENT_EMISSIVE_PROGRAM; }
// public Object TEXT_BACKGROUND_PROGRAM() { return wrapperContained.TEXT_BACKGROUND_PROGRAM; }
// public Object TRANSPARENT_TEXT_BACKGROUND_PROGRAM() { return wrapperContained.TRANSPARENT_TEXT_BACKGROUND_PROGRAM; }
// public Object BIGGER_DEPTH_TEST() { return wrapperContained.BIGGER_DEPTH_TEST; }
// public Object NO_COLOR_LOGIC() { return wrapperContained.NO_COLOR_LOGIC; }
// public Object OR_REVERSE() { return wrapperContained.OR_REVERSE; }
// public Object GUI_PROGRAM() { return wrapperContained.GUI_PROGRAM; }
// public Object GUI_OVERLAY_PROGRAM() { return wrapperContained.GUI_OVERLAY_PROGRAM; }
// public Object GUI_TEXT_HIGHLIGHT_PROGRAM() { return wrapperContained.GUI_TEXT_HIGHLIGHT_PROGRAM; }
// public Object GUI_GHOST_RECIPE_OVERLAY_PROGRAM() { return wrapperContained.GUI_GHOST_RECIPE_OVERLAY_PROGRAM; }
// public Object BREEZE_WIND_PROGRAM() { return wrapperContained.BREEZE_WIND_PROGRAM; }
// public Object CLOUDS_PROGRAM() { return wrapperContained.CLOUDS_PROGRAM; }
public void startDrawing() { wrapperContained.startDrawing(); }
// public void setupGlintTexturing(float scale) { wrapperContained.setupGlintTexturing(scale); }
public void endDrawing() { wrapperContained.endDrawing(); }

}