package yarnwrap.network.codec;
public class PacketCodec { public net.minecraft.network.codec.PacketCodec wrapperContained; public PacketCodec(net.minecraft.network.codec.PacketCodec wrapperContained) { this.wrapperContained = wrapperContained; }

public yarnwrap.network.codec.PacketCodec cast() { return new yarnwrap.network.codec.PacketCodec(wrapperContained.cast()); }
// public static yarnwrap.network.codec.PacketCodec cast() { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.cast()); }
// public yarnwrap.network.codec.PacketCodec unit(java.lang.Object value) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.unit(value)); }
// public static yarnwrap.network.codec.PacketCodec unit(java.lang.Object value, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.unit(value)); }
public yarnwrap.network.codec.PacketCodec xmap(java.util.function.Function to,java.util.function.Function from) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.xmap(to,from)); }
// public static yarnwrap.network.codec.PacketCodec xmap(java.util.function.Function to,java.util.function.Function from, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.xmap(to,from)); }
// public yarnwrap.network.codec.PacketCodec collect(Object function) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.collect(function)); }
// public static yarnwrap.network.codec.PacketCodec collect(Object function, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.collect(function)); }
// public yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec,java.util.function.Function from,java.util.function.Function to) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.tuple(codec.wrapperContained,from,to)); }
// public static yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec,java.util.function.Function from,java.util.function.Function to, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.tuple(codec.wrapperContained,from,to)); }
// public yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,java.util.function.BiFunction to) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,to)); }
// public static yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,java.util.function.BiFunction to, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,to)); }
// public yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,com.mojang.datafixers.util.Function3 to) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,to)); }
// public static yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,com.mojang.datafixers.util.Function3 to, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,to)); }
// public yarnwrap.network.codec.PacketCodec ofStatic(yarnwrap.network.codec.PacketEncoder encoder,yarnwrap.network.codec.PacketDecoder decoder) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.ofStatic(encoder.wrapperContained,decoder.wrapperContained)); }
// public static yarnwrap.network.codec.PacketCodec ofStatic(yarnwrap.network.codec.PacketEncoder encoder,yarnwrap.network.codec.PacketDecoder decoder, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.ofStatic(encoder.wrapperContained,decoder.wrapperContained)); }
// public yarnwrap.network.codec.PacketCodec of(yarnwrap.network.codec.ValueFirstEncoder encoder,yarnwrap.network.codec.PacketDecoder decoder) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.of(encoder.wrapperContained,decoder.wrapperContained)); }
// public static yarnwrap.network.codec.PacketCodec of(yarnwrap.network.codec.ValueFirstEncoder encoder,yarnwrap.network.codec.PacketDecoder decoder, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.of(encoder.wrapperContained,decoder.wrapperContained)); }
public yarnwrap.network.codec.PacketCodec mapBuf(java.util.function.Function function) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.mapBuf(function)); }
// public static yarnwrap.network.codec.PacketCodec mapBuf(java.util.function.Function function, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.mapBuf(function)); }
public yarnwrap.network.codec.PacketCodec dispatch(java.util.function.Function type,java.util.function.Function codec) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.dispatch(type,codec)); }
// public static yarnwrap.network.codec.PacketCodec dispatch(java.util.function.Function type,java.util.function.Function codec, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.dispatch(type,codec)); }
// public yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,yarnwrap.network.codec.PacketCodec codec4,java.util.function.Function from4,com.mojang.datafixers.util.Function4 to) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,codec4.wrapperContained,from4,to)); }
// public static yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,yarnwrap.network.codec.PacketCodec codec4,java.util.function.Function from4,com.mojang.datafixers.util.Function4 to, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,codec4.wrapperContained,from4,to)); }
// public yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,yarnwrap.network.codec.PacketCodec codec4,java.util.function.Function from4,yarnwrap.network.codec.PacketCodec codec5,java.util.function.Function from5,com.mojang.datafixers.util.Function5 to) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,codec4.wrapperContained,from4,codec5.wrapperContained,from5,to)); }
// public static yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,yarnwrap.network.codec.PacketCodec codec4,java.util.function.Function from4,yarnwrap.network.codec.PacketCodec codec5,java.util.function.Function from5,com.mojang.datafixers.util.Function5 to, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,codec4.wrapperContained,from4,codec5.wrapperContained,from5,to)); }
// public yarnwrap.network.codec.PacketCodec recursive(java.util.function.UnaryOperator codecGetter) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.recursive(codecGetter)); }
// public static yarnwrap.network.codec.PacketCodec recursive(java.util.function.UnaryOperator codecGetter, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.recursive(codecGetter)); }
// public yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,yarnwrap.network.codec.PacketCodec codec4,java.util.function.Function from4,yarnwrap.network.codec.PacketCodec codec5,java.util.function.Function from5,yarnwrap.network.codec.PacketCodec codec6,java.util.function.Function from6,com.mojang.datafixers.util.Function6 to) { return new yarnwrap.network.codec.PacketCodec(wrapperContained.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,codec4.wrapperContained,from4,codec5.wrapperContained,from5,codec6.wrapperContained,from6,to)); }
// public static yarnwrap.network.codec.PacketCodec tuple(yarnwrap.network.codec.PacketCodec codec1,java.util.function.Function from1,yarnwrap.network.codec.PacketCodec codec2,java.util.function.Function from2,yarnwrap.network.codec.PacketCodec codec3,java.util.function.Function from3,yarnwrap.network.codec.PacketCodec codec4,java.util.function.Function from4,yarnwrap.network.codec.PacketCodec codec5,java.util.function.Function from5,yarnwrap.network.codec.PacketCodec codec6,java.util.function.Function from6,com.mojang.datafixers.util.Function6 to, ) { return new yarnwrap.network.codec.PacketCodec(net.minecraft.network.codec.PacketCodec.tuple(codec1.wrapperContained,from1,codec2.wrapperContained,from2,codec3.wrapperContained,from3,codec4.wrapperContained,from4,codec5.wrapperContained,from5,codec6.wrapperContained,from6,to)); }

}