package yarnwrap.client.render.block.entity;
public class BannerBlockEntityRenderer { public net.minecraft.client.render.block.entity.BannerBlockEntityRenderer wrapperContained; public BannerBlockEntityRenderer(net.minecraft.client.render.block.entity.BannerBlockEntityRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public int ROTATIONS() { return wrapperContained.ROTATIONS; }
// public void ROTATIONS(int value) { wrapperContained.ROTATIONS = value; }
// public static int ROTATIONS() { return net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.ROTATIONS; }
// public static void ROTATIONS(int value, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.ROTATIONS = value; }

// public yarnwrap.client.render.block.entity.model.BannerBlockModel standingModel() { return new yarnwrap.client.render.block.entity.model.BannerBlockModel(wrapperContained.standingModel); }
// public void standingModel(yarnwrap.client.render.block.entity.model.BannerBlockModel value) { wrapperContained.standingModel = value.wrapperContained; }
// public static yarnwrap.client.render.block.entity.model.BannerBlockModel standingModel() { return new yarnwrap.client.render.block.entity.model.BannerBlockModel(net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.standingModel); }
// public static void standingModel(yarnwrap.client.render.block.entity.model.BannerBlockModel value, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.standingModel = value.wrapperContained; }

// public yarnwrap.client.render.block.entity.model.BannerBlockModel wallModel() { return new yarnwrap.client.render.block.entity.model.BannerBlockModel(wrapperContained.wallModel); }
// public void wallModel(yarnwrap.client.render.block.entity.model.BannerBlockModel value) { wrapperContained.wallModel = value.wrapperContained; }
// public static yarnwrap.client.render.block.entity.model.BannerBlockModel wallModel() { return new yarnwrap.client.render.block.entity.model.BannerBlockModel(net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.wallModel); }
// public static void wallModel(yarnwrap.client.render.block.entity.model.BannerBlockModel value, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.wallModel = value.wrapperContained; }

// public yarnwrap.client.render.block.entity.model.BannerFlagBlockModel standingFlagModel() { return new yarnwrap.client.render.block.entity.model.BannerFlagBlockModel(wrapperContained.standingFlagModel); }
// public void standingFlagModel(yarnwrap.client.render.block.entity.model.BannerFlagBlockModel value) { wrapperContained.standingFlagModel = value.wrapperContained; }
// public static yarnwrap.client.render.block.entity.model.BannerFlagBlockModel standingFlagModel() { return new yarnwrap.client.render.block.entity.model.BannerFlagBlockModel(net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.standingFlagModel); }
// public static void standingFlagModel(yarnwrap.client.render.block.entity.model.BannerFlagBlockModel value, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.standingFlagModel = value.wrapperContained; }

// public yarnwrap.client.render.block.entity.model.BannerFlagBlockModel wallFlagModel() { return new yarnwrap.client.render.block.entity.model.BannerFlagBlockModel(wrapperContained.wallFlagModel); }
// public void wallFlagModel(yarnwrap.client.render.block.entity.model.BannerFlagBlockModel value) { wrapperContained.wallFlagModel = value.wrapperContained; }
// public static yarnwrap.client.render.block.entity.model.BannerFlagBlockModel wallFlagModel() { return new yarnwrap.client.render.block.entity.model.BannerFlagBlockModel(net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.wallFlagModel); }
// public static void wallFlagModel(yarnwrap.client.render.block.entity.model.BannerFlagBlockModel value, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.wallFlagModel = value.wrapperContained; }

public BannerBlockEntityRenderer(yarnwrap.client.render.entity.model.LoadedEntityModels models) { this.wrapperContained = new net.minecraft.client.render.block.entity.BannerBlockEntityRenderer(models.wrapperContained); }
// public BannerBlockEntityRenderer(Object context) { this.wrapperContained = new net.minecraft.client.render.block.entity.BannerBlockEntityRenderer(context); }
// public void renderCanvas(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.client.model.ModelPart canvas,yarnwrap.client.util.SpriteIdentifier baseSprite,boolean isBanner,yarnwrap.util.DyeColor color,yarnwrap.component.type.BannerPatternsComponent patterns,boolean glint,boolean solid) { wrapperContained.renderCanvas(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,canvas.wrapperContained,baseSprite.wrapperContained,isBanner,color.wrapperContained,patterns.wrapperContained,glint,solid); }
// public static void renderCanvas(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.client.model.ModelPart canvas,yarnwrap.client.util.SpriteIdentifier baseSprite,boolean isBanner,yarnwrap.util.DyeColor color,yarnwrap.component.type.BannerPatternsComponent patterns,boolean glint,boolean solid, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.renderCanvas(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,canvas.wrapperContained,baseSprite.wrapperContained,isBanner,color.wrapperContained,patterns.wrapperContained,glint,solid); }
// public void renderCanvas(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.client.model.ModelPart canvas,yarnwrap.client.util.SpriteIdentifier baseSprite,boolean isBanner,yarnwrap.util.DyeColor color,yarnwrap.component.type.BannerPatternsComponent patterns) { wrapperContained.renderCanvas(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,canvas.wrapperContained,baseSprite.wrapperContained,isBanner,color.wrapperContained,patterns.wrapperContained); }
// public static void renderCanvas(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.client.model.ModelPart canvas,yarnwrap.client.util.SpriteIdentifier baseSprite,boolean isBanner,yarnwrap.util.DyeColor color,yarnwrap.component.type.BannerPatternsComponent patterns, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.renderCanvas(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,canvas.wrapperContained,baseSprite.wrapperContained,isBanner,color.wrapperContained,patterns.wrapperContained); }
// public void renderLayer(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.client.model.ModelPart canvas,yarnwrap.client.util.SpriteIdentifier textureId,yarnwrap.util.DyeColor color) { wrapperContained.renderLayer(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,canvas.wrapperContained,textureId.wrapperContained,color.wrapperContained); }
// public static void renderLayer(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.client.model.ModelPart canvas,yarnwrap.client.util.SpriteIdentifier textureId,yarnwrap.util.DyeColor color, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.renderLayer(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,canvas.wrapperContained,textureId.wrapperContained,color.wrapperContained); }
// public void render(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,float rotation,yarnwrap.client.render.block.entity.model.BannerBlockModel model,yarnwrap.client.render.block.entity.model.BannerFlagBlockModel flagModel,float sway,yarnwrap.util.DyeColor baseColor,yarnwrap.component.type.BannerPatternsComponent patterns) { wrapperContained.render(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,rotation,model.wrapperContained,flagModel.wrapperContained,sway,baseColor.wrapperContained,patterns.wrapperContained); }
// public static void render(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,float rotation,yarnwrap.client.render.block.entity.model.BannerBlockModel model,yarnwrap.client.render.block.entity.model.BannerFlagBlockModel flagModel,float sway,yarnwrap.util.DyeColor baseColor,yarnwrap.component.type.BannerPatternsComponent patterns, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.render(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,rotation,model.wrapperContained,flagModel.wrapperContained,sway,baseColor.wrapperContained,patterns.wrapperContained); }
public void renderAsItem(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.util.DyeColor baseColor,yarnwrap.component.type.BannerPatternsComponent patterns) { wrapperContained.renderAsItem(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,baseColor.wrapperContained,patterns.wrapperContained); }
// public static void renderAsItem(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,yarnwrap.util.DyeColor baseColor,yarnwrap.component.type.BannerPatternsComponent patterns, ) { net.minecraft.client.render.block.entity.BannerBlockEntityRenderer.renderAsItem(matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,baseColor.wrapperContained,patterns.wrapperContained); }

}