package yarnwrap.client.render.block.entity;
public class StructureBlockBlockEntityRenderer { public net.minecraft.client.render.block.entity.StructureBlockBlockEntityRenderer wrapperContained; public StructureBlockBlockEntityRenderer(net.minecraft.client.render.block.entity.StructureBlockBlockEntityRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public StructureBlockBlockEntityRenderer(Object ctx) { this.wrapperContained = new net.minecraft.client.render.block.entity.StructureBlockBlockEntityRenderer(ctx); }
// public void renderInvisibleBlocks(yarnwrap.block.entity.BlockEntity entity,yarnwrap.world.BlockView world,yarnwrap.util.math.BlockPos pos,yarnwrap.util.math.Vec3i size,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.client.util.math.MatrixStack matrices) { wrapperContained.renderInvisibleBlocks(entity.wrapperContained,world.wrapperContained,pos.wrapperContained,size.wrapperContained,vertexConsumers.wrapperContained,matrices.wrapperContained); }
// public static void renderInvisibleBlocks(yarnwrap.block.entity.BlockEntity entity,yarnwrap.world.BlockView world,yarnwrap.util.math.BlockPos pos,yarnwrap.util.math.Vec3i size,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.client.util.math.MatrixStack matrices, ) { net.minecraft.client.render.block.entity.StructureBlockBlockEntityRenderer.renderInvisibleBlocks(entity.wrapperContained,world.wrapperContained,pos.wrapperContained,size.wrapperContained,vertexConsumers.wrapperContained,matrices.wrapperContained); }
// public void renderStructureVoids(yarnwrap.block.entity.BlockEntity entity,yarnwrap.util.math.BlockPos pos,yarnwrap.util.math.Vec3i size,yarnwrap.client.render.VertexConsumer vertexConsumer,yarnwrap.client.util.math.MatrixStack matrices) { wrapperContained.renderStructureVoids(entity.wrapperContained,pos.wrapperContained,size.wrapperContained,vertexConsumer.wrapperContained,matrices.wrapperContained); }
// public static void renderStructureVoids(yarnwrap.block.entity.BlockEntity entity,yarnwrap.util.math.BlockPos pos,yarnwrap.util.math.Vec3i size,yarnwrap.client.render.VertexConsumer vertexConsumer,yarnwrap.client.util.math.MatrixStack matrices, ) { net.minecraft.client.render.block.entity.StructureBlockBlockEntityRenderer.renderStructureVoids(entity.wrapperContained,pos.wrapperContained,size.wrapperContained,vertexConsumer.wrapperContained,matrices.wrapperContained); }
// public void method_61048(yarnwrap.util.math.BlockPos direction,yarnwrap.util.math.BlockPos x,yarnwrap.client.util.math.MatrixStack y,yarnwrap.client.render.VertexConsumer z) { wrapperContained.method_61048(direction.wrapperContained,x.wrapperContained,y.wrapperContained,z.wrapperContained); }
// public static void method_61048(yarnwrap.util.math.BlockPos direction,yarnwrap.util.math.BlockPos x,yarnwrap.client.util.math.MatrixStack y,yarnwrap.client.render.VertexConsumer z, ) { net.minecraft.client.render.block.entity.StructureBlockBlockEntityRenderer.method_61048(direction.wrapperContained,x.wrapperContained,y.wrapperContained,z.wrapperContained); }

}