package yarnwrap.client.render.item;
public class ItemRenderer { public net.minecraft.client.render.item.ItemRenderer wrapperContained; public ItemRenderer(net.minecraft.client.render.item.ItemRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public yarnwrap.util.Identifier ENTITY_ENCHANTMENT_GLINT() { return new yarnwrap.util.Identifier(wrapperContained.ENTITY_ENCHANTMENT_GLINT); }
// public void ENTITY_ENCHANTMENT_GLINT(yarnwrap.util.Identifier value) { wrapperContained.ENTITY_ENCHANTMENT_GLINT = value.wrapperContained; }
public static yarnwrap.util.Identifier ENTITY_ENCHANTMENT_GLINT() { return new yarnwrap.util.Identifier(net.minecraft.client.render.item.ItemRenderer.ENTITY_ENCHANTMENT_GLINT); }
// public static void ENTITY_ENCHANTMENT_GLINT(yarnwrap.util.Identifier value, ) { net.minecraft.client.render.item.ItemRenderer.ENTITY_ENCHANTMENT_GLINT = value.wrapperContained; }

// public yarnwrap.util.Identifier ITEM_ENCHANTMENT_GLINT() { return new yarnwrap.util.Identifier(wrapperContained.ITEM_ENCHANTMENT_GLINT); }
// public void ITEM_ENCHANTMENT_GLINT(yarnwrap.util.Identifier value) { wrapperContained.ITEM_ENCHANTMENT_GLINT = value.wrapperContained; }
public static yarnwrap.util.Identifier ITEM_ENCHANTMENT_GLINT() { return new yarnwrap.util.Identifier(net.minecraft.client.render.item.ItemRenderer.ITEM_ENCHANTMENT_GLINT); }
// public static void ITEM_ENCHANTMENT_GLINT(yarnwrap.util.Identifier value, ) { net.minecraft.client.render.item.ItemRenderer.ITEM_ENCHANTMENT_GLINT = value.wrapperContained; }

// public yarnwrap.client.item.ItemModelManager itemModelManager() { return new yarnwrap.client.item.ItemModelManager(wrapperContained.itemModelManager); }
// public void itemModelManager(yarnwrap.client.item.ItemModelManager value) { wrapperContained.itemModelManager = value.wrapperContained; }
// public static yarnwrap.client.item.ItemModelManager itemModelManager() { return new yarnwrap.client.item.ItemModelManager(net.minecraft.client.render.item.ItemRenderer.itemModelManager); }
// public static void itemModelManager(yarnwrap.client.item.ItemModelManager value, ) { net.minecraft.client.render.item.ItemRenderer.itemModelManager = value.wrapperContained; }

// public yarnwrap.client.render.item.ItemRenderState itemRenderState() { return new yarnwrap.client.render.item.ItemRenderState(wrapperContained.itemRenderState); }
// public void itemRenderState(yarnwrap.client.render.item.ItemRenderState value) { wrapperContained.itemRenderState = value.wrapperContained; }
// public static yarnwrap.client.render.item.ItemRenderState itemRenderState() { return new yarnwrap.client.render.item.ItemRenderState(net.minecraft.client.render.item.ItemRenderer.itemRenderState); }
// public static void itemRenderState(yarnwrap.client.render.item.ItemRenderState value, ) { net.minecraft.client.render.item.ItemRenderer.itemRenderState = value.wrapperContained; }

public ItemRenderer(yarnwrap.client.item.ItemModelManager itemModelManager) { this.wrapperContained = new net.minecraft.client.render.item.ItemRenderer(itemModelManager.wrapperContained); }
public void renderItem(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,yarnwrap.item.ItemDisplayContext displayContext,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.world.World world,int light,int overlay,int seed) { wrapperContained.renderItem(entity.wrapperContained,stack.wrapperContained,displayContext.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,world.wrapperContained,light,overlay,seed); }
// public static void renderItem(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,yarnwrap.item.ItemDisplayContext displayContext,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.world.World world,int light,int overlay,int seed, ) { net.minecraft.client.render.item.ItemRenderer.renderItem(entity.wrapperContained,stack.wrapperContained,displayContext.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,world.wrapperContained,light,overlay,seed); }
public void renderItem(yarnwrap.item.ItemStack stack,yarnwrap.item.ItemDisplayContext displayContext,int light,int overlay,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.world.World world,int seed) { wrapperContained.renderItem(stack.wrapperContained,displayContext.wrapperContained,light,overlay,matrices.wrapperContained,vertexConsumers.wrapperContained,world.wrapperContained,seed); }
// public static void renderItem(yarnwrap.item.ItemStack stack,yarnwrap.item.ItemDisplayContext displayContext,int light,int overlay,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.world.World world,int seed, ) { net.minecraft.client.render.item.ItemRenderer.renderItem(stack.wrapperContained,displayContext.wrapperContained,light,overlay,matrices.wrapperContained,vertexConsumers.wrapperContained,world.wrapperContained,seed); }
// public void renderBakedItemQuads(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumer,java.util.List quads,int tints,int light,int overlay) { wrapperContained.renderBakedItemQuads(matrices.wrapperContained,vertexConsumer.wrapperContained,quads,tints,light,overlay); }
// public static void renderBakedItemQuads(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumer,java.util.List quads,int tints,int light,int overlay, ) { net.minecraft.client.render.item.ItemRenderer.renderBakedItemQuads(matrices.wrapperContained,vertexConsumer.wrapperContained,quads,tints,light,overlay); }
// public yarnwrap.client.render.VertexConsumer getItemGlintConsumer(yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.client.render.RenderLayer layer,boolean solid,boolean glint) { return new yarnwrap.client.render.VertexConsumer(wrapperContained.getItemGlintConsumer(vertexConsumers.wrapperContained,layer.wrapperContained,solid,glint)); }
// public static yarnwrap.client.render.VertexConsumer getItemGlintConsumer(yarnwrap.client.render.VertexConsumerProvider vertexConsumers,yarnwrap.client.render.RenderLayer layer,boolean solid,boolean glint, ) { return new yarnwrap.client.render.VertexConsumer(net.minecraft.client.render.item.ItemRenderer.getItemGlintConsumer(vertexConsumers.wrapperContained,layer.wrapperContained,solid,glint)); }
// public yarnwrap.client.render.VertexConsumer getArmorGlintConsumer(yarnwrap.client.render.VertexConsumerProvider provider,yarnwrap.client.render.RenderLayer layer,boolean glint) { return new yarnwrap.client.render.VertexConsumer(wrapperContained.getArmorGlintConsumer(provider.wrapperContained,layer.wrapperContained,glint)); }
// public static yarnwrap.client.render.VertexConsumer getArmorGlintConsumer(yarnwrap.client.render.VertexConsumerProvider provider,yarnwrap.client.render.RenderLayer layer,boolean glint, ) { return new yarnwrap.client.render.VertexConsumer(net.minecraft.client.render.item.ItemRenderer.getArmorGlintConsumer(provider.wrapperContained,layer.wrapperContained,glint)); }
// public void renderItem(yarnwrap.item.ItemDisplayContext displayContext,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,int tints,java.util.List[] quads,yarnwrap.client.render.RenderLayer layer,Object glint) { wrapperContained.renderItem(displayContext.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,tints,quads,layer.wrapperContained,glint); }
// public static void renderItem(yarnwrap.item.ItemDisplayContext displayContext,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumerProvider vertexConsumers,int light,int overlay,int tints,java.util.List[] quads,yarnwrap.client.render.RenderLayer layer,Object glint, ) { net.minecraft.client.render.item.ItemRenderer.renderItem(displayContext.wrapperContained,matrices.wrapperContained,vertexConsumers.wrapperContained,light,overlay,tints,quads,layer.wrapperContained,glint); }
// public int getTint(int tints,int index) { return wrapperContained.getTint(tints,index); }
// public static int getTint(int tints,int index, ) { return net.minecraft.client.render.item.ItemRenderer.getTint(tints,index); }
// public yarnwrap.client.render.VertexConsumer getSpecialItemGlintConsumer(yarnwrap.client.render.VertexConsumerProvider consumers,yarnwrap.client.render.RenderLayer layer,Object matrix) { return new yarnwrap.client.render.VertexConsumer(wrapperContained.getSpecialItemGlintConsumer(consumers.wrapperContained,layer.wrapperContained,matrix)); }
// public static yarnwrap.client.render.VertexConsumer getSpecialItemGlintConsumer(yarnwrap.client.render.VertexConsumerProvider consumers,yarnwrap.client.render.RenderLayer layer,Object matrix, ) { return new yarnwrap.client.render.VertexConsumer(net.minecraft.client.render.item.ItemRenderer.getSpecialItemGlintConsumer(consumers.wrapperContained,layer.wrapperContained,matrix)); }
// public boolean useTranslucentGlint(yarnwrap.client.render.RenderLayer renderLayer) { return wrapperContained.useTranslucentGlint(renderLayer.wrapperContained); }
// public static boolean useTranslucentGlint(yarnwrap.client.render.RenderLayer renderLayer, ) { return net.minecraft.client.render.item.ItemRenderer.useTranslucentGlint(renderLayer.wrapperContained); }

}