package yarnwrap.client.gui;
public class DrawContext { public net.minecraft.client.gui.DrawContext wrapperContained; public DrawContext(net.minecraft.client.gui.DrawContext wrapperContained) { this.wrapperContained = wrapperContained; }

// public int BACKGROUND_MARGIN() { return wrapperContained.BACKGROUND_MARGIN; }
// public void BACKGROUND_MARGIN(int value) { wrapperContained.BACKGROUND_MARGIN = value; }
// public static int BACKGROUND_MARGIN() { return net.minecraft.client.gui.DrawContext.BACKGROUND_MARGIN; }
// public static void BACKGROUND_MARGIN(int value, ) { net.minecraft.client.gui.DrawContext.BACKGROUND_MARGIN = value; }

// public yarnwrap.client.MinecraftClient client() { return new yarnwrap.client.MinecraftClient(wrapperContained.client); }
// public void client(yarnwrap.client.MinecraftClient value) { wrapperContained.client = value.wrapperContained; }
// public static yarnwrap.client.MinecraftClient client() { return new yarnwrap.client.MinecraftClient(net.minecraft.client.gui.DrawContext.client); }
// public static void client(yarnwrap.client.MinecraftClient value, ) { net.minecraft.client.gui.DrawContext.client = value.wrapperContained; }

// public org.joml.Matrix3x2fStack matrices() { return wrapperContained.matrices; }
// // public void matrices(org.joml.Matrix3x2fStack value) { wrapperContained.matrices = value; }
// public static org.joml.Matrix3x2fStack matrices() { return net.minecraft.client.gui.DrawContext.matrices; }
// // public static void matrices(org.joml.Matrix3x2fStack value, ) { net.minecraft.client.gui.DrawContext.matrices = value; }

// public Object scissorStack() { return wrapperContained.scissorStack; }
// // public void scissorStack(Object value) { wrapperContained.scissorStack = value; }
// // public static Object scissorStack() { return net.minecraft.client.gui.DrawContext.scissorStack; }
// // public static void scissorStack(Object value, ) { net.minecraft.client.gui.DrawContext.scissorStack = value; }

// public yarnwrap.client.texture.GuiAtlasManager guiAtlasManager() { return new yarnwrap.client.texture.GuiAtlasManager(wrapperContained.guiAtlasManager); }
// public void guiAtlasManager(yarnwrap.client.texture.GuiAtlasManager value) { wrapperContained.guiAtlasManager = value.wrapperContained; }
// public static yarnwrap.client.texture.GuiAtlasManager guiAtlasManager() { return new yarnwrap.client.texture.GuiAtlasManager(net.minecraft.client.gui.DrawContext.guiAtlasManager); }
// public static void guiAtlasManager(yarnwrap.client.texture.GuiAtlasManager value, ) { net.minecraft.client.gui.DrawContext.guiAtlasManager = value.wrapperContained; }

// public yarnwrap.client.gui.render.state.GuiRenderState state() { return new yarnwrap.client.gui.render.state.GuiRenderState(wrapperContained.state); }
// public void state(yarnwrap.client.gui.render.state.GuiRenderState value) { wrapperContained.state = value.wrapperContained; }
// public static yarnwrap.client.gui.render.state.GuiRenderState state() { return new yarnwrap.client.gui.render.state.GuiRenderState(net.minecraft.client.gui.DrawContext.state); }
// public static void state(yarnwrap.client.gui.render.state.GuiRenderState value, ) { net.minecraft.client.gui.DrawContext.state = value.wrapperContained; }

// public java.lang.Runnable tooltipDrawer() { return wrapperContained.tooltipDrawer; }
// public void tooltipDrawer(java.lang.Runnable value) { wrapperContained.tooltipDrawer = value; }
// public static java.lang.Runnable tooltipDrawer() { return net.minecraft.client.gui.DrawContext.tooltipDrawer; }
// public static void tooltipDrawer(java.lang.Runnable value, ) { net.minecraft.client.gui.DrawContext.tooltipDrawer = value; }

// public DrawContext(yarnwrap.client.MinecraftClient client,yarnwrap.client.gui.render.state.GuiRenderState state) { this.wrapperContained = new net.minecraft.client.gui.DrawContext(client.wrapperContained,state.wrapperContained); }
// public DrawContext(yarnwrap.client.MinecraftClient client,org.joml.Matrix3x2fStack matrices,yarnwrap.client.gui.render.state.GuiRenderState state) { this.wrapperContained = new net.minecraft.client.gui.DrawContext(client.wrapperContained,matrices,state.wrapperContained); }
// public void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int textureWidth,int textureHeight) { wrapperContained.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,textureWidth,textureHeight); }
// public static void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int textureWidth,int textureHeight, ) { net.minecraft.client.gui.DrawContext.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,textureWidth,textureHeight); }
// public void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int textureWidth,int textureHeight,int color) { wrapperContained.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,textureWidth,textureHeight,color); }
// public static void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int textureWidth,int textureHeight,int color, ) { net.minecraft.client.gui.DrawContext.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,textureWidth,textureHeight,color); }
// public void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int regionWidth,int regionHeight,int textureWidth,int textureHeight,int color) { wrapperContained.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,regionWidth,regionHeight,textureWidth,textureHeight,color); }
// public static void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int regionWidth,int regionHeight,int textureWidth,int textureHeight,int color, ) { net.minecraft.client.gui.DrawContext.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,regionWidth,regionHeight,textureWidth,textureHeight,color); }
public void fill(int x1,int y1,int x2,int y2,int color) { wrapperContained.fill(x1,y1,x2,y2,color); }
// public static void fill(int x1,int y1,int x2,int y2,int color, ) { net.minecraft.client.gui.DrawContext.fill(x1,y1,x2,y2,color); }
// public void drawTexturedQuad(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x1,int x2,int y1,int y2,float u1,float u2,float v1,float v2,int color) { wrapperContained.drawTexturedQuad(pipeline,sprite.wrapperContained,x1,x2,y1,y2,u1,u2,v1,v2,color); }
// public static void drawTexturedQuad(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x1,int x2,int y1,int y2,float u1,float u2,float v1,float v2,int color, ) { net.minecraft.client.gui.DrawContext.drawTexturedQuad(pipeline,sprite.wrapperContained,x1,x2,y1,y2,u1,u2,v1,v2,color); }
public void fillGradient(int startX,int startY,int endX,int endY,int colorStart,int colorEnd) { wrapperContained.fillGradient(startX,startY,endX,endY,colorStart,colorEnd); }
// public static void fillGradient(int startX,int startY,int endX,int endY,int colorStart,int colorEnd, ) { net.minecraft.client.gui.DrawContext.fillGradient(startX,startY,endX,endY,colorStart,colorEnd); }
public void drawCenteredTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,java.lang.String text,int centerX,int y,int color) { wrapperContained.drawCenteredTextWithShadow(textRenderer.wrapperContained,text,centerX,y,color); }
// public static void drawCenteredTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,java.lang.String text,int centerX,int y,int color, ) { net.minecraft.client.gui.DrawContext.drawCenteredTextWithShadow(textRenderer.wrapperContained,text,centerX,y,color); }
// public void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int regionWidth,int regionHeight,int textureWidth,int textureHeight) { wrapperContained.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,regionWidth,regionHeight,textureWidth,textureHeight); }
// public static void drawTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,float u,float v,int width,int height,int regionWidth,int regionHeight,int textureWidth,int textureHeight, ) { net.minecraft.client.gui.DrawContext.drawTexture(pipeline,sprite.wrapperContained,x,y,u,v,width,height,regionWidth,regionHeight,textureWidth,textureHeight); }
public void drawTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,java.lang.String text,int x,int y,int color) { wrapperContained.drawTextWithShadow(textRenderer.wrapperContained,text,x,y,color); }
// public static void drawTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,java.lang.String text,int x,int y,int color, ) { net.minecraft.client.gui.DrawContext.drawTextWithShadow(textRenderer.wrapperContained,text,x,y,color); }
public void drawCenteredTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int centerX,int y,int color) { wrapperContained.drawCenteredTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,centerX,y,color); }
// public static void drawCenteredTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int centerX,int y,int color, ) { net.minecraft.client.gui.DrawContext.drawCenteredTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,centerX,y,color); }
public void drawTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,int color) { wrapperContained.drawTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,x,y,color); }
// public static void drawTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,int color, ) { net.minecraft.client.gui.DrawContext.drawTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,x,y,color); }
public void drawCenteredTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.OrderedText text,int centerX,int y,int color) { wrapperContained.drawCenteredTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,centerX,y,color); }
// public static void drawCenteredTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.OrderedText text,int centerX,int y,int color, ) { net.minecraft.client.gui.DrawContext.drawCenteredTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,centerX,y,color); }
public void drawTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.OrderedText text,int x,int y,int color) { wrapperContained.drawTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,x,y,color); }
// public static void drawTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.OrderedText text,int x,int y,int color, ) { net.minecraft.client.gui.DrawContext.drawTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,x,y,color); }
public void enableScissor(int x1,int y1,int x2,int y2) { wrapperContained.enableScissor(x1,y1,x2,y2); }
// public static void enableScissor(int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.enableScissor(x1,y1,x2,y2); }
public void disableScissor() { wrapperContained.disableScissor(); }
// public static void disableScissor() { net.minecraft.client.gui.DrawContext.disableScissor(); }
// public void fill(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,int x1,int y1,int x2,int y2,int z) { wrapperContained.fill(pipeline,x1,y1,x2,y2,z); }
// public static void fill(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,int x1,int y1,int x2,int y2,int z, ) { net.minecraft.client.gui.DrawContext.fill(pipeline,x1,y1,x2,y2,z); }
public void drawBorder(int x,int y,int width,int height,int color) { wrapperContained.drawBorder(x,y,width,height,color); }
// public static void drawBorder(int x,int y,int width,int height,int color, ) { net.minecraft.client.gui.DrawContext.drawBorder(x,y,width,height,color); }
public int getScaledWindowWidth() { return wrapperContained.getScaledWindowWidth(); }
// public static int getScaledWindowWidth() { return net.minecraft.client.gui.DrawContext.getScaledWindowWidth(); }
public void drawItem(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,int x,int y,int seed) { wrapperContained.drawItem(entity.wrapperContained,stack.wrapperContained,x,y,seed); }
// public static void drawItem(yarnwrap.entity.LivingEntity entity,yarnwrap.item.ItemStack stack,int x,int y,int seed, ) { net.minecraft.client.gui.DrawContext.drawItem(entity.wrapperContained,stack.wrapperContained,x,y,seed); }
// public void drawItem(yarnwrap.entity.LivingEntity entity,yarnwrap.world.World world,yarnwrap.item.ItemStack stack,int x,int y,int seed) { wrapperContained.drawItem(entity.wrapperContained,world.wrapperContained,stack.wrapperContained,x,y,seed); }
// public static void drawItem(yarnwrap.entity.LivingEntity entity,yarnwrap.world.World world,yarnwrap.item.ItemStack stack,int x,int y,int seed, ) { net.minecraft.client.gui.DrawContext.drawItem(entity.wrapperContained,world.wrapperContained,stack.wrapperContained,x,y,seed); }
public void drawItem(yarnwrap.item.ItemStack item,int x,int y) { wrapperContained.drawItem(item.wrapperContained,x,y); }
// public static void drawItem(yarnwrap.item.ItemStack item,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawItem(item.wrapperContained,x,y); }
public void drawItem(yarnwrap.item.ItemStack stack,int x,int y,int seed) { wrapperContained.drawItem(stack.wrapperContained,x,y,seed); }
// public static void drawItem(yarnwrap.item.ItemStack stack,int x,int y,int seed, ) { net.minecraft.client.gui.DrawContext.drawItem(stack.wrapperContained,x,y,seed); }
public void drawText(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.OrderedText text,int x,int y,int color,boolean shadow) { wrapperContained.drawText(textRenderer.wrapperContained,text.wrapperContained,x,y,color,shadow); }
// public static void drawText(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.OrderedText text,int x,int y,int color,boolean shadow, ) { net.minecraft.client.gui.DrawContext.drawText(textRenderer.wrapperContained,text.wrapperContained,x,y,color,shadow); }
public void drawStackOverlay(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y) { wrapperContained.drawStackOverlay(textRenderer.wrapperContained,stack.wrapperContained,x,y); }
// public static void drawStackOverlay(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawStackOverlay(textRenderer.wrapperContained,stack.wrapperContained,x,y); }
public void drawStackOverlay(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y,java.lang.String stackCountText) { wrapperContained.drawStackOverlay(textRenderer.wrapperContained,stack.wrapperContained,x,y,stackCountText); }
// public static void drawStackOverlay(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y,java.lang.String stackCountText, ) { net.minecraft.client.gui.DrawContext.drawStackOverlay(textRenderer.wrapperContained,stack.wrapperContained,x,y,stackCountText); }
// public void drawText(yarnwrap.client.font.TextRenderer textRenderer,java.lang.String x,int y,int color,int shadow) { wrapperContained.drawText(textRenderer.wrapperContained,x,y,color,shadow); }
// public static void drawText(yarnwrap.client.font.TextRenderer textRenderer,java.lang.String x,int y,int color,int shadow, ) { net.minecraft.client.gui.DrawContext.drawText(textRenderer.wrapperContained,x,y,color,shadow); }
public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y) { wrapperContained.drawTooltip(textRenderer.wrapperContained,text,x,y); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,text,x,y); }
// public void drawTooltipImmediately(yarnwrap.client.font.TextRenderer textRenderer,java.util.List components,int x,int y,yarnwrap.client.gui.tooltip.TooltipPositioner positioner,yarnwrap.util.Identifier texture) { wrapperContained.drawTooltipImmediately(textRenderer.wrapperContained,components,x,y,positioner.wrapperContained,texture.wrapperContained); }
// public static void drawTooltipImmediately(yarnwrap.client.font.TextRenderer textRenderer,java.util.List components,int x,int y,yarnwrap.client.gui.tooltip.TooltipPositioner positioner,yarnwrap.util.Identifier texture, ) { net.minecraft.client.gui.DrawContext.drawTooltipImmediately(textRenderer.wrapperContained,components,x,y,positioner.wrapperContained,texture.wrapperContained); }
// public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,yarnwrap.client.gui.tooltip.TooltipPositioner positioner,int x,int y,boolean focused) { wrapperContained.drawTooltip(textRenderer.wrapperContained,text,positioner.wrapperContained,x,y,focused); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,yarnwrap.client.gui.tooltip.TooltipPositioner positioner,int x,int y,boolean focused, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,text,positioner.wrapperContained,x,y,focused); }
public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,java.util.Optional data,int x,int y,yarnwrap.util.Identifier texture) { wrapperContained.drawTooltip(textRenderer.wrapperContained,text,data,x,y,texture.wrapperContained); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,java.util.Optional data,int x,int y,yarnwrap.util.Identifier texture, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,text,data,x,y,texture.wrapperContained); }
public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y) { wrapperContained.drawTooltip(textRenderer.wrapperContained,text.wrapperContained,x,y); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,text.wrapperContained,x,y); }
public void drawText(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,int color,boolean shadow) { wrapperContained.drawText(textRenderer.wrapperContained,text.wrapperContained,x,y,color,shadow); }
// public static void drawText(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,int color,boolean shadow, ) { net.minecraft.client.gui.DrawContext.drawText(textRenderer.wrapperContained,text.wrapperContained,x,y,color,shadow); }
public void drawWrappedText(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.StringVisitable text,int x,int y,int width,int color,boolean shadow) { wrapperContained.drawWrappedText(textRenderer.wrapperContained,text.wrapperContained,x,y,width,color,shadow); }
// public static void drawWrappedText(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.StringVisitable text,int x,int y,int width,int color,boolean shadow, ) { net.minecraft.client.gui.DrawContext.drawWrappedText(textRenderer.wrapperContained,text.wrapperContained,x,y,width,color,shadow); }
public void drawHoverEvent(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Style style,int x,int y) { wrapperContained.drawHoverEvent(textRenderer.wrapperContained,style.wrapperContained,x,y); }
// public static void drawHoverEvent(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Style style,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawHoverEvent(textRenderer.wrapperContained,style.wrapperContained,x,y); }
public int getScaledWindowHeight() { return wrapperContained.getScaledWindowHeight(); }
// public static int getScaledWindowHeight() { return net.minecraft.client.gui.DrawContext.getScaledWindowHeight(); }
public void drawItemWithoutEntity(yarnwrap.item.ItemStack stack,int x,int y) { wrapperContained.drawItemWithoutEntity(stack.wrapperContained,x,y); }
// public static void drawItemWithoutEntity(yarnwrap.item.ItemStack stack,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawItemWithoutEntity(stack.wrapperContained,x,y); }
public void drawItemTooltip(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y) { wrapperContained.drawItemTooltip(textRenderer.wrapperContained,stack.wrapperContained,x,y); }
// public static void drawItemTooltip(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawItemTooltip(textRenderer.wrapperContained,stack.wrapperContained,x,y); }
public void drawOrderedTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y) { wrapperContained.drawOrderedTooltip(textRenderer.wrapperContained,text,x,y); }
// public static void drawOrderedTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawOrderedTooltip(textRenderer.wrapperContained,text,x,y); }
// public org.joml.Matrix3x2fStack getMatrices() { return wrapperContained.getMatrices(); }
// // public static org.joml.Matrix3x2fStack getMatrices() { return net.minecraft.client.gui.DrawContext.getMatrices(); }
public void drawHorizontalLine(int x1,int x2,int y,int color) { wrapperContained.drawHorizontalLine(x1,x2,y,color); }
// public static void drawHorizontalLine(int x1,int x2,int y,int color, ) { net.minecraft.client.gui.DrawContext.drawHorizontalLine(x1,x2,y,color); }
// public void fill(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.TextureSetup textureSetup,int x1,int y1,int x2,int y2) { wrapperContained.fill(pipeline,textureSetup.wrapperContained,x1,y1,x2,y2); }
// public static void fill(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.TextureSetup textureSetup,int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.fill(pipeline,textureSetup.wrapperContained,x1,y1,x2,y2); }
public void drawVerticalLine(int x,int y1,int y2,int color) { wrapperContained.drawVerticalLine(x,y1,y2,color); }
// public static void drawVerticalLine(int x,int y1,int y2,int color, ) { net.minecraft.client.gui.DrawContext.drawVerticalLine(x,y1,y2,color); }
// public void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,int width,int height) { wrapperContained.drawGuiTexture(pipeline,sprite.wrapperContained,x,y,width,height); }
// public static void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,int width,int height, ) { net.minecraft.client.gui.DrawContext.drawGuiTexture(pipeline,sprite.wrapperContained,x,y,width,height); }
// public void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,int width,int height,int color) { wrapperContained.drawGuiTexture(pipeline,sprite.wrapperContained,x,y,width,height,color); }
// public static void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,int width,int height,int color, ) { net.minecraft.client.gui.DrawContext.drawGuiTexture(pipeline,sprite.wrapperContained,x,y,width,height,color); }
// public void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int textureWidth,int textureHeight,int u,int v,int x,int y,int width,int height,int color) { wrapperContained.drawGuiTexture(pipeline,sprite.wrapperContained,textureWidth,textureHeight,u,v,x,y,width,height,color); }
// public static void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int textureWidth,int textureHeight,int u,int v,int x,int y,int width,int height,int color, ) { net.minecraft.client.gui.DrawContext.drawGuiTexture(pipeline,sprite.wrapperContained,textureWidth,textureHeight,u,v,x,y,width,height,color); }
// public void drawSpriteStretched(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height) { wrapperContained.drawSpriteStretched(pipeline,sprite.wrapperContained,x,y,width,height); }
// public static void drawSpriteStretched(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height, ) { net.minecraft.client.gui.DrawContext.drawSpriteStretched(pipeline,sprite.wrapperContained,x,y,width,height); }
// public void drawSpriteStretched(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height,int color) { wrapperContained.drawSpriteStretched(pipeline,sprite.wrapperContained,x,y,width,height,color); }
// public static void drawSpriteStretched(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height,int color, ) { net.minecraft.client.gui.DrawContext.drawSpriteStretched(pipeline,sprite.wrapperContained,x,y,width,height,color); }
// public void drawSpriteRegion(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int textureWidth,int textureHeight,int u,int v,int x,int y,int width,int height,int color) { wrapperContained.drawSpriteRegion(pipeline,sprite.wrapperContained,textureWidth,textureHeight,u,v,x,y,width,height,color); }
// public static void drawSpriteRegion(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int textureWidth,int textureHeight,int u,int v,int x,int y,int width,int height,int color, ) { net.minecraft.client.gui.DrawContext.drawSpriteRegion(pipeline,sprite.wrapperContained,textureWidth,textureHeight,u,v,x,y,width,height,color); }
// public void drawSpriteTiled(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height,int u,int v,int tileWidth,int tileHeight,int textureWidth,int textureHeight,int color) { wrapperContained.drawSpriteTiled(pipeline,sprite.wrapperContained,x,y,width,height,u,v,tileWidth,tileHeight,textureWidth,textureHeight,color); }
// public static void drawSpriteTiled(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height,int u,int v,int tileWidth,int tileHeight,int textureWidth,int textureHeight,int color, ) { net.minecraft.client.gui.DrawContext.drawSpriteTiled(pipeline,sprite.wrapperContained,x,y,width,height,u,v,tileWidth,tileHeight,textureWidth,textureHeight,color); }
// public void drawSpriteNineSliced(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,Object nineSlice,int x,int y,int width,int height,int color) { wrapperContained.drawSpriteNineSliced(pipeline,sprite.wrapperContained,nineSlice,x,y,width,height,color); }
// public static void drawSpriteNineSliced(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.Sprite sprite,Object nineSlice,int x,int y,int width,int height,int color, ) { net.minecraft.client.gui.DrawContext.drawSpriteNineSliced(pipeline,sprite.wrapperContained,nineSlice,x,y,width,height,color); }
public void drawItemWithoutEntity(yarnwrap.item.ItemStack stack,int x,int y,int seed) { wrapperContained.drawItemWithoutEntity(stack.wrapperContained,x,y,seed); }
// public static void drawItemWithoutEntity(yarnwrap.item.ItemStack stack,int x,int y,int seed, ) { net.minecraft.client.gui.DrawContext.drawItemWithoutEntity(stack.wrapperContained,x,y,seed); }
public boolean scissorContains(int x,int y) { return wrapperContained.scissorContains(x,y); }
// public static boolean scissorContains(int x,int y, ) { return net.minecraft.client.gui.DrawContext.scissorContains(x,y); }
public void drawTextWithBackground(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,int width,int color) { wrapperContained.drawTextWithBackground(textRenderer.wrapperContained,text.wrapperContained,x,y,width,color); }
// public static void drawTextWithBackground(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,int width,int color, ) { net.minecraft.client.gui.DrawContext.drawTextWithBackground(textRenderer.wrapperContained,text.wrapperContained,x,y,width,color); }
public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y,yarnwrap.util.Identifier texture) { wrapperContained.drawTooltip(textRenderer.wrapperContained,text,x,y,texture.wrapperContained); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y,yarnwrap.util.Identifier texture, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,text,x,y,texture.wrapperContained); }
public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,java.util.Optional data,int x,int y) { wrapperContained.drawTooltip(textRenderer.wrapperContained,text,data,x,y); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,java.util.Optional data,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,text,data,x,y); }
// public void drawInnerSprite(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,Object nineSlice,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height,int u,int v,int tileWidth,int tileHeight,int textureWidth,int textureHeight,int color) { wrapperContained.drawInnerSprite(pipeline,nineSlice,sprite.wrapperContained,x,y,width,height,u,v,tileWidth,tileHeight,textureWidth,textureHeight,color); }
// public static void drawInnerSprite(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,Object nineSlice,yarnwrap.client.texture.Sprite sprite,int x,int y,int width,int height,int u,int v,int tileWidth,int tileHeight,int textureWidth,int textureHeight,int color, ) { net.minecraft.client.gui.DrawContext.drawInnerSprite(pipeline,nineSlice,sprite.wrapperContained,x,y,width,height,u,v,tileWidth,tileHeight,textureWidth,textureHeight,color); }
public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,yarnwrap.util.Identifier texture) { wrapperContained.drawTooltip(textRenderer.wrapperContained,text.wrapperContained,x,y,texture.wrapperContained); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.Text text,int x,int y,yarnwrap.util.Identifier texture, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,text.wrapperContained,x,y,texture.wrapperContained); }
public void drawOrderedTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y,yarnwrap.util.Identifier texture) { wrapperContained.drawOrderedTooltip(textRenderer.wrapperContained,text,x,y,texture.wrapperContained); }
// public static void drawOrderedTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List text,int x,int y,yarnwrap.util.Identifier texture, ) { net.minecraft.client.gui.DrawContext.drawOrderedTooltip(textRenderer.wrapperContained,text,x,y,texture.wrapperContained); }
// public void drawStackCount(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y,java.lang.String stackCountText) { wrapperContained.drawStackCount(textRenderer.wrapperContained,stack.wrapperContained,x,y,stackCountText); }
// public static void drawStackCount(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.item.ItemStack stack,int x,int y,java.lang.String stackCountText, ) { net.minecraft.client.gui.DrawContext.drawStackCount(textRenderer.wrapperContained,stack.wrapperContained,x,y,stackCountText); }
// public void drawItemBar(yarnwrap.item.ItemStack stack,int x,int y) { wrapperContained.drawItemBar(stack.wrapperContained,x,y); }
// public static void drawItemBar(yarnwrap.item.ItemStack stack,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawItemBar(stack.wrapperContained,x,y); }
// public void drawCooldownProgress(yarnwrap.item.ItemStack stack,int x,int y) { wrapperContained.drawCooldownProgress(stack.wrapperContained,x,y); }
// public static void drawCooldownProgress(yarnwrap.item.ItemStack stack,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawCooldownProgress(stack.wrapperContained,x,y); }
public void drawWrappedTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.StringVisitable text,int x,int y,int width,int color) { wrapperContained.drawWrappedTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,x,y,width,color); }
// public static void drawWrappedTextWithShadow(yarnwrap.client.font.TextRenderer textRenderer,yarnwrap.text.StringVisitable text,int x,int y,int width,int color, ) { net.minecraft.client.gui.DrawContext.drawWrappedTextWithShadow(textRenderer.wrapperContained,text.wrapperContained,x,y,width,color); }
// public void drawTexturedQuad(yarnwrap.util.Identifier sprite,int x1,int y1,int x2,int y2,float u1,float u2,float v1,float v2) { wrapperContained.drawTexturedQuad(sprite.wrapperContained,x1,y1,x2,y2,u1,u2,v1,v2); }
// public static void drawTexturedQuad(yarnwrap.util.Identifier sprite,int x1,int y1,int x2,int y2,float u1,float u2,float v1,float v2, ) { net.minecraft.client.gui.DrawContext.drawTexturedQuad(sprite.wrapperContained,x1,y1,x2,y2,u1,u2,v1,v2); }
// public void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int textureWidth,int textureHeight,int u,int v,int x,int y,int width,int height) { wrapperContained.drawGuiTexture(pipeline,sprite.wrapperContained,textureWidth,textureHeight,u,v,x,y,width,height); }
// public static void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int textureWidth,int textureHeight,int u,int v,int x,int y,int width,int height, ) { net.minecraft.client.gui.DrawContext.drawGuiTexture(pipeline,sprite.wrapperContained,textureWidth,textureHeight,u,v,x,y,width,height); }
// public void drawTexturedQuad(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,com.mojang.blaze3d.textures.GpuTextureView texture,int x1,int y1,int x2,int y2,float u1,float u2,float v1,float v2,int color) { wrapperContained.drawTexturedQuad(pipeline,texture,x1,y1,x2,y2,u1,u2,v1,v2,color); }
// public static void drawTexturedQuad(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,com.mojang.blaze3d.textures.GpuTextureView texture,int x1,int y1,int x2,int y2,float u1,float u2,float v1,float v2,int color, ) { net.minecraft.client.gui.DrawContext.drawTexturedQuad(pipeline,texture,x1,y1,x2,y2,u1,u2,v1,v2,color); }
// public void fill(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.TextureSetup textureSetup,int x1,int y1,int x2,int y2,int color,java.lang.Integer color2) { wrapperContained.fill(pipeline,textureSetup.wrapperContained,x1,y1,x2,y2,color,color2); }
// public static void fill(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.client.texture.TextureSetup textureSetup,int x1,int y1,int x2,int y2,int color,java.lang.Integer color2, ) { net.minecraft.client.gui.DrawContext.fill(pipeline,textureSetup.wrapperContained,x1,y1,x2,y2,color,color2); }
// public void addBookModel(yarnwrap.client.render.entity.model.BookModel bookModel,yarnwrap.util.Identifier texture,float scale,float open,float flip,int x1,int y1,int x2,int y2) { wrapperContained.addBookModel(bookModel.wrapperContained,texture.wrapperContained,scale,open,flip,x1,y1,x2,y2); }
// public static void addBookModel(yarnwrap.client.render.entity.model.BookModel bookModel,yarnwrap.util.Identifier texture,float scale,float open,float flip,int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.addBookModel(bookModel.wrapperContained,texture.wrapperContained,scale,open,flip,x1,y1,x2,y2); }
// public void addSign(yarnwrap.client.model.Model signModel,float scale,yarnwrap.block.WoodType woodType,int x1,int y1,int x2,int y2) { wrapperContained.addSign(signModel.wrapperContained,scale,woodType.wrapperContained,x1,y1,x2,y2); }
// public static void addSign(yarnwrap.client.model.Model signModel,float scale,yarnwrap.block.WoodType woodType,int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.addSign(signModel.wrapperContained,scale,woodType.wrapperContained,x1,y1,x2,y2); }
// public void addPlayerSkin(yarnwrap.client.render.entity.model.PlayerEntityModel playerModel,yarnwrap.util.Identifier texture,float scale,float xRotation,float yRotation,float yPivot,int x1,int y1,int x2,int y2) { wrapperContained.addPlayerSkin(playerModel.wrapperContained,texture.wrapperContained,scale,xRotation,yRotation,yPivot,x1,y1,x2,y2); }
// public static void addPlayerSkin(yarnwrap.client.render.entity.model.PlayerEntityModel playerModel,yarnwrap.util.Identifier texture,float scale,float xRotation,float yRotation,float yPivot,int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.addPlayerSkin(playerModel.wrapperContained,texture.wrapperContained,scale,xRotation,yRotation,yPivot,x1,y1,x2,y2); }
// public void addBannerResult(yarnwrap.client.model.ModelPart flag,yarnwrap.util.DyeColor baseColor,yarnwrap.component.type.BannerPatternsComponent resultBannerPatterns,int x1,int y1,int x2,int y2) { wrapperContained.addBannerResult(flag.wrapperContained,baseColor.wrapperContained,resultBannerPatterns.wrapperContained,x1,y1,x2,y2); }
// public static void addBannerResult(yarnwrap.client.model.ModelPart flag,yarnwrap.util.DyeColor baseColor,yarnwrap.component.type.BannerPatternsComponent resultBannerPatterns,int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.addBannerResult(flag.wrapperContained,baseColor.wrapperContained,resultBannerPatterns.wrapperContained,x1,y1,x2,y2); }
// public void addEntity(yarnwrap.client.render.entity.state.EntityRenderState entityState,float scale,org.joml.Vector3f translation,org.joml.Quaternionf rotation,org.joml.Quaternionf overrideCameraAngle,int x1,int y1,int x2,int y2) { wrapperContained.addEntity(entityState.wrapperContained,scale,translation,rotation,overrideCameraAngle,x1,y1,x2,y2); }
// public static void addEntity(yarnwrap.client.render.entity.state.EntityRenderState entityState,float scale,org.joml.Vector3f translation,org.joml.Quaternionf rotation,org.joml.Quaternionf overrideCameraAngle,int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.addEntity(entityState.wrapperContained,scale,translation,rotation,overrideCameraAngle,x1,y1,x2,y2); }
// public void drawMap(yarnwrap.client.render.MapRenderState mapState) { wrapperContained.drawMap(mapState.wrapperContained); }
// public static void drawMap(yarnwrap.client.render.MapRenderState mapState, ) { net.minecraft.client.gui.DrawContext.drawMap(mapState.wrapperContained); }
// public void addProfilerChart(java.util.List chartData,int x1,int y1,int x2,int y2) { wrapperContained.addProfilerChart(chartData,x1,y1,x2,y2); }
// public static void addProfilerChart(java.util.List chartData,int x1,int y1,int x2,int y2, ) { net.minecraft.client.gui.DrawContext.addProfilerChart(chartData,x1,y1,x2,y2); }
// public void createNewRootLayer() { wrapperContained.createNewRootLayer(); }
// public static void createNewRootLayer() { net.minecraft.client.gui.DrawContext.createNewRootLayer(); }
// public void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List components,int x,int y,yarnwrap.client.gui.tooltip.TooltipPositioner positioner,yarnwrap.util.Identifier texture,boolean focused) { wrapperContained.drawTooltip(textRenderer.wrapperContained,components,x,y,positioner.wrapperContained,texture.wrapperContained,focused); }
// public static void drawTooltip(yarnwrap.client.font.TextRenderer textRenderer,java.util.List components,int x,int y,yarnwrap.client.gui.tooltip.TooltipPositioner positioner,yarnwrap.util.Identifier texture,boolean focused, ) { net.minecraft.client.gui.DrawContext.drawTooltip(textRenderer.wrapperContained,components,x,y,positioner.wrapperContained,texture.wrapperContained,focused); }
// public void drawTooltip(java.util.List text,int x,int y) { wrapperContained.drawTooltip(text,x,y); }
// public static void drawTooltip(java.util.List text,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawTooltip(text,x,y); }
// public void method_71275(java.util.List datax) { wrapperContained.method_71275(datax); }
// public static void method_71275(java.util.List datax, ) { net.minecraft.client.gui.DrawContext.method_71275(datax); }
// public void drawTooltip(yarnwrap.text.Text text,int x,int y) { wrapperContained.drawTooltip(text.wrapperContained,x,y); }
// public static void drawTooltip(yarnwrap.text.Text text,int x,int y, ) { net.minecraft.client.gui.DrawContext.drawTooltip(text.wrapperContained,x,y); }
// public void applyBlur() { wrapperContained.applyBlur(); }
// public static void applyBlur() { net.minecraft.client.gui.DrawContext.applyBlur(); }
// public void renderTooltip() { wrapperContained.renderTooltip(); }
// public static void renderTooltip() { net.minecraft.client.gui.DrawContext.renderTooltip(); }
// public void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,int width,int height,float alpha) { wrapperContained.drawGuiTexture(pipeline,sprite.wrapperContained,x,y,width,height,alpha); }
// public static void drawGuiTexture(com.mojang.blaze3d.pipeline.RenderPipeline pipeline,yarnwrap.util.Identifier sprite,int x,int y,int width,int height,float alpha, ) { net.minecraft.client.gui.DrawContext.drawGuiTexture(pipeline,sprite.wrapperContained,x,y,width,height,alpha); }

}