package yarnwrap.client.render.entity;
public class BipedEntityRenderer { public net.minecraft.client.render.entity.BipedEntityRenderer wrapperContained; public BipedEntityRenderer(net.minecraft.client.render.entity.BipedEntityRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public BipedEntityRenderer(Object context,yarnwrap.client.render.entity.model.BipedEntityModel model,float shadowRadius) { this.wrapperContained = new net.minecraft.client.render.entity.BipedEntityRenderer(context,model.wrapperContained,shadowRadius); }
// public BipedEntityRenderer(Object context,yarnwrap.client.render.entity.model.BipedEntityModel model,yarnwrap.client.render.entity.model.BipedEntityModel babyModel,float scale) { this.wrapperContained = new net.minecraft.client.render.entity.BipedEntityRenderer(context,model.wrapperContained,babyModel.wrapperContained,scale); }
// public BipedEntityRenderer(Object context,yarnwrap.client.render.entity.model.BipedEntityModel model,yarnwrap.client.render.entity.model.BipedEntityModel babyModel,float scale,Object headTransformation) { this.wrapperContained = new net.minecraft.client.render.entity.BipedEntityRenderer(context,model.wrapperContained,babyModel.wrapperContained,scale,headTransformation); }
// public void updateBipedRenderState(yarnwrap.entity.LivingEntity entity,yarnwrap.client.render.entity.state.BipedEntityRenderState state,float tickProgress,yarnwrap.client.item.ItemModelManager itemModelResolver) { wrapperContained.updateBipedRenderState(entity.wrapperContained,state.wrapperContained,tickProgress,itemModelResolver.wrapperContained); }
// public static void updateBipedRenderState(yarnwrap.entity.LivingEntity entity,yarnwrap.client.render.entity.state.BipedEntityRenderState state,float tickProgress,yarnwrap.client.item.ItemModelManager itemModelResolver, ) { net.minecraft.client.render.entity.BipedEntityRenderer.updateBipedRenderState(entity.wrapperContained,state.wrapperContained,tickProgress,itemModelResolver.wrapperContained); }
// public yarnwrap.util.Arm getPreferredArm(yarnwrap.entity.LivingEntity entity) { return new yarnwrap.util.Arm(wrapperContained.getPreferredArm(entity.wrapperContained)); }
// public static yarnwrap.util.Arm getPreferredArm(yarnwrap.entity.LivingEntity entity, ) { return new yarnwrap.util.Arm(net.minecraft.client.render.entity.BipedEntityRenderer.getPreferredArm(entity.wrapperContained)); }
// public Object getArmPose(yarnwrap.entity.mob.MobEntity entity,yarnwrap.util.Arm arm) { return wrapperContained.getArmPose(entity.wrapperContained,arm.wrapperContained); }
// public static Object getArmPose(yarnwrap.entity.mob.MobEntity entity,yarnwrap.util.Arm arm, ) { return net.minecraft.client.render.entity.BipedEntityRenderer.getArmPose(entity.wrapperContained,arm.wrapperContained); }
// public yarnwrap.item.ItemStack getEquippedStack(yarnwrap.entity.LivingEntity entity,yarnwrap.entity.EquipmentSlot slot) { return new yarnwrap.item.ItemStack(wrapperContained.getEquippedStack(entity.wrapperContained,slot.wrapperContained)); }
// public static yarnwrap.item.ItemStack getEquippedStack(yarnwrap.entity.LivingEntity entity,yarnwrap.entity.EquipmentSlot slot, ) { return new yarnwrap.item.ItemStack(net.minecraft.client.render.entity.BipedEntityRenderer.getEquippedStack(entity.wrapperContained,slot.wrapperContained)); }

}