package yarnwrap.client.render.block;
public class BlockModelRenderer { public net.minecraft.client.render.block.BlockModelRenderer wrapperContained; public BlockModelRenderer(net.minecraft.client.render.block.BlockModelRenderer wrapperContained) { this.wrapperContained = wrapperContained; }

// public net.minecraft.util.math.Direction[] DIRECTIONS() { return wrapperContained.DIRECTIONS; }
// public int BRIGHTNESS_CACHE_MAX_SIZE() { return wrapperContained.BRIGHTNESS_CACHE_MAX_SIZE; }
// public yarnwrap.client.color.block.BlockColors colors() { return new yarnwrap.client.color.block.BlockColors(wrapperContained.colors); }
// public java.lang.ThreadLocal BRIGHTNESS_CACHE() { return wrapperContained.BRIGHTNESS_CACHE; }
public void enableBrightnessCache() { wrapperContained.enableBrightnessCache(); }
public void disableBrightnessCache() { wrapperContained.disableBrightnessCache(); }
// public void renderQuad(yarnwrap.world.BlockRenderView world,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos,yarnwrap.client.render.VertexConsumer vertexConsumer,Object matrixEntry,yarnwrap.client.render.model.BakedQuad quad,float brightness0,float brightness1,float brightness2,float brightness3,int light0,int light1,int light2,int light3,int overlay) { wrapperContained.renderQuad(world.wrapperContained,state.wrapperContained,pos.wrapperContained,vertexConsumer.wrapperContained,matrixEntry,quad.wrapperContained,brightness0,brightness1,brightness2,brightness3,light0,light1,light2,light3,overlay); }
public void renderSmooth(yarnwrap.world.BlockRenderView world,yarnwrap.client.render.model.BakedModel model,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumer,boolean cull,yarnwrap.util.math.random.Random random,long seed,int overlay) { wrapperContained.renderSmooth(world.wrapperContained,model.wrapperContained,state.wrapperContained,pos.wrapperContained,matrices.wrapperContained,vertexConsumer.wrapperContained,cull,random.wrapperContained,seed,overlay); }
// public void renderQuadsSmooth(yarnwrap.world.BlockRenderView world,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumer,java.util.List quads,float box,java.util.BitSet[] flags,Object ambientOcclusionCalculator,int overlay) { wrapperContained.renderQuadsSmooth(world.wrapperContained,state.wrapperContained,pos.wrapperContained,matrices.wrapperContained,vertexConsumer.wrapperContained,quads,box,flags,ambientOcclusionCalculator,overlay); }
// public void getQuadDimensions(yarnwrap.world.BlockRenderView world,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos,int vertexData,net.minecraft.util.math.Direction[] face,float box,java.util.BitSet[] flags) { wrapperContained.getQuadDimensions(world.wrapperContained,state.wrapperContained,pos.wrapperContained,vertexData,face,box,flags); }
// public void renderQuads(Object entry,yarnwrap.client.render.VertexConsumer vertexConsumer,float red,float green,float blue,java.util.List quads,int light,int overlay) { wrapperContained.renderQuads(entry,vertexConsumer.wrapperContained,red,green,blue,quads,light,overlay); }
// public void render(Object entry,yarnwrap.client.render.VertexConsumer vertexConsumer,yarnwrap.block.BlockState state,yarnwrap.client.render.model.BakedModel bakedModel,float red,float green,float blue,int light,int overlay) { wrapperContained.render(entry,vertexConsumer.wrapperContained,state.wrapperContained,bakedModel.wrapperContained,red,green,blue,light,overlay); }
// public void renderQuadsFlat(yarnwrap.world.BlockRenderView world,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos,int light,int overlay,boolean useWorldLight,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumer,java.util.List quads,java.util.BitSet flags) { wrapperContained.renderQuadsFlat(world.wrapperContained,state.wrapperContained,pos.wrapperContained,light,overlay,useWorldLight,matrices.wrapperContained,vertexConsumer.wrapperContained,quads,flags); }
public void renderFlat(yarnwrap.world.BlockRenderView world,yarnwrap.client.render.model.BakedModel model,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumer,boolean cull,yarnwrap.util.math.random.Random random,long seed,int overlay) { wrapperContained.renderFlat(world.wrapperContained,model.wrapperContained,state.wrapperContained,pos.wrapperContained,matrices.wrapperContained,vertexConsumer.wrapperContained,cull,random.wrapperContained,seed,overlay); }
public void render(yarnwrap.world.BlockRenderView world,yarnwrap.client.render.model.BakedModel model,yarnwrap.block.BlockState state,yarnwrap.util.math.BlockPos pos,yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumer,boolean cull,yarnwrap.util.math.random.Random random,long seed,int overlay) { wrapperContained.render(world.wrapperContained,model.wrapperContained,state.wrapperContained,pos.wrapperContained,matrices.wrapperContained,vertexConsumer.wrapperContained,cull,random.wrapperContained,seed,overlay); }

}