package yarnwrap.client.render;
public class VertexRendering { public net.minecraft.client.render.VertexRendering wrapperContained; public VertexRendering(net.minecraft.client.render.VertexRendering wrapperContained) { this.wrapperContained = wrapperContained; }

// public void drawBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,double x1,double y1,double z1,double x2,double y2,double z2,float red,float green,float blue,float alpha) { wrapperContained.drawBox(matrices.wrapperContained,vertexConsumers.wrapperContained,x1,y1,z1,x2,y2,z2,red,green,blue,alpha); }
// public static void drawBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,double x1,double y1,double z1,double x2,double y2,double z2,float red,float green,float blue,float alpha, ) { net.minecraft.client.render.VertexRendering.drawBox(matrices.wrapperContained,vertexConsumers.wrapperContained,x1,y1,z1,x2,y2,z2,red,green,blue,alpha); }
// public void drawBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,double x1,double y1,double z1,double x2,double y2,double z2,float red,float green,float blue,float alpha,float xAxisRed,float yAxisGreen,float zAxisBlue) { wrapperContained.drawBox(matrices.wrapperContained,vertexConsumers.wrapperContained,x1,y1,z1,x2,y2,z2,red,green,blue,alpha,xAxisRed,yAxisGreen,zAxisBlue); }
// public static void drawBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,double x1,double y1,double z1,double x2,double y2,double z2,float red,float green,float blue,float alpha,float xAxisRed,float yAxisGreen,float zAxisBlue, ) { net.minecraft.client.render.VertexRendering.drawBox(matrices.wrapperContained,vertexConsumers.wrapperContained,x1,y1,z1,x2,y2,z2,red,green,blue,alpha,xAxisRed,yAxisGreen,zAxisBlue); }
// public void drawFilledBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,float minX,float minY,float minZ,float maxX,float maxY,float maxZ,float red,float green,float blue,float alpha) { wrapperContained.drawFilledBox(matrices.wrapperContained,vertexConsumers.wrapperContained,minX,minY,minZ,maxX,maxY,maxZ,red,green,blue,alpha); }
// public static void drawFilledBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,float minX,float minY,float minZ,float maxX,float maxY,float maxZ,float red,float green,float blue,float alpha, ) { net.minecraft.client.render.VertexRendering.drawFilledBox(matrices.wrapperContained,vertexConsumers.wrapperContained,minX,minY,minZ,maxX,maxY,maxZ,red,green,blue,alpha); }
// public void drawBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,yarnwrap.util.math.Box box,float red,float green,float blue,float alpha) { wrapperContained.drawBox(matrices.wrapperContained,vertexConsumers.wrapperContained,box.wrapperContained,red,green,blue,alpha); }
// public static void drawBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,yarnwrap.util.math.Box box,float red,float green,float blue,float alpha, ) { net.minecraft.client.render.VertexRendering.drawBox(matrices.wrapperContained,vertexConsumers.wrapperContained,box.wrapperContained,red,green,blue,alpha); }
// public void drawOutline(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,yarnwrap.util.shape.VoxelShape shape,double offsetX,double offsetY,double offsetZ,int color) { wrapperContained.drawOutline(matrices.wrapperContained,vertexConsumers.wrapperContained,shape.wrapperContained,offsetX,offsetY,offsetZ,color); }
// public static void drawOutline(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,yarnwrap.util.shape.VoxelShape shape,double offsetX,double offsetY,double offsetZ,int color, ) { net.minecraft.client.render.VertexRendering.drawOutline(matrices.wrapperContained,vertexConsumers.wrapperContained,shape.wrapperContained,offsetX,offsetY,offsetZ,color); }
// public void drawSide(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,yarnwrap.util.math.Direction side,float minX,float minY,float minZ,float maxX,float maxY,float maxZ,float red,float green,float blue,float alpha) { wrapperContained.drawSide(matrices.wrapperContained,vertexConsumers.wrapperContained,side.wrapperContained,minX,minY,minZ,maxX,maxY,maxZ,red,green,blue,alpha); }
// public static void drawSide(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,yarnwrap.util.math.Direction side,float minX,float minY,float minZ,float maxX,float maxY,float maxZ,float red,float green,float blue,float alpha, ) { net.minecraft.client.render.VertexRendering.drawSide(matrices.wrapperContained,vertexConsumers.wrapperContained,side.wrapperContained,minX,minY,minZ,maxX,maxY,maxZ,red,green,blue,alpha); }
// public void drawVector(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,org.joml.Vector3f offset,yarnwrap.util.math.Vec3d vec,int argb) { wrapperContained.drawVector(matrices.wrapperContained,vertexConsumers.wrapperContained,offset,vec.wrapperContained,argb); }
// public static void drawVector(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,org.joml.Vector3f offset,yarnwrap.util.math.Vec3d vec,int argb, ) { net.minecraft.client.render.VertexRendering.drawVector(matrices.wrapperContained,vertexConsumers.wrapperContained,offset,vec.wrapperContained,argb); }
// public void method_62299(yarnwrap.client.render.VertexConsumer x1,Object y1,double z1,double x2,double y2,int z2) { wrapperContained.method_62299(x1.wrapperContained,y1,z1,x2,y2,z2); }
// public static void method_62299(yarnwrap.client.render.VertexConsumer x1,Object y1,double z1,double x2,double y2,int z2, ) { net.minecraft.client.render.VertexRendering.method_62299(x1.wrapperContained,y1,z1,x2,y2,z2); }
// public void drawFilledBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,double minX,double minY,double minZ,double maxX,double maxY,double maxZ,float red,float green,float blue,float alpha) { wrapperContained.drawFilledBox(matrices.wrapperContained,vertexConsumers.wrapperContained,minX,minY,minZ,maxX,maxY,maxZ,red,green,blue,alpha); }
// public static void drawFilledBox(yarnwrap.client.util.math.MatrixStack matrices,yarnwrap.client.render.VertexConsumer vertexConsumers,double minX,double minY,double minZ,double maxX,double maxY,double maxZ,float red,float green,float blue,float alpha, ) { net.minecraft.client.render.VertexRendering.drawFilledBox(matrices.wrapperContained,vertexConsumers.wrapperContained,minX,minY,minZ,maxX,maxY,maxZ,red,green,blue,alpha); }

}